import { makeStyles, tokens } from '@fluentui/react-components';

export const useKustoToolCreateDialogStyles = makeStyles({
    dialogSurface: {
        minWidth: 'fit-content',
        padding: '0px',
    },
    dialogBody: {
        display: 'flex',
        flexDirection: 'column',
        gap: '0px',
        height: '100%',
    },
    fullScreenBody: {
        display: 'flex',
        flexDirection: 'column',
        gap: '0px',
        height: '0px',
        flex: '1 1 auto',
    },
    dialogTitleWrapper: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '24px 24px',
        borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    },
    dialogTitle: {
        margin: '0px',
    },
    dialogContent: {
        display: 'flex',
        flexDirection: 'column'
    },
    fullScreenContent: {
        flex: '1 1 auto',
        height: '0px',
        display: 'flex',
        flexDirection: 'column'
    },
    toolForm: {
        display: 'flex',
        padding: tokens.spacingVerticalXL,
        overflowX: 'auto',
        flex: '1 1 auto',
        height: '0%',
        flexDirection: 'row',
        paddingTop: '0px',
        paddingBottom: '0px',
    },
    toolFormLeft: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingHorizontalXL,
        minWidth: '600px',
        flex: '1 1 50%',
        paddingTop: '16px',
        paddingRight: '16px',
        paddingBottom: '16px',
        overflowY: 'auto',
    },
    toolFormDivider: {
        backgroundColor: tokens.colorNeutralStroke1,
        width: '1px',
        alignSelf: 'stretch',
        padding: '0px',
    },
    toolFormRight: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        gap: tokens.spacingVerticalL,
        alignSelf: 'stretch',
        minWidth: '600px',
        flex: '1 1 50%',
        paddingTop: '16px',
        paddingBottom: '16px',
        paddingLeft: '16px',
    },
    dialogActions: {
        display: 'flex',
        justifyContent: 'flex-end',
        padding: tokens.spacingHorizontalL,
        borderTop: `1px solid ${tokens.colorNeutralStroke1}`,
    },
    toolbarButton: {
        fontWeight: 'normal',
        padding: '2px 8px',
    },
    parametersAccordion: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
    },
    parameterAccordionHeader: {
        display: 'flex',
        alignItems: 'center',
        flex: 1,
        justifyContent: 'space-between',
        gap: tokens.spacingHorizontalM,
        fontWeight: 600,
    },
    parameterAccordionItem: {
        border: `1px solid ${tokens.colorNeutralStroke1}`,
        borderRadius: tokens.borderRadiusMedium,
    },
    parameterAccordionDescription: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingHorizontalS,
        padding: `${0} ${tokens.spacingHorizontalM} ${tokens.spacingVerticalM}`,
        margin: 0,
    },
    parameterNameAndType: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: tokens.spacingHorizontalXS,
        width: '100%',
        alignItems: 'start',
    },
    testPanelHeader: { display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '12px', width: '100%' },
    testPanelMessageBar: { width: '100%', maxWidth: '600px', textWrap: 'wrap' },
    emptyContent: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '20px',
        width: '100%',
        maxHeight: '364px',
        flexGrow: 1,
    },
    testResultsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
        width: '100%',
        flex: '1 1 auto',
        height: '0px',
    },
    testResultsHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'baseline',
        flexWrap: 'wrap',
        gap: tokens.spacingHorizontalS,
    },
    testResultsTableWrapper: {
        width: '100%',
        overflowX: 'auto',
    },
    testResultsTable: {
        width: '100%',
        borderCollapse: 'collapse',
        fontSize: tokens.fontSizeBase200,
    },
    testResultsTableHead: {
        backgroundColor: tokens.colorNeutralBackground3,
    },
    testResultsTableHeader: {
        textAlign: 'left',
        padding: tokens.spacingHorizontalXS,
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        fontWeight: tokens.fontWeightSemibold,
    },
    testResultsTableCell: {
        padding: tokens.spacingHorizontalXS,
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        fontFamily: tokens.fontFamilyMonospace,
        whiteSpace: 'nowrap',
    },
    testValueAccordionItem: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
    },
    testValueColumnHeaders: {
        display: 'grid',
        gridTemplateColumns: '2.5fr 2.5fr 1fr',
        gap: tokens.spacingHorizontalS,
        marginBottom: tokens.spacingVerticalXS,
        alignItems: 'center',
        width: '100%',
    },
    testParameterInputs: {
        display: 'grid',
        gridTemplateColumns: '2.5fr 2.5fr 1fr',
        gap: tokens.spacingHorizontalS,
        alignItems: 'flex-start',
        width: '100%',
        marginBottom: tokens.spacingVerticalXS,
    },
});
