# Documentation for branch policy: https://aka.ms/gim/docs/policy/branch-protection

name: Default branch protection policy
description: Requires two reviewers for merges into main branch
resource: repository
where:
configuration:
  branchProtectionRules:
    - branchNamePattern: "main"
      requiredApprovingReviewsCount: 2
      restrictsPushes: true
      requireLastPushApproval: true
      requiresConversationResolution: true
      requiresPullRequestBeforeMerging: true
      dismissStaleReviews: true
      allowsForcePushes: true
      isAdminEnforced: false
      whoCanPush: []
      requiredStatusChecks:
      - GitOps/AdvancedSecurity
      - build-dotnet
      - build-frontend-agent
      - build-frontend-portal
      - Run Evaluation Tests
      # - E2E Container Tests # The test code had issue handling async PATCH
    - branchNamePattern: "release/*"
      requiredApprovingReviewsCount: 2
      restrictsPushes: true
      requireLastPushApproval: true
      requiresConversationResolution: true
      requiresPullRequestBeforeMerging: true
      dismissStaleReviews: true
      allowsForcePushes: true
      isAdminEnforced: false
      whoCanPush:
      - k4appscore
      - srea-devs
      requiredStatusChecks:
      - GitOps/AdvancedSecurity
      - build-dotnet
      - build-frontend-agent
      - build-frontend-portal
      - Run Evaluation Tests
      # - E2E Container Tests # The test code had issue handling async PATCH
    - branchNamePattern: "rcaagent-port-new-framework"
      requiredApprovingReviewsCount: 2
      restrictsPushes: true
      requireLastPushApproval: true
      requiresConversationResolution: true
      requiresPullRequestBeforeMerging: true
      dismissStaleReviews: true
      allowsForcePushes: true
      isAdminEnforced: false
      whoCanPush:
      - k4appscore
      - srea-devs
      requiredStatusChecks:
      - GitOps/AdvancedSecurity
      - build-dotnet
      - build-frontend-agent
      - build-frontend-portal
