<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agent.Cli\Agent.Cli.csproj" />
    <ProjectReference Include="..\Agent.Web\Agent.Web.csproj" />
    <ProjectReference Include="..\Agent.Runtime\Agent.Runtime.csproj" />
    <ProjectReference Include="..\Agent.Core\Agent.Core.csproj" />
    <ProjectReference Include="..\Agent.Data\Agent.Data.csproj" />
  </ItemGroup>

</Project>
