let fromDate = datetime("##fromDate##");
let endDate = datetime("##toDate##");
let environmentName =  "##managedClusterName##";
SwiftNetworkingEvents
| where TIMESTAMP between (fromDate .. endDate)
| where EnvironmentName == environmentName
| where msg has "Customer DNS Servers are >> "
| summarize emptyDNSServersCount = countif(msg == "Customer DNS Servers are >> "), totalCount = count()
| project  isCustomDNSConfigured = case(
    totalCount > 0 and emptyDNSServersCount == totalCount, "False",
    totalCount > 0 and emptyDNSServersCount == 0, "True",
    totalCount == 0, "Data unavailable",
    "Unknown" // Unknown means DNS configuration changed in the time interval
)
