let startDate = datetime(##fromDate##);
let endDate = datetime(##toDate##);
let regionName = "##regionName##";
let querySubscription = "##subscriptionId##";
let queryResourceGroup =  "##resourceGroupName##";
let queryClusterName = "##managedClusterName##";
let ccpClusterId = "##ccpClusterId##";

let _aggregator = 'Sum';
let _cx_cluster_idb09d39b9 = ccpClusterId;
let _endTime = endDate;
let _startTime = startDate;
let _group_byb9d0584a = dynamic(null);
let _interval = 'auto';
let _period = '1s';
let _region = dynamic(['regionName']);
let _scrape_jobb9d0584a = dynamic(['kubelet']);
let region = _region;
let cluster_id = _cx_cluster_idb09d39b9;
let scrape_job = _scrape_jobb9d0584a;
let period = totimespan(_period);
let interval = iff(_interval == 'auto', max_of((_endTime-_startTime)/200, 1m), totimespan(_interval));
let aggregator = _aggregator;
let group_by = _group_byb9d0584a;
KubeletRuntimeOperationsErrorsTotal1mIncrease
| where Timestamp between (_startTime  .. _endTime)
| where isempty(_region) or RPTenant in (_region)
| where isempty(_cx_cluster_idb09d39b9) or Labels.cluster_id == _cx_cluster_idb09d39b9 or Labels.namespace == _cx_cluster_idb09d39b9
| where isempty(_scrape_jobb9d0584a) or Labels.job in (_scrape_jobb9d0584a)
| extend region=iff(set_has_element(group_by, "region"), RPTenant, "all")
| extend cluster_id=iff(set_has_element(group_by, "cluster_id"), tostring(Labels.cluster_id), "all")
| extend scrape_job=iff(set_has_element(group_by, "scrape_job"), tostring(Labels.job), "all")
| extend operation_type=tostring(Labels.operation_type)
| summarize Max=max(Value), Avg=avg(Value), Min=min(Value), Count=dcount(SeriesId, 4), Sum=avg(Value)*dcount(SeriesId, 4) by bin(Timestamp, interval), region, cluster_id, scrape_job, operation_type
| project Timestamp, Value=toreal(column_ifexists(_aggregator, "")), region, cluster_id, scrape_job, operation_type
| extend Value=Value*(period/1s)/60
| where Value > 0
| take 1000
