let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let cappNameParam = "##containerAppName##";
let cappResourceGroup = "##resourceGroupName##";
let cappSubscription = "##subscriptionId##";
ContainerAppsAdminEvents
| where PreciseTimeStamp > queryFrom and PreciseTimeStamp < queryTo
| where EventId == 2
| where statusCode != -1
| where requestMethod != "GET"
| where resourceType has "containerApps" or resourceType has "jobs"
| where subscription =~ cappSubscription
| where resourceGroup =~ cappResourceGroup
| where  resourceName =~ cappNameParam or 
    ( isempty(resourceName) and resourceType == "jobs/start" and tolower(requestPath) contains strcat("/microsoft.app/jobs/", cappNameParam))
| extend Health = case(
                       statusCode >= 200 and statusCode <= 299, "Healthy",
                       statusCode >= 300 and statusCode <= 499, "Degraded",
                       statusCode >= 500, "Unhealthy",
                       "Neutral"
                       )
| join kind=leftouter 
    (ContainerAppDBState
     | where PreciseTimeStamp between(queryFrom .. queryTo)
     | where containerAppName == cappNameParam
     | where resourceGroup == cappResourceGroup
     | where subscription == cappSubscription
     | project managedClusterName, env_dt_spanId
) on env_dt_spanId
| project StartTime=PreciseTimeStamp, Content =strcat(requestMethod, " - ", statusCode), GroupBy=managedClusterName1, requestBody, durationInMilliseconds, env_dt_traceId, env_dt_spanId, correlationId, Health
