let fromDate = datetime("##fromDate##");
let toDate = datetime("##toDate##");
let _subscriptionId = "##subscriptionId##";
let _resourceGroupName = "##resourceGroupName##";
let _sessionPoolName =  "##sessionPoolName##";
// Base filtered table
let BaseData = SessionPoolDBState
| where TIMESTAMP between (fromDate .. toDate)
| where subscription == _subscriptionId and resourceGroup == _resourceGroupName and sessionPoolName == _sessionPoolName
;
// Wrapper function for reuse
let TrackChanges = (data: (ComponentType: string, PreciseTimeStamp: datetime, Content: string)) {
    data
    | order by PreciseTimeStamp asc
    | where isnotempty(Content) and Content != ""
    | extend PreviousContent = prev(Content)
    | extend SessionIndex = row_cumsum(iff(Content != PreviousContent, 1, 0))
    | summarize StartTime = min(PreciseTimeStamp), EndTime = max(PreciseTimeStamp) by Content, SessionIndex, ComponentType
    | serialize 
    | extend PreviousContent = prev(Content)
    | extend ChangeStatus = iff(SessionIndex == 1, "No change", "Change")
    | where SessionIndex > 1 // focus only on change
    | project StartTime, EndTime, ComponentType, Value=Content, ChangeStatus, PreviousValue=PreviousContent
    | order by StartTime asc
};
let customContainerTemplateData = BaseData
| where isnotempty(customContainerTemplate)
| extend ComponentType = "Custom Container Session Template"
| project ComponentType, PreciseTimeStamp, Content = customContainerTemplate;
let dynamicPoolConfigurationJsonStringData = BaseData
| where isnotempty(dynamicPoolConfigurationJsonString)
| extend ComponentType = "Dynamic Pool Configuration Json"
| project ComponentType, PreciseTimeStamp, Content = dynamicPoolConfigurationJsonString;
let maxConcurrentSessionsData = BaseData
| where isnotempty(maxConcurrentSessions)
| extend ComponentType = "Max Concurrent Sessions"
| project ComponentType, PreciseTimeStamp, Content = tostring(maxConcurrentSessions);
let poolManagementTypeData = BaseData
| where isnotempty(poolManagementType)
| extend ComponentType = "Pool Management Type"
| project ComponentType, PreciseTimeStamp, Content = poolManagementType;
let legionPodPoolNameData = BaseData
| where isnotempty(legionPodPoolName)
| extend ComponentType = "Legion PodPool Name"
| project ComponentType, PreciseTimeStamp, Content = legionPodPoolName;
// Final union of all change-tracked components
union 
    // Versions
    TrackChanges(customContainerTemplateData),
    TrackChanges(dynamicPoolConfigurationJsonStringData),
    TrackChanges(legionPodPoolNameData),
    TrackChanges(poolManagementTypeData),
    TrackChanges(maxConcurrentSessionsData)
| order by StartTime asc, ComponentType asc
