let startTime = datetime("##fromDate##");
let endTime = datetime("##toDate##");
let cappSubscription = "##subscriptionId##";
let cappResourceGroup = "##resourceGroupName##";
let cappName = "##containerAppName##";
ContainerAppDBState
| where TIMESTAMP between (startTime .. endTime)
| where subscription == cappSubscription
| where resourceGroup == cappResourceGroup
| where containerAppName == cappName
| summarize  max(TIMESTAMP) by managedClusterName
| distinct managedClusterName
