let local_cappName = "##containerAppName##";
let local_cappResourceGroup = "##resourceGroupName##";
let local_cappSubscription = "##subscriptionId##";
let local_location = "##region##";
let globalFrom = datetime("##fromDate##");
let globalTo = datetime("##toDate##");

let testRegions = cluster('cappstest.westus.kusto.windows.net').database('capps').ContainerAppDBState
| where PreciseTimeStamp between (globalFrom .. globalTo);

AllCapps("ContainerAppDBState")
| where PreciseTimeStamp between (globalFrom .. globalTo)
| union testRegions
| where (containerAppName == local_cappName or containerAppsJobName == local_cappName)
      and resourceGroup == local_cappResourceGroup
      and subscription == local_cappSubscription
      and Tenant == local_location
| summarize arg_max(PreciseTimeStamp, provisioningState) by 
    cappName = iif(isempty(containerAppName), containerAppsJobName, containerAppName),
    type = iif(isempty(containerAppName), "job", "containerApp"),
    cappResourceGroup = resourceGroup,
    cappSubscription = subscription,
    environmentType,
    environmentId,
    managedClusterName,    
    createdTimeUtc,
    Region = Tenant,
    workloadProfileType
| join kind=leftouter (GetRegions) on $left.Region == $right.Name
| project
    Region,
    cappName,
    type,
    cappResourceGroup,
    cappSubscription,
    environmentType,
    environmentId,
    managedClusterName,    
    createdTimeUtc,
    provisioningState,
    workloadProfileType,
    KustoUrl = iff(Region contains "Test", "cappstest.westus", KustoUrl)
| order by createdTimeUtc desc
| take 1
