let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let managedClusterName = "##managedClusterName##";
SwiftNetworkingEvents
| where EnvironmentName == managedClusterName
| where PreciseTimeStamp between (queryFrom .. queryTo)
| extend DNSConfigStatus = case(
    msg startswith "DNS Servers are fine, no need to update...", "Healthy",
    msg startswith "Detected Customer DNS Servers Missing in resolv.conf." or msg startswith "Succesfully applied netplan and removed the netplan file", "Degraded",
    ""
)
| where DNSConfigStatus != ""
| project PreciseTimeStamp, DNSConfigStatus,Role
| order by PreciseTimeStamp asc
| extend SessionIndex = row_cumsum(iff(DNSConfigStatus != prev(DNSConfigStatus), 1, 0))
| summarize StartTime = min(PreciseTimeStamp), EndTime = max(PreciseTimeStamp) by DNSConfigStatus,SessionIndex,Role
| project StartTime, EndTime, DNSConfigStatus, Role
