let queryFrom = datetime("##fromDate##"); 
let queryTo = datetime("##toDate##"); 
let clusterName = "##managedClusterName##"; 
let containerAppOrJobName = "##containerAppOrJobName##"; 
let issues = (EventProcessorEvents
| where PreciseTimeStamp >= queryFrom and PreciseTimeStamp <= queryTo
| where EnvironmentName =~ clusterName 
| where isempty(containerAppOrJobName) or ContainerAppName =~ containerAppOrJobName or JobName =~ containerAppOrJobName
| where Internal != bool(False) 
| where Type != "Normal"
| where msg != "Debounce condition"
| summarize count() by Type, msg, Reason
| take 500);
let normal = (EventProcessorEvents
| where PreciseTimeStamp >= queryFrom and PreciseTimeStamp <= queryTo
| where EnvironmentName =~ clusterName 
| where isempty(containerAppOrJobName) or ContainerAppName =~ containerAppOrJobName or JobName =~ containerAppOrJobName
| where Type == "Normal"
| project Type, msg, Reason
| take 1);
issues
| union normal
