let startTime = datetime("##fromDate##");
let endTime = datetime("##toDate##");
let managedClusterName = "##managedClusterName##";
let containerAppName = "##containerAppName##";
EnvoyFrontEndLogsTable
| where TIMESTAMP between (startTime .. endTime)
| where EnvironmentName == managedClusterName
| where Authority contains containerAppName
//| project StartTime, Authority, Method, Path, Protocol, Status, ResponseFlags, ResponseCodeDetails, GrpcStatus, GrpcStatusNumber, RequestDuration, UpstreamHost, UpstreamCluster, UpstreamRequestAttemptCount, BytesRecieved, BytesSent, RevisionName, UserAgent, Role
| summarize FirstSeen=min(StartTime),LastSeen=max(StartTime),max(RequestDuration),count() by Authority, Method, Path, Protocol, Status, ResponseCodeDetails,UpstreamHost
| project FirstSeen,LastSeen,max_RequestDuration,Count=count_,Authority, Method, Path, Protocol, Status, ResponseCodeDetails, UpstreamHost
| order by FirstSeen asc 
| limit 1000
