let startTime = datetime("##fromDate##");
let endTime = datetime("##toDate##");
let managedClusterName = "##managedClusterName##";
EnvoyControllerEvents
| where PreciseTimeStamp between (startTime .. endTime)
| where EnvironmentName == managedClusterName
| where isnotempty(Log) or isnotempty( error )
| project PreciseTimeStamp, Log, msg, error, Role, _ContainerGroupId, _ContainerGroupName, _ContainerId, _ContainerImage, caller
