
let queryFrom = datetime("##fromDate##"); 
let queryTo = datetime("##toDate##"); 
let clusterName = "##managedClusterName##"; 
let containerAppOrJobName = "##containerAppOrJobName##"; 
EventProcessorEvents
| where PreciseTimeStamp >= queryFrom and PreciseTimeStamp <= queryTo
| where EnvironmentName == clusterName 
| where ContainerAppName == containerAppOrJobName or JobName == containerAppOrJobName
| where Internal == bool(False) 
| where Type != "Normal"
| project Type, Message = msg, Reason
| take 1000
