let startTime = datetime("##fromDate##");
let endTime = datetime("##toDate##");
let managedClusterName = "##managedClusterName##";
EnvoyFrontEndEvents
| where PreciseTimeStamp between (startTime .. endTime)
| where EnvironmentName == managedClusterName
| where _ContainerName == "envoy"
| where Log !contains "\"GET /"
| where Log !contains "\"POST /"
| distinct EnvironmentName,Log, Role, _ContainerGroupId, _ContainerGroupName, _ContainerId, _ContainerImage
