let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let managedClusterName = "##managedClusterName##";
let metricName = "##metricName##";
let region = "##region##";
cluster("gcappsprod.northeurope.kusto.windows.net").database("gcapps").
Metrics
| where Timestamp between(queryFrom..queryTo)
| where Region =~ region
| where ClusterName =~ managedClusterName
| where MetricName == metricName
| where Attributes has "name=\"Output_CustomerAppLogs\""
| extend TotalValue=NumSamples*AverageValue
| project Timestamp, MetricName, Attributes, TotalValue
| where TotalValue != 0