let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let capp_name = "##containerAppName##";
let capp_rg = "##resourceGroupName##";
let capp_sub = "##subscriptionId##";
let capp_revision = "##revisionName##";
let managedCluster = toscalar(GetManagedClusterName(capp_name, capp_rg, capp_sub));
ContainerAppControllerEvents
| where TIMESTAMP between (queryFrom .. queryTo)
| where Tenant == managedCluster
| where msg == "HPA Heartbeat"
| where RevisionName == capp_revision
| extend metrics = parse_json(Details).metrics
| mv-expand metric = metrics
| extend metricName = tostring(metric.name)
| extend curr_raw    = todouble(replace("m", "", tostring(metric.currentValue))),
         target_raw  = todouble(replace("m", "", tostring(metric.targetValue)))
| extend current = iif(metric.currentValue  endswith "m", curr_raw   / 1000.0, curr_raw),
         target  = iif(metric.targetValue   endswith "m", target_raw / 1000.0, target_raw)
| summarize current = avg(current),
           target  = avg(target)
        by metricName, TIMESTAMP = bin(TIMESTAMP, 1m)
| project TIMESTAMP, metricName, current, target
| order by metricName, TIMESTAMP asc
