let globalFrom = datetime("##fromDate##");
let globalTo = datetime("##toDate##");
let local_cappName = "##containerAppName##";
let local_revisionName = "##revisionName##";

EventProcessorEvents
| where PreciseTimeStamp between(globalFrom .. globalTo)
| where ContainerAppName == local_cappName
| where RevisionName == local_revisionName
| where msg has "probe failed"
| where Internal = true
| order by PreciseTimeStamp desc
| project PreciseTimeStamp,Type, msg, Reason, Count, EventSource, ReplicaName, RevisionName, level=iff(Type=="Normal","Info","Error")
