let globalFrom = datetime("##fromDate##");
let globalTo = datetime("##toDate##");
let local_environmentLocation = "##region##";
let local_environmentName = "##environmentName##";
let local_environmentResourceGroup = "##resourceGroupName##";
let local_environmentSubscription = "##subscriptionId##";


ManagedEnvironmentDBState
| where PreciseTimeStamp between (globalFrom .. globalTo)
| where environmentName == local_environmentName
  and resourceGroup == local_environmentResourceGroup
  and subscription == local_environmentSubscription
  and Tenant == local_environmentLocation
| order by PreciseTimeStamp desc
| join kind=inner (GetRegions) on $left.Tenant == $right.Name
| project 
    PreciseTimeStamp,
    managedClusterName,
    managedClusterLocation,
    managedSubscription,
    managedClusterCreatedTime,
    powerState,
    provisioningState = managedClusterProvisioningState,
    managedClusterProvisioningError = "<TO BE ADDED>",
    chartVersion,
    isInternal,
    chartVersionUpgradeTime,
    chartVersionUpgradeError = chartVersionUpgradeErrors,
    kubernetesVersion,
    kubernetesVersionUpgradeTime,
    upgradeBatch,
    environmentSubscription = subscription,
    environmentResourceGroup = resourceGroup,
    environmentLocation = Tenant,
    environmentName,
    environmentCreatedTime = environmentClusterCreatedTime,
    hasWorkloadProfiles,
    hasCustomerVnet,
    hasMaintenanceConfiguration,
    publicNetworkAccess,
    hasPrivateEndpoints,
    KustoUrl = iff(Region contains "Test", "cappstest.westus", KustoUrl)
| top 1 by PreciseTimeStamp desc
