let fromTime = datetime("##fromDate##");
let toTime = datetime("##toDate##");
let customerEnvironmentName = "##environmentName##";
let customerResourceGroupName = "##resourceGroupName##";
let customerSubscriptionId = "##subscriptionId##";
ContainerAppsAdminEvents
| where TIMESTAMP between (fromTime .. toTime)
| where operationEntityType in ('KubeEnvironment','ManagedCluster')
| where Level < 3
| where subscription =~ customerSubscriptionId and
        resourceGroup =~ customerResourceGroupName and
        environmentName =~ customerEnvironmentName
| extend exception = iff(isempty(exception), message, exception)
| summarize arg_max(exception, PreciseTimeStamp, managedClusterName,operationType,operationEntityType) by env_dt_traceId
| summarize FirstSeen=min(PreciseTimeStamp),LastSeen=max(PreciseTimeStamp),count=count() by operationType,operationEntityType,exception
| order by FirstSeen asc
| limit 50
