let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let capp_name = "##containerAppName##";
let capp_rg = "##resourceGroupName##";
let capp_sub = "##subscriptionId##";
let capp_revision = "##revisionName##";
let managedClusterName = toscalar(GetManagedClusterName(capp_name, capp_rg, capp_sub));    
All("ContainerAppControllerEvents")
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where msg == "Pod Heartbeat"
| where EnvironmentName == managedClusterName
| where PodName startswith capp_revision
| extend parsedJson = parse_json(RevisionJson)
| extend WorkloadProfileType = tostring(parsedJson.metadata.labels['k8se.microsoft.com/workloadProfileType'])
| extend legionRevisionName = iff(WorkloadProfileType has "consumption", PodName, "")
| summarize arg_max(PreciseTimeStamp, PodStatus) by PodName, EnvironmentName, legionRevisionName
| extend Status = iif(PreciseTimeStamp < queryTo - 30m, "Shut Down", PodStatus)
| extend legionPodName = iif(isempty(legionRevisionName), "", PodName)
| project PodName, EnvironmentName, Status, PreciseTimeStamp, legionPodName
| order by PreciseTimeStamp
