let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let managedClusterName = "##managedClusterName##";
let threshold = toint("##threshold##");
let podNamePrefix = "##podNamePrefix##";
let podNamespace = "##podNamespace##";
EventProcessorEvents
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where EnvironmentName == managedClusterName
| where InvolvedObjectKind == "Pod"
| where InvolvedObjectNamespace == podNamespace
| where InvolvedObjectName contains podNamePrefix
| where Internal == "True"
| where Reason == "ContainerBackOff" or Reason  == "NodeNotReady"
| summarize FailureStartTime = min(PreciseTimeStamp),FailureEndTime =  max(PreciseTimeStamp), FailureCount = count() by Pod = InvolvedObjectName, Node = Role, msg, Reason
| where FailureCount > threshold
