let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let revisionName = "##revisionName##";
let clusterName = "##managedClusterName##";
ContainerAppControllerEvents
| where PreciseTimeStamp between(queryFrom..queryTo)
| where EnvironmentName == clusterName
| where msg == "Pod Heartbeat"
| distinct PodName
| where PodName startswith revisionName
| summarize make_set(PodName);
