let fromDate = datetime("##fromDate##");
let endDate = datetime("##toDate##"); 
let _subscriptionId = "##subscriptionId##";
let _resourceGroupName = "##resourceGroupName##";
let _sessionPoolName =  "##sessionPoolName##";
let sessionPoolPath = strcat("/subscriptions/",_subscriptionId,"/resourceGroups/",_resourceGroupName,"/providers/Microsoft.App/sessionPools/",_sessionPoolName);
let _sessionOperationInstanceId = strcat(_sessionPoolName, "-", _subscriptionId, "-", _resourceGroupName, "-session-pool-create"); 
let updateRequestTraceIds = (ContainerAppsAdminEvents
| where PreciseTimeStamp between (fromDate .. endDate)
| where requestMethod != "GET" and requestMethod != ""
| where requestPath contains sessionPoolPath
| where statusCode != -1
| distinct env_dt_traceId);
let backgroundJobTraceIds = (ContainerAppsAdminEvents
| where PreciseTimeStamp between (fromDate .. endDate) 
| where instanceId endswith _sessionOperationInstanceId
| distinct env_dt_traceId);
ContainerAppsAdminEvents
| where PreciseTimeStamp between (fromDate .. endDate)
| where env_dt_traceId  in (updateRequestTraceIds) or env_dt_traceId in (backgroundJobTraceIds)
| project PreciseTimeStamp, Level, message, exception, poolType, env_dt_traceId
| where Level <= 2
