let queryFrom = datetime("##queryFrom##");
let queryTo = datetime("##queryTo##");
let cappClusterName = "##cappClusterName##";
let jobName = "##jobName##";
ContainerAppControllerEvents
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where EnvironmentName == cappClusterName
| where ContainerAppJobName == jobName
| where msg contains "Job Execution Heartbeat"
| summarize arg_max(PreciseTimeStamp, *) by JobExecutionName
| where JobExecutionStatus == "Failed"
| extend JobExecutionJsonJson = parse_json(JobExecutionJson)
| extend JobExecutionStatusDetails = JobExecutionJsonJson.status
| project PreciseTimeStamp,JobExecutionName, Tenant, msg, JobExecutionStatus, JobExecutionStatusDetails