let queryFrom = datetime("##queryFrom##");
let queryTo = datetime("##queryTo##");
let cappName = "##cappName##";
let cappResourceGroup = "##cappResourceGroup##";
let cappSubscription = "##cappSubscription##";
let cappClusterName = "##cappClusterName##";
ContainerAppControllerEvents
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where EnvironmentName == cappClusterName
| where msg == "Container Apps Job Heartbeat"
| extend json = JobJson
| where isnotempty(json)
| extend itemName = ContainerAppJobName
| where itemName == cappName
| where json contains cappSubscription and json contains cappResourceGroup and json contains cappName
| summarize TimeStampForJobJsonFirstSeen=min(PreciseTimeStamp) by json
| extend d=parse_json(json)
| project TIMESTAMP, Configuration=d.spec.configuration, Template=d.spec.template
| order by TIMESTAMP asc