import { makeStyles, tokens } from '@fluentui/react-components';

export const useScheduledTasksStyles = makeStyles({
    tabRoot: {
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
        position: 'relative',
        flex: 1,
        padding: '16px',
    },
    content: {
        display: 'flex',
        flexDirection: 'column',
        overflowY: 'auto',
        overflowX: 'auto',
        position: 'relative',
        flex: 1,
        padding: '16px',
    },
    title: {
        display: 'flex',
        padding: `${tokens.spacingHorizontalXXL} ${tokens.spacingHorizontalXXL} ${tokens.spacingHorizontalXL} ${tokens.spacingHorizontalXXL}`,
        flexDirection: 'column',
        alignItems: 'flex-start',
        gap: tokens.spacingVerticalXS,
        alignSelf: 'stretch',
    },
    cards: {
        display: 'flex',
        padding: `${tokens.spacingHorizontalNone} ${tokens.spacingHorizontalXL} ${tokens.spacingHorizontalXXXL} ${tokens.spacingHorizontalXL}`,
        alignItems: 'center',
        gap: '9px',
        alignSelf: 'stretch',
        flexWrap: 'wrap',
    },
    card: {
        display: 'flex',
        padding: '12px',
        flexDirection: 'column',
        alignItems: 'flex-start',
        alignSelf: 'stretch',
        flex: '1 1 auto',
        maxWidth: '180px',
    },
    cardContent: {
        display: 'flex',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
    },
    taskOverviewBody: {
        display: 'flex',
        margin: `0 ${tokens.spacingHorizontalXL} ${tokens.spacingHorizontalXL} ${tokens.spacingHorizontalXL}`,
        flexDirection: 'column',
        gap: '16px',
        alignSelf: 'stretch',
        flex: 1,
    },
    toolbar: {
        display: 'flex',
        justifyContent: 'space-between',
        gap: '5px',
        padding: '20px',
        paddingLeft: '0px',
        flexWrap: 'wrap',
    },
    toolbarButtons: {
        display: 'flex',
        gap: '12px',
        flexWrap: 'wrap',
    },
    toolbarButton: {
        fontWeight: 'normal',
        padding: '2px 8px',
    },
    filters: {
        display: 'flex',
        gap: '10px',
        alignItems: 'center',
    },
    searchBox: {
        minWidth: '230px',
        width: 'max-content',
    },
    menuItems: {
        display: 'flex',
        gap: '6px',
        alignItems: 'center',
    },
    taskForm: {
        display: 'flex',
        gap: '24px',
        padding: '12px 0',
        justifyContent: 'space-around',
    },
    taskFormDivider: {
        backgroundColor: '#D1D1D1',
        width: '1px',
        alignSelf: 'stretch',
    },
    taskFormLeft: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingHorizontalXL,
        maxWidth: '460px',
    },
    taskFormRight: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'stretch',
        gap: '24px',
    },
    taskFormTimeFields: {
        display: 'grid',
        alignItems: 'start',
        gridTemplateColumns: 'repeat(auto-fit, minmax(84px, 1fr))',
        gap: '12px',
        '& .fui-Dropdown': {
            minWidth: '0 !important',
            width: '100%',
        },
    },
    timePicker: {
        minWidth: 'initial',
        gridTemplateColumns: 'minmax(0, 1fr) auto',
    },
    taskFormDateFields: {
        display: 'grid',
        alignItems: 'start',
        gridTemplateColumns: '1fr 1fr',
        gap: '12px',
    },
    fieldActionGroup: {
        display: 'inline-flex',
        alignItems: 'center',
    },
    fieldLabelRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        gap: tokens.spacingHorizontalM,
    },
    fieldRequiredStar: {
        color: tokens.colorPaletteRedForeground1,
        fontWeight: tokens.fontWeightRegular,
        lineHeight: 1,
    },
    promptImprovementButton: {
        display: 'flex',
        gap: tokens.spacingHorizontalXS,
        alignItems: 'center',
        fontSize: tokens.fontSizeBase200,
    },
    emptyState: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: tokens.spacingVerticalXXL,
        gap: tokens.spacingVerticalS,
        textAlign: 'center',
    },
    executionsHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalM,
        padding: `${tokens.spacingVerticalL} ${tokens.spacingHorizontalXL}`,
        borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    },
    executionsHeaderTitle: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalXXS,
    },
    backButton: {
        minWidth: 'auto',
    },
});
