// ------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All rights reserved.
// ------------------------------------------------------------

using System.Text.Json;
using System.Text.Json.Serialization;
using Agent.Core;
using Agent.Core.Extensions;
using Agent.Core.Interfaces;
using Agent.Core.Models.Api.v1;
using Agent.Data.Repositories;
using Agent.Framework;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;

namespace Agent.Runtime.Helpers;

/// <summary>
/// Helper class for handling tool result operations specifically for agent tasks/deep investigation.
/// Encapsulates all the logic for saving tool results to agent task storage and managing investigation steps.
/// </summary>
public class AgentTaskToolResultHelper
{
    private readonly ILogger<AgentTaskToolResultHelper> _logger;
    private readonly IAgentTasksRepository _agentTaskRepository;
    private readonly IThreadRepository _threadRepository;
    private readonly IStreamingService _streamingService;

    public AgentTaskToolResultHelper(
        ILogger<AgentTaskToolResultHelper> logger,
        IAgentTasksRepository agentTaskRepository,
        IThreadRepository threadRepository,
        IStreamingService streamingService)
    {
        _logger = logger;
        _agentTaskRepository = agentTaskRepository;
        _threadRepository = threadRepository;
        _streamingService = streamingService;
    }

    string defaultInitialInvestigationToolResultsStepTitle = "Context Gathering Operation Results";
    string defaultInitialInvestigationToolResultsStepSummary = "Results from operations performed during initial investigation";

    string defaultHypothesisToolResultsStepTitle = "Hypothesis Validation Operation Results";
    string defaultHypothesisToolResultsStepDetails = "Results from operations performed during hypothesis validation";

    /// <summary>
    /// Saves a tool execution result to the appropriate investigation step
    /// </summary>
    public async Task SaveToolResultAsync(Guid agentTaskId, InvestigationStepContext? stepContext, ToolExecutionResult result, Guid threadId)
    {
        try
        {
            var agentTask = await _agentTaskRepository.GetAgentTaskAsync(threadId, agentTaskId);
            if (agentTask?.Properties is not IncidentInvestigationTaskProperties properties)
            {
                _logger.LogInternalWarning("Agent task {AgentTaskId} not found or has invalid properties", agentTaskId);
                return;
            }

            // Add result to appropriate step based on context
            if (stepContext == null)
            {
                // Default to initial investigation when no context is available
                var initStep = GetOrCreateDefaultInitialInvestigationStep(properties, defaultInitialInvestigationToolResultsStepTitle);
                initStep.ToolExecutions.Add(result);
                _logger.LogInternalWarning("No step context available for agent task {AgentTaskId}, defaulting to initial investigation", agentTaskId);
            }
            else
            {
                switch (stepContext.StepPhase)
                {
                    case "InitialInvestigation":
                        // For initial investigation, all tool results go into a single default step because steps are generated by the agent
                        // after tool calls complete, so we cant assign results to specific steps during execution.
                        // To Do: In future, if we have more detailed step tracking during initial investigation, we can update this logic.
                        var initStep = GetOrCreateDefaultInitialInvestigationStep(properties, defaultInitialInvestigationToolResultsStepTitle);
                        initStep.ToolExecutions.Add(result);
                        break;

                    case "HypothesisValidation":
                        var hypothesis = GetHypothesisById(properties, stepContext.HypothesisId);
                        if (hypothesis != null)
                        {
                            var hypStep = GetOrCreateDefaultHypothesisStep(hypothesis, stepContext.StepName);
                            hypStep.ToolExecutions.Add(result);
                        }
                        else
                        {
                            _logger.LogInternalWarning("Could not find hypothesis with ID '{HypothesisId}' for tool result", stepContext.HypothesisId);
                        }
                        break;

                    default:
                        _logger.LogInternalWarning("Unknown step phase {StepPhase} for agent task {AgentTaskId}", 
                            stepContext.StepPhase, agentTaskId);
                        return;
                }
            }
            
            await _agentTaskRepository.UpdateAgentTaskAsync(agentTask);
            _logger.LogInternalInformation("Saved tool result {ToolType} to agent task {AgentTaskId}, step {StepPhase}", 
                result.Type, agentTaskId, stepContext?.StepPhase ?? "InitialInvestigation");
        }
        catch (Exception ex)
        {
            _logger.LogInternalError(ex, "Failed to save tool result to agent task {AgentTaskId}", agentTaskId);
        }
    }

    /// <summary>
    /// Finds an existing agentTask from db, then hypothesis step 
    /// </summary>
    /// <param name="agentTaskId">The agent task ID</param>
    /// <param name="threadId">The thread ID</param>
    /// <param name="hypothesisId">The hypothesis ID to search for</param>
    /// <param name="stepTitle">The step title to match</param>
    /// <returns>The existing hypothesis step if found, null otherwise</returns>
    public async Task<HypothesisStep?> FindExistingHypothesisStepAsync(
        Guid agentTaskId, 
        Guid threadId, 
        Guid hypothesisId, 
        string? stepTitle)
    {
        try
        {
            var dbAgentTask = await _agentTaskRepository.GetAgentTaskAsync(threadId, agentTaskId);
            if (dbAgentTask?.Properties is not IncidentInvestigationTaskProperties properties)
            {
                _logger.LogInternalWarning("Agent task {AgentTaskId} not found or has invalid properties", agentTaskId);
                return null;
            }

            // Find hypothesis by ID
            var hypothesis = GetHypothesisById(properties, hypothesisId);
            if (hypothesis == null)
            {
                _logger.LogInternalWarning("Could not find hypothesis with ID '{HypothesisId}'", hypothesisId);
                return null;
            }

            // Find step by title
            var existingStep = hypothesis.Steps
                .FirstOrDefault(s => s.Summary.Equals(stepTitle, StringComparison.OrdinalIgnoreCase));

            if (existingStep != null)
            {
                _logger.LogInternalInformation("Found existing hypothesis step '{StepName}' with {ToolCount} tool executions", 
                    stepTitle, existingStep.ToolExecutions.Count);
            }
            else
            {
                _logger.LogInternalInformation("No existing hypothesis step found for '{StepName}'", stepTitle);
            }

            return existingStep;
        }
        catch (Exception ex)
        {
            _logger.LogInternalError(ex, "Failed to find existing hypothesis step for agent task {AgentTaskId}", agentTaskId);
            return null;
        }
    }

    /// <summary>
    /// Adds tool result to agent chat history as reasoning message so tools arent repeatedly called
    /// </summary>
    public async Task AddToolResultToAgentChatHistoryAsync(Guid threadId, ChatMessage message)
    {
        try
        {
            // Get agent contexts for this thread
            var agentContexts = await _threadRepository.GetAgentContextsForThreadAsync(threadId);
            var agentContext = agentContexts.FirstOrDefault();
            
            if (agentContext == null)
            {
                _logger.LogInternalWarning("No agent context found for thread {ThreadId}, cannot add tool result to chat history", threadId);
                return;
            }

            // Get existing chat history
            var agentChatHistory = await _threadRepository.GetAgentChatHistoryAsync(agentContext.Id);
            if (agentChatHistory == null)
            {
                _logger.LogInternalWarning("No agent chat history found for context {AgentContextId}, cannot add tool result", agentContext.Id);
                return;
            }

            // Create reasoning message from tool result
            var reasoningMessage = message.GetReasoningMessage(agentContext.Id);
            
            // Create and add reasoning message to storage
            await _threadRepository.CreateReasoningMessageAsync(reasoningMessage);
            
            // Add to agent chat history for context
            await _threadRepository.AddReasoningMessagesToChatHistoryAsync(agentChatHistory, new[] { reasoningMessage });
            
            _logger.LogInternalInformation("Successfully added tool result as reasoning message to agent chat history for context {AgentContextId}", agentContext.Id);
        }
        catch (Exception ex)
        {
            _logger.LogInternalError(ex, "Failed to add tool result to agent chat history for thread {ThreadId}", threadId);
        }
    }


    /// <summary>
    ///  finds intial investigation context gathering step by name
    /// </summary>
    /// <param name="properties"></param>
    /// <param name="stepName"></param>
    /// <returns></returns>
    private InitialInvestigationStep? GetInitialInvestigationStepByStepName(IncidentInvestigationTaskProperties properties, string? stepName)
    {
  
        var existingToolResultsStep = properties.InitialInvestigation.GatheringContext.Steps
            .FirstOrDefault(s => s.Title.Equals(stepName, StringComparison.OrdinalIgnoreCase));

        if (existingToolResultsStep != null)
        {
            return existingToolResultsStep;
        }

        return null;
    }


    /// <summary>
    ///  finds intial investigation context gathering step by name and creates default if tool gathering step if it doesnt exist
    /// </summary>
    /// <param name="properties"></param>
    /// <param name="stepName"></param>
    /// <returns></returns>
    private InitialInvestigationStep GetOrCreateDefaultInitialInvestigationStep(IncidentInvestigationTaskProperties properties, string? stepName)
    {

        var existingToolResultsStep = GetInitialInvestigationStepByStepName(properties, stepName);

        if (existingToolResultsStep != null)
        {
            return existingToolResultsStep;
        }

        var newStep = new InitialInvestigationStep
        {
            Title = stepName ?? defaultInitialInvestigationToolResultsStepTitle,
            Summary =  defaultInitialInvestigationToolResultsStepSummary,
            Status = InitialInvestigationStatus.InProgress
        };

        properties.InitialInvestigation.GatheringContext.Steps.Add(newStep);
        return newStep;
    }


    /// <summary>
    /// Finds a hypothesis by its ID using recursive search through all hypotheses and their children.
    /// </summary>
    private HypothesisTreeItem? GetHypothesisById(IncidentInvestigationTaskProperties properties, Guid? hypothesisId)
    {
        if (!hypothesisId.HasValue)
        {
            _logger.LogInternalWarning("GetHypothesisById called with null hypothesisId");
            return null;
        }

        // GetAllHypotheses() recursively finds all hypotheses including direct children and all descendants
        var allHypotheses = properties.FormingHypothesis.GetAllHypotheses();
        
        var hypothesis = allHypotheses.FirstOrDefault(h => h.Id == hypothesisId.Value);
        if (hypothesis != null)
        {
            _logger.LogInternalInformation("Found hypothesis by GUID '{Guid}': '{Description}'", hypothesisId.Value, hypothesis.Description);
            return hypothesis;
        }
        else
        {
            _logger.LogInternalWarning("No hypothesis found with GUID: {Guid} among {TotalCount} hypotheses (including {RootCount} root hypotheses)", 
                hypothesisId.Value, allHypotheses.Count, properties.FormingHypothesis.Hypotheses.Count);
            return null;
        }
    }

    /// <summary>
    ///  finds hypothesis step by name
    /// </summary>
    /// <param name="hypothesis"></param>
    /// <param name="stepName"></param>
    /// <returns></returns>
    private HypothesisStep? GetHypothesisStepByStepName(HypothesisTreeItem hypothesis, string? stepName)
    {
        // If a step with the given name already exists, return it (preserving tool executions)
        if (!string.IsNullOrEmpty(stepName))
        {
            var existingStep = hypothesis.Steps
                .FirstOrDefault(s => s.Summary.Equals(stepName, StringComparison.OrdinalIgnoreCase));
            if (existingStep != null)
            {
                _logger.LogInternalInformation("Found existing hypothesis step '{StepName}' with {ToolCount} tool executions", 
                    stepName, existingStep.ToolExecutions.Count);
                return existingStep;
            }
        }

        _logger.LogInternalInformation("No existing hypothesis step found for '{StepName}'", stepName);
        return null;
    }

    /// <summary>
    ///  finds a hypothesis step by name, if the step doesnt exist it creates default tool results step
    /// </summary>
    /// <param name="hypothesis"></param>
    /// <param name="stepName"></param>
    /// <returns></returns>
    private HypothesisStep GetOrCreateDefaultHypothesisStep(HypothesisTreeItem hypothesis, string? stepName)
    {
        // If a step with the given name already exists, return it (preserving tool executions)
        if (!string.IsNullOrEmpty(stepName))
        {
            var existingStep = GetHypothesisStepByStepName(hypothesis, stepName);
            if (existingStep != null)
            {
                _logger.LogInternalInformation("Found existing hypothesis step '{StepName}' with {ToolCount} tool executions",
                    stepName, existingStep.ToolExecutions.Count);
                return existingStep;
            }
        }

        // Create a default tool results step if none exists
        var newStep = new HypothesisStep
        {
            Summary = stepName ?? defaultHypothesisToolResultsStepTitle,
            Details = defaultHypothesisToolResultsStepDetails
        };
        hypothesis.Steps.Add(newStep);
        _logger.LogInternalInformation("Created new default step  because step '{StepName}' was not found", stepName);
        return newStep;
    }

    #region AzCli


    /// <summary>
    /// Finds and updates an existing AzCli tool execution result, or creates a new one if not found
    /// </summary>
    private async Task SaveOrUpdateAzCliToolResultAsync(Guid agentTaskId, InvestigationStepContext? stepContext, AzCliExecution execution, Guid threadId)
    {
        try
        {
            var agentTask = await _agentTaskRepository.GetAgentTaskAsync(threadId, agentTaskId);
            if (agentTask?.Properties is not IncidentInvestigationTaskProperties properties)
            {
                _logger.LogInternalWarning("Agent task {AgentTaskId} not found or has invalid properties", agentTaskId);
                return;
            }

            // Find existing tool execution by AzCli execution ID
            ToolExecutionResult? existingToolResult = null;
            
            if (stepContext == null)
            {
                // Search in initial investigation steps
                foreach (var step in properties.InitialInvestigation.GatheringContext.Steps)
                {
                    existingToolResult = step.ToolExecutions.FirstOrDefault(te => 
                        te.Type == ToolExecutionType.AzCli && 
                        te.AzCliExecution?.Id == execution.Id);
                    if (existingToolResult != null) break;
                }
            }
            else if (stepContext.StepPhase == "InitialInvestigation")
            {
                // Search in initial investigation steps
                foreach (var step in properties.InitialInvestigation.GatheringContext.Steps)
                {
                    existingToolResult = step.ToolExecutions.FirstOrDefault(te => 
                        te.Type == ToolExecutionType.AzCli && 
                        te.AzCliExecution?.Id == execution.Id);
                    if (existingToolResult != null) break;
                }
            }
            else if (stepContext.StepPhase == "HypothesisValidation")
            {
                // Search in hypothesis steps
                var hypothesis = GetHypothesisById(properties, stepContext.HypothesisId);
                if (hypothesis != null)
                {
                    foreach (var step in hypothesis.Steps)
                    {
                        existingToolResult = step.ToolExecutions.FirstOrDefault(te => 
                            te.Type == ToolExecutionType.AzCli && 
                            te.AzCliExecution?.Id == execution.Id);
                        if (existingToolResult != null) break;
                    }
                }
            }

            if (existingToolResult != null)
            {
                // Update existing tool execution
                existingToolResult.AzCliExecution = execution;
                existingToolResult.ExecutedTimestamp = DateTime.UtcNow;
                _logger.LogInternalInformation("Updated existing AzCli tool execution {ToolExecutionId} with status {Status}", 
                    existingToolResult.Id, execution.Status);
            }
            else
            {
                // Create new tool execution
                var newToolResult = new ToolExecutionResult
                {
                    Type = ToolExecutionType.AzCli,
                    KustoQueryResults = string.Empty, // Frontend uses AzCliExecution object directly
                    ExecutedTimestamp = DateTime.UtcNow,
                    AzCliExecution = execution
                };

                // Add to appropriate step based on context
                if (stepContext == null)
                {
                    var initStep = GetOrCreateDefaultInitialInvestigationStep(properties, defaultInitialInvestigationToolResultsStepTitle);
                    initStep.ToolExecutions.Add(newToolResult);
                }
                else if (stepContext.StepPhase == "InitialInvestigation")
                {
                    var initStep = GetOrCreateDefaultInitialInvestigationStep(properties, defaultInitialInvestigationToolResultsStepTitle);
                    initStep.ToolExecutions.Add(newToolResult);
                }
                else if (stepContext.StepPhase == "HypothesisValidation")
                {
                    var hypothesis = GetHypothesisById(properties, stepContext.HypothesisId);
                    if (hypothesis != null)
                    {
                        var hypStep = GetOrCreateDefaultHypothesisStep(hypothesis, stepContext.StepName);
                        hypStep.ToolExecutions.Add(newToolResult);
                    }
                }

                _logger.LogInternalInformation("Created new AzCli tool execution {ToolExecutionId} with status {Status}", 
                    newToolResult.Id, execution.Status);
            }
            
            await _agentTaskRepository.UpdateAgentTaskAsync(agentTask);
        }
        catch (Exception ex)
        {
            _logger.LogInternalError(ex, "Failed to save or update AzCli tool result for agent task {AgentTaskId}", agentTaskId);
        }
    }

    /// <summary>
    /// Handles pending AzCli execution for agent tasks
    /// </summary>
    public async Task HandlePendingAzCliAsync(Guid threadId, AzCliExecution execution, Guid agentTaskId, InvestigationStepContext? stepContext)
    {
        await SaveOrUpdateAzCliToolResultAsync(agentTaskId, stepContext, execution, threadId);
        await SendAgentTaskUpdateWithAzCliStatusAsync(threadId, execution, agentTaskId);
        
        _logger.LogInternalInformation("AzCli {Status} - stored in agent task and sent approval request stream", execution.Status);
    }

    /// <summary>
    /// Handles running AzCli execution for agent tasks
    /// </summary>
    public async Task HandleRunningAzCliAsync(Guid threadId, AzCliExecution execution, Guid agentTaskId, InvestigationStepContext? stepContext)
    {
        await SaveOrUpdateAzCliToolResultAsync(agentTaskId, stepContext, execution, threadId);
        await SendAgentTaskUpdateWithAzCliStatusAsync(threadId, execution, agentTaskId);
        
        _logger.LogInternalInformation("AzCli Running - updated agent task and sent task update");
    }

    /// <summary>
    /// Handles completed AzCli execution for agent tasks
    /// </summary>
    public async Task HandleCompletedAzCliAsync(Guid threadId, AzCliExecution execution, Guid agentTaskId, InvestigationStepContext? stepContext)
    {
        await SaveOrUpdateAzCliToolResultAsync(agentTaskId, stepContext, execution, threadId);
        
        // Add reasoning message for agent context
        var azCliMessage = new ChatMessage(ChatRole.Tool, $"Command: {execution.Command}\nOutput: {execution.Output ?? execution.Error}");
        await AddToolResultToAgentChatHistoryAsync(threadId, azCliMessage);
        
        // Send task update to agent task panel
        await SendAgentTaskUpdateWithAzCliStatusAsync(threadId, execution, agentTaskId);
        
        _logger.LogInternalInformation("AzCli {Status} - stored in agent task and sent task update", execution.Status);
    }

    /// <summary>
    /// Sends agent task update with AzCli status
    /// </summary>
    private async Task SendAgentTaskUpdateWithAzCliStatusAsync(Guid threadId, AzCliExecution execution, Guid agentTaskId)
    {
        try
        {
            // Get the current agent task to send full update
            var agentTask = await _agentTaskRepository.GetAgentTaskAsync(threadId, agentTaskId);
            if (agentTask == null)
            {
                _logger.LogInternalWarning("Could not find agent task {AgentTaskId} for AzCli status update", agentTaskId);
                return;
            }

            // Set task status based on AzCli execution status
            var originalStatus = agentTask.Status;
            var newStatus = execution.Status switch
            {
                AzCliExecutionStatus.Pending or AzCliExecutionStatus.PendingAuthorization => AgentTaskStatus.PendingUserApproval,
                AzCliExecutionStatus.Running => AgentTaskStatus.InProgress,
                AzCliExecutionStatus.Completed => originalStatus, // Don't change overall task status for individual completions
                AzCliExecutionStatus.Failed => originalStatus,
                AzCliExecutionStatus.Cancelled => originalStatus,
                _ => originalStatus
            };
            
            _logger.LogInternalInformation("Agent task status mapping: AzCli {AzCliStatus} -> Agent Task {OriginalStatus} -> {NewStatus}", 
                execution.Status, originalStatus, newStatus);
            
            agentTask.Status = newStatus;

            // Save the updated agent task to the database
            await _agentTaskRepository.UpdateAgentTaskAsync(agentTask);

            // Use the standard task update mechanism (sends whole task)
            var taskJson = JsonSerializer.Serialize(agentTask, JsonSerializerOptions.Web);
            await _streamingService.StreamTaskUpdateAsync(threadId, taskJson);
            
            _logger.LogInternalInformation("Sent full agent task update for AzCli {Status} on task {AgentTaskId}", execution.Status, agentTaskId);
        }
        catch (Exception ex)
        {
            _logger.LogInternalError(ex, "Failed to send agent task update for AzCli {Status} on task {AgentTaskId}", execution.Status, agentTaskId);
        }
    }

    #endregion
}
