script:
  prompt: "Create a read-only role for pods bound to my reader-sa service account in the create-simple-rbac namespace in aks cluster {{.aksClusterName}}."
setup: "setup.sh"
setupWindows: "setup.ps1"
verifier: "verify.sh"
verifierWindows: "verify.ps1"
cleanup: "cleanup.sh"
cleanupWindows: "cleanup.ps1"
disabled: true
