# ==============================================================================
# Deploy Extension to EV2
# ==============================================================================
# This script deploys an agent extension using EV2 rollout infrastructure.
# It validates artifacts, registers them with EV2, and creates a rollout.
#
# Generated by srectl extension generate-ev2
# ==============================================================================

param(
    [Parameter(Mandatory = $true)]
    [string]$ArtifactsDirectory,

    [Parameter(Mandatory = $true)]
    [string]$Location,

    [Parameter(Mandatory = $false)]
    [switch]$SkipValidation,

    [Parameter(Mandatory = $false)]
    [switch]$SkipRollout
)

$ErrorActionPreference = "Stop"
$PSNativeCommandUseErrorActionPreference = $true
Set-StrictMode -Version 3.0

# EV2 Stage Map Configuration
$STAGE_MAP_NAME = "Microsoft.Azure.SDP.Standard"
$STAGE_MAP_VERSION = "0.0.11"

# ==============================================================================
# Helper Functions
# ==============================================================================

function Write-Info { param([string]$Message); Write-Host "[INFO] $Message" -ForegroundColor Green }
function Write-Error-Message { param([string]$Message); Write-Host "[ERROR] $Message" -ForegroundColor Red }
function Write-Warning-Message { param([string]$Message); Write-Host "[WARN] $Message" -ForegroundColor Yellow }

function Test-Prerequisites {
    Write-Info "Checking prerequisites..."

    # Check if EV2 PowerShell module is loaded
    if (-not (Get-Module -Name "Microsoft.Azure.Deployment.Express.CmdLet")) {
        Write-Info "EV2 module not loaded. Attempting to load..."

        # Try to load from AzureServiceDeployClient.ps1 (common in deployment directories)
        $AzureServiceDeployClientPath = ".\AzureServiceDeployClient.ps1"
        if (Test-Path $AzureServiceDeployClientPath) {
            Write-Info "Loading EV2 module from $AzureServiceDeployClientPath"
            try {
                . $AzureServiceDeployClientPath
                Write-Info "EV2 module loaded successfully"
            }
            catch {
                Write-Error-Message "Failed to load EV2 module from $AzureServiceDeployClientPath : $_"
                throw "Failed to load EV2 module"
            }
        }
        else {
            # Try standard Import-Module
            try {
                Import-Module Microsoft.Azure.Deployment.Express.CmdLet -ErrorAction Stop
                Write-Info "EV2 module loaded successfully"
            }
            catch {
                Write-Error-Message "EV2 PowerShell module is not available"
                Write-Info ""
                Write-Info "To install EV2 module, you have several options:"
                Write-Info "  1. Copy AzureServiceDeployClient.ps1 to the current directory"
                Write-Info "  2. Run: Import-Module Microsoft.Azure.Deployment.Express.CmdLet"
                Write-Info "  3. Install from your organization's package repository"
                Write-Info ""
                Write-Info "For more info: https://ev2docs.azure.net/getting-started/install.html"
                throw "Missing EV2 module"
            }
        }
    }
    else {
        Write-Info "EV2 module is already loaded"
    }

    # Check if az CLI is installed
    if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
        Write-Error-Message "Azure CLI is not installed"
        throw "Azure CLI is required"
    }

    Write-Info "All prerequisites are met"
}

function Test-ArtifactsExist {
    param([string]$Directory)
    $requiredFiles = @("configurationSettings.jsonc", "RolloutSpec.json", "ScopeBindings.json", "ServiceModel.json", "version.txt")
    foreach ($file in $requiredFiles) {
        $filePath = Join-Path $Directory $file
        if (-not (Test-Path $filePath)) {
            Write-Error-Message "Required file not found: $file"
            throw "Missing artifact: $file"
        }
    }
    Write-Info "All required Ev2 artifact files found"
}

function Get-ConfigurationSettings {
    param([string]$Directory)
    $configPath = Join-Path $Directory "configurationSettings.jsonc"
    
    if (-not (Test-Path $configPath)) {
        Write-Error-Message "configurationSettings.jsonc not found"
        throw "Missing configuration file"
    }
    
    try {
        # Remove JSONC comments and parse
        $configContent = Get-Content -Raw -Path $configPath
        $configContent = $configContent -replace '//.*$', '' -replace '/\*[\s\S]*?\*/', ''
        $configJson = $configContent | ConvertFrom-Json
        
        if (-not $configJson.Settings) {
            Write-Error-Message "Settings section not found in configurationSettings.jsonc"
            throw "Invalid configuration file"
        }
        
        if (-not $configJson.Settings.environment) {
            Write-Error-Message "environment field not found in configurationSettings.jsonc"
            throw "Missing required configuration: environment"
        }
        
        if (-not $configJson.Settings.subscriptionKey) {
            Write-Error-Message "subscriptionKey field not found in configurationSettings.jsonc"
            throw "Missing required configuration: subscriptionKey"
        }
        
        if (-not $configJson.Settings.subscriptionId) {
            Write-Error-Message "subscriptionId field not found in configurationSettings.jsonc"
            throw "Missing required configuration: subscriptionId"
        }
        
        if (-not $configJson.Settings.resourceGroup) {
            Write-Error-Message "resourceGroup field not found in configurationSettings.jsonc"
            throw "Missing required configuration: resourceGroup"
        }
        
        return $configJson.Settings
    }
    catch {
        Write-Error-Message "Failed to parse configurationSettings.jsonc: $_"
        throw
    }
}

function Get-ServiceMetadata {
    param([string]$Directory)
    $serviceModelPath = Join-Path $Directory "serviceModel.json"
    $serviceModelJson = Get-Content -Raw -Path $serviceModelPath | ConvertFrom-Json
    
    return @{
        ServiceId    = $serviceModelJson.serviceMetadata.serviceIdentifier
        ServiceGroup = $serviceModelJson.serviceMetadata.serviceGroup
    }
}

function Get-ArtifactVersion {
    param([string]$Directory)
    $versionPath = Join-Path $Directory "version"
    if (Test-Path $versionPath) { return (Get-Content -Raw -Path $versionPath).Trim() }
    return "1.0.0"
}

function Register-ServiceGroup {
    param(
        [string]$ServiceId,
        [string]$ServiceGroup,
        [string]$Directory,
        [string]$RolloutInfra
    )
    Write-Info "Checking if service group '$ServiceGroup' is registered"
    
    try {
        $serviceGroupRegistration = Get-AzureServiceRolloutServiceGroupRegistration -ServiceIdentifier $ServiceId -ServiceGroup $ServiceGroup -RolloutInfra $RolloutInfra -ErrorAction SilentlyContinue
        
        if (-not $serviceGroupRegistration -or $serviceGroupRegistration -match "ServiceGroupIsNotRegistered") {
            Write-Warning-Message "Service group '$ServiceGroup' is not registered"
            Write-Info "Registering service group..."
            
            $serviceGroupSpecPath = Join-Path $Directory "serviceGroupSpecification.json"
            New-AzureServiceRolloutServiceGroupRegistration -ServiceIdentifier $ServiceId -ServiceGroupSpecificationPath $serviceGroupSpecPath -RolloutInfra $RolloutInfra -ErrorAction Stop | Out-Null
            Write-Info "Service group '$ServiceGroup' registered successfully!"
        }
        else {
            Write-Info "Service group '$ServiceGroup' is already registered"
        }
    }
    catch {
        Write-Error-Message "Failed to register service group: $_"
        throw
    }
}

function Register-SubscriptionKey {
    param(
        [string]$ServiceId,
        [string]$ServiceGroup,
        [string]$RolloutInfra,
        [string]$SubscriptionKey,
        [string]$SubscriptionId
    )
    Write-Info "Checking subscription key: $SubscriptionKey"
    
    try {
        $azureSubscription = Get-AzureServiceSubscription -ServiceIdentifier $ServiceId -ServiceGroup $ServiceGroup -SubscriptionKey $SubscriptionKey -RolloutInfra $RolloutInfra -ErrorAction SilentlyContinue
        if ($azureSubscription) {
            Write-Info "Subscription key '$SubscriptionKey' is already registered"
        }
        else {
            Write-Warning-Message "Subscription key '$SubscriptionKey' is not registered"
            Write-Info "Auto-registering subscription key..."
            Register-AzureServiceSubscription -ServiceIdentifier $ServiceId -ServiceGroup $ServiceGroup -SubscriptionKey $SubscriptionKey -SubscriptionId $SubscriptionId -RolloutInfra $RolloutInfra -ErrorAction Stop
            Write-Info "Subscription key '$SubscriptionKey' registered successfully!"
        }
    }
    catch {
        Write-Error-Message "Failed to register subscription key: $_"
        throw
    }
}

# ==============================================================================
# Main Script
# ==============================================================================

Write-Info "Starting EV2 deployment for agent extension"

$ArtifactsDirectory = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($ArtifactsDirectory)
Write-Info "Artifacts Directory: $ArtifactsDirectory"

Test-Prerequisites
Test-ArtifactsExist -Directory $ArtifactsDirectory

$configSettings = Get-ConfigurationSettings -Directory $ArtifactsDirectory
$environment = $configSettings.environment

$subscriptionKey = $configSettings.subscriptionKey
$subscriptionId = $configSettings.subscriptionId
$resourceGroup = $configSettings.resourceGroup

$metadata = Get-ServiceMetadata -Directory $ArtifactsDirectory
$serviceId = $metadata.ServiceId
$serviceGroup = $metadata.ServiceGroup

Write-Info "Environment: $environment"
Write-Info "Service ID: $serviceId"
Write-Info "Service Group: $serviceGroup"
Write-Info "Subscription Key: $subscriptionKey"
Write-Info "Subscription ID: $subscriptionId"
Write-Info "Resource Group: $resourceGroup"

$version = Get-ArtifactVersion -Directory $ArtifactsDirectory
Write-Info "Artifact Version: $version"

Register-ServiceGroup -ServiceId $serviceId -ServiceGroup $serviceGroup -Directory $ArtifactsDirectory -RolloutInfra $environment
Register-SubscriptionKey -ServiceId $serviceId -ServiceGroup $serviceGroup -RolloutInfra $environment -SubscriptionKey $subscriptionKey -SubscriptionId $subscriptionId

$selector = if ($Location) { "regions($Location)" } else { "regions(*)" }
Write-Info "Selector: $selector"

if (-not $SkipValidation) {
    Write-Info "Validating EV2 artifacts..."
    try {
        Test-AzureServiceArtifacts -ServiceGroupRoot $ArtifactsDirectory -RolloutSpec (Join-Path $ArtifactsDirectory "rolloutSpec.json") -RolloutInfra $environment -Select $selector -ErrorAction Stop | Out-Null
        Write-Info "Artifact validation successful"
    }
    catch { Write-Error-Message "Artifact validation failed: $_"; throw }
}
else { Write-Warning-Message "Skipping artifact validation" }

if (-not $SkipRollout) {
    Write-Info "Registering artifacts with EV2..."
    try {
        Register-AzureServiceArtifacts -ServiceGroupRoot $ArtifactsDirectory -RolloutSpec (Join-Path $ArtifactsDirectory "rolloutSpec.json") -RolloutInfra $environment -Force -ErrorAction Stop | Out-Null
        Write-Info "Artifacts registered successfully"
    }
    catch { Write-Error-Message "Artifact registration failed: $_"; throw }

    Write-Info "Creating EV2 rollout..."
    try {
        New-AzureServiceRollout -ServiceIdentifier $serviceId -ServiceGroup $serviceGroup -StageMapName $STAGE_MAP_NAME -StageMapVersion $STAGE_MAP_VERSION -Select $selector -ArtifactsVersion $version -RolloutInfra $environment -ErrorAction Stop
        Write-Info "Rollout created successfully!"
    }
    catch { Write-Error-Message "Rollout creation failed: $_"; throw }
}
else { Write-Warning-Message "Skipping artifact registration and rollout creation" }

Write-Info ""
Write-Info "Deployment process completed successfully!"
Write-Info ""
Write-Info "Next steps:"
Write-Info "  1. Monitor the rollout progress in EV2 portal"
Write-Info "  2. Verify the extension is deployed correctly"
Write-Info "  3. Test the extension functionality"
