import { makeStyles, tokens } from '@fluentui/react-components';

export const useCreationDialogStyles = makeStyles({
    dialogSurface: {
        maxWidth: '800px',
        width: '90vw',
        minHeight: '600px',
        display: 'flex',
        flexDirection: 'column',
    },
    dialogSurfaceWithTester: {
        maxWidth: '1400px',
        width: '95vw',
        minHeight: '600px',
        display: 'flex',
        flexDirection: 'column',
    },
    dialogBody: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
        paddingTop: '24px',
    },
    dialogBodyWithTester: {
        flex: 1,
        display: 'flex',
        flexDirection: 'row',
        gap: '24px',
        paddingTop: '24px',
    },
    formColumn: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
        overflowY: 'auto',
        maxHeight: '70vh',
        overflowX: 'visible',
        position: 'relative',
    },
    testerColumn: {
        width: '500px',
        display: 'flex',
        flexDirection: 'column',
        borderLeft: `1px solid ${tokens.colorNeutralStroke1}`,
        paddingLeft: '24px',
        overflowY: 'auto',
        maxHeight: '70vh',
        animationName: {
            from: {
                opacity: 0,
                transform: 'translateX(20px)',
            },
            to: {
                opacity: 1,
                transform: 'translateX(0)',
            },
        },
        animationDuration: '0.3s',
        animationTimingFunction: 'ease-out',
    },
    stepIndicator: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalL,
        marginBottom: '32px',
        justifyContent: 'space-between',
        width: '100%',
        maxWidth: '640px',
        marginLeft: 'auto',
        marginRight: 'auto',
    },
    formSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    formRow: {
        display: 'flex',
        gap: '12px',
    },
    formRowItem: {
        flex: 1,
    },
    formGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '16px',
        alignItems: 'start',
        '@media (max-width: 768px)': {
            gridTemplateColumns: '1fr',
        },
    },
    scheduleGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
        gap: tokens.spacingHorizontalL,
        alignItems: 'start',
    },
    scheduleGridFull: {
        gridColumn: '1 / -1',
    },
    compactField: {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
        width: '100%',
        minHeight: 'fit-content',
    },
    paramStatusRow: {
        display: 'flex',
        gap: tokens.spacingHorizontalM,
        marginTop: '4px',
        alignItems: 'center',
        flexWrap: 'wrap',
    },
    paramStatusDanger: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalXS,
        color: 'var(--colorStatusDangerForeground1)',
    },
    paramStatusInfo: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalXS,
        color: 'var(--colorStatusInformationForeground1)',
    },
    paramStatusSuccess: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalXS,
        color: 'var(--colorStatusSuccessForeground1)',
    },
    compactTextarea: {
        minHeight: '60px',
        maxHeight: '120px',
        resize: 'vertical',
    },
    helpText: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
        marginTop: '4px',
    },
    metaAgentInfo: {
        marginTop: '4px',
        padding: '4px 8px',
        borderRadius: tokens.borderRadiusSmall,
        backgroundColor: tokens.colorBrandBackground2,
        color: tokens.colorBrandForeground2,
        fontSize: tokens.fontSizeBase200,
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalXS,
    },
    metaAgentInfoIcon: {
        color: tokens.colorBrandForeground2,
        flexShrink: 0,
    },
    typeSelector: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gap: '16px',
        marginTop: '24px',
    },
    typeCard: {
        padding: '24px',
        borderRadius: tokens.borderRadiusMedium,
        border: `2px solid ${tokens.colorNeutralStroke1}`,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '12px',
        backgroundColor: tokens.colorNeutralBackground1,
        cursor: 'pointer',
        ':hover': {
            border: `2px solid ${tokens.colorBrandStroke1}`,
            boxShadow: tokens.shadow4,
        },
    },
    typeCardSelected: {
        border: `2px solid ${tokens.colorBrandStroke1}`,
        backgroundColor: tokens.colorBrandBackground2,
        boxShadow: tokens.shadow8,
    },
    typeIcon: {
        fontSize: '48px',
        color: tokens.colorBrandForeground1,
    },
    typeTitle: {
        fontSize: tokens.fontSizeBase400,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground1,
    },
    typeDescription: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
    },
    typeCardActions: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        width: '100%',
        marginTop: tokens.spacingVerticalS,
    },
    triggerStats: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '4px',
        color: tokens.colorNeutralForeground3,
        fontSize: tokens.fontSizeBase200,
        textAlign: 'center',
        width: '100%',
    },
    sectionHeader: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalXS,
    },
    sectionTitle: {
        fontSize: tokens.fontSizeBase400,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground1,
    },
    sectionDescription: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
        maxWidth: '560px',
    },
    triggerDetailsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
        gap: '16px',
        width: '100%',
    },
    triggerDetailsCard: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        textAlign: 'left',
        gap: tokens.spacingVerticalXS,
        padding: '20px',
        borderRadius: tokens.borderRadiusMedium,
        border: `2px solid ${tokens.colorNeutralStroke1}`,
        backgroundColor: tokens.colorNeutralBackground1,
        cursor: 'pointer',
        transition: 'border 0.2s ease, box-shadow 0.2s ease',
        ':hover': {
            border: `2px solid ${tokens.colorBrandStroke1}`,
            boxShadow: tokens.shadow8,
        },
    },
    triggerDetailsCardDisabled: {
        opacity: 0.5,
        cursor: 'not-allowed',
    },
    triggerCardHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalS,
        width: '100%',
    },
    triggerOptionIcon: {
        fontSize: '32px',
        color: tokens.colorBrandForeground1,
    },
    triggerOptionTitle: {
        fontSize: tokens.fontSizeBase300,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground1,
    },
    triggerOptionDescription: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
    },
    triggerOptionStat: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
    },
    triggerOptionFooter: {
        marginTop: tokens.spacingVerticalS,
        width: '100%',
        display: 'flex',
        justifyContent: 'flex-start',
    },
    triggerLayout: {
        display: 'flex',
        flexDirection: 'row',
        gap: '32px',
        alignItems: 'flex-start',
        width: '100%',
        flexWrap: 'wrap',
    },
    triggerMainColumn: {
        flex: 3,
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
        minWidth: 'min(640px, 100%)',
    },
    triggerSidePanel: {
        flex: 2,
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        minWidth: '280px',
    },
    triggerFormCard: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
        padding: '24px',
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke1}`,
        backgroundColor: tokens.colorNeutralBackground1,
        boxShadow: tokens.shadow8,
    },
    triggerHelperCard: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        padding: '20px',
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke1}`,
        backgroundColor: tokens.colorNeutralBackground2,
    },
    triggerHelperHeading: {
        fontSize: tokens.fontSizeBase300,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground1,
    },
    triggerHelperChipGroup: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '12px',
    },
    triggerHelperChip: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalS,
        padding: '8px 12px',
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke1}`,
        backgroundColor: tokens.colorNeutralBackground1,
        minWidth: '180px',
    },
    triggerHelperChipIcon: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: tokens.colorBrandForeground1,
        fontSize: '20px',
    },
    triggerHelperChipLabel: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
    },
    triggerHelperChipValue: {
        fontSize: tokens.fontSizeBase300,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground1,
    },
    triggerHelperList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    triggerHelperListItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '8px 12px',
        borderRadius: tokens.borderRadiusSmall,
        backgroundColor: tokens.colorNeutralBackground1,
    },
    triggerHelperEmpty: {
        color: tokens.colorNeutralForeground3,
    },
    toolReviewCard: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        padding: '24px',
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke1}`,
        backgroundColor: tokens.colorNeutralBackground1,
        boxShadow: tokens.shadow8,
    },
    toolReviewHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: tokens.spacingHorizontalS,
    },
    toolReviewGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
        gap: '16px',
    },
    toolReviewItem: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    toolReviewItemLabel: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
    },
    toolReviewItemValue: {
        fontSize: tokens.fontSizeBase300,
        color: tokens.colorNeutralForeground1,
    },
    toolReviewParameters: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    toolReviewParameterList: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '12px',
    },
    toolReviewParameterCard: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        padding: '16px',
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        backgroundColor: tokens.colorNeutralBackground2,
        minWidth: '220px',
    },
    toolReviewParameterHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: tokens.spacingHorizontalS,
    },
    toolReviewParameterMeta: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '8px',
    },
    triggerReviewBody: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
    },
    triggerReviewStats: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalXS,
        color: tokens.colorNeutralForeground3,
    },
    triggerReviewLabel: {
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground1,
    },
    previewSection: {
        padding: '16px',
        backgroundColor: tokens.colorNeutralBackground2,
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke1}`,
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
    },
    previewHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: tokens.spacingHorizontalXS,
        marginBottom: tokens.spacingVerticalS,
    },
    previewTitle: {
        fontSize: tokens.fontSizeBase300,
        fontWeight: tokens.fontWeightSemibold,
        marginBottom: 0,
        color: tokens.colorNeutralForeground1,
    },
    previewCopyButton: {
        flexShrink: 0,
    },
    previewContent: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground2,
        fontFamily: tokens.fontFamilyMonospace,
        whiteSpace: 'pre-wrap',
        padding: tokens.spacingHorizontalS,
        backgroundColor: tokens.colorNeutralBackground1,
        borderRadius: tokens.borderRadiusSmall,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
    },
    previewEditorContainer: {
        width: '100%',
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        overflow: 'hidden',
        backgroundColor: tokens.colorNeutralBackground1,
        boxShadow: tokens.shadow4,
    },
    previewEditor: {
        width: '100%',
        height: '100%',
    },
    progressSection: {
        marginBottom: '16px',
    },
    quickCreateHeader: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalXS,
    },
    quickCreateDescription: {
        color: tokens.colorNeutralForeground3,
        fontSize: tokens.fontSizeBase200,
        maxWidth: '560px',
    },
    quickCreateHint: {
        color: tokens.colorNeutralForeground3,
        fontSize: tokens.fontSizeBase200,
    },
    contextBanner: {
        position: 'sticky',
        top: 0,
        zIndex: 2,
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalXS,
        padding: '12px 16px',
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke1}`,
        backgroundColor: tokens.colorNeutralBackground1,
        boxShadow: tokens.shadow2,
    },
    contextBannerTitle: {
        fontSize: tokens.fontSizeBase300,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground1,
    },
    contextBannerSubtext: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
    },
    relationshipSummaryContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalXS,
        padding: '12px 16px',
        borderRadius: tokens.borderRadiusMedium,
        border: `1px dashed ${tokens.colorNeutralStroke2}`,
        backgroundColor: tokens.colorNeutralBackground2,
    },
    relationshipSummaryChip: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalXS,
        padding: '6px 12px',
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        backgroundColor: tokens.colorNeutralBackground1,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground1,
    },
    relationshipSummarySection: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalXS,
        padding: '12px 16px',
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        backgroundColor: tokens.colorNeutralBackground2,
    },
    relationshipSummaryTitle: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
        textTransform: 'uppercase',
        letterSpacing: '0.04em',
    },
    inlineError: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorPaletteRedForeground2,
        marginTop: tokens.spacingVerticalXXS,
    },
    segmentedHint: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
        marginTop: tokens.spacingVerticalXXS,
    },
    badgeRow: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalXS,
    },
    pillsRow: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: tokens.spacingHorizontalXS,
        alignItems: 'center',
    },
    pill: {
        display: 'inline-flex',
        alignItems: 'center',
        padding: '4px 8px',
        borderRadius: tokens.borderRadiusSmall,
        backgroundColor: tokens.colorNeutralBackground3,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground1,
    },
    sectionCard: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
        padding: '16px',
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke1}`,
        backgroundColor: tokens.colorNeutralBackground1,
        cursor: 'pointer',
        ':hover': {
            border: `1px solid ${tokens.colorBrandStroke1}`,
            boxShadow: tokens.shadow4,
        },
    },
    scheduleSummaryCard: {
        padding: '12px',
        gap: tokens.spacingVerticalXS,
    },
    cardSubtitle: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
    },
    triggerInfoLead: {
        fontSize: tokens.fontSizeBase300,
        color: tokens.colorNeutralForeground1,
        fontWeight: tokens.fontWeightSemibold,
        marginBottom: tokens.spacingVerticalS,
    },
    segmentedRow: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
    },
    agentOptionRow: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: tokens.spacingHorizontalS,
        padding: '8px 12px',
        borderRadius: tokens.borderRadiusSmall,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        backgroundColor: tokens.colorNeutralBackground2,
    },
    agentOptionBadges: {
        display: 'flex',
        gap: tokens.spacingHorizontalXS,
        alignItems: 'center',
    },
    agentOptionWarning: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorPaletteRedForeground1,
        fontWeight: tokens.fontWeightSemibold,
    },
    templateChips: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: tokens.spacingHorizontalS,
    },
    chipsRow: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: tokens.spacingHorizontalXS,
        alignItems: 'center',
    },
    advancedSection: {
        marginTop: tokens.spacingVerticalL,
    },
    indicatorBadge: {
        fontSize: tokens.fontSizeBase200,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorBrandForeground1,
    },

    // Tester Panel Styles
    testerPanel: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        height: '100%',
        padding: '8px',
        overflow: 'visible',
    },
    testerHeader: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        marginBottom: '8px',
    },
    testerParametersSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
        marginTop: tokens.spacingVerticalM,
        marginBottom: tokens.spacingVerticalM,
    },
    testerParametersList: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
        marginTop: tokens.spacingVerticalXS,
    },
    testerParameterWarning: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorPaletteRedForeground1,
        marginTop: tokens.spacingVerticalXXS,
    },
    testerButton: {
        alignSelf: 'flex-start',
        minWidth: '120px',
        whiteSpace: 'nowrap',
        fontSize: tokens.fontSizeBase300,
        padding: '8px 16px',
    },
    testerResults: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    testerResultsHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    testerResultsTable: {
        overflowX: 'auto',
        border: `1px solid ${tokens.colorNeutralStroke1}`,
        borderRadius: tokens.borderRadiusMedium,
        maxHeight: '400px',
        overflowY: 'auto',
    },
    testerTable: {
        width: '100%',
        borderCollapse: 'collapse',
        fontSize: tokens.fontSizeBase200,
    },
    testerTableHead: {
        backgroundColor: tokens.colorNeutralBackground2,
        position: 'sticky',
        top: 0,
    },
    testerTableHeader: {
        padding: '8px',
        textAlign: 'left',
        borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
        fontWeight: tokens.fontWeightSemibold,
    },
    testerTableCell: {
        padding: '8px',
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    },

    // World-Class Trigger Card Styles
    triggerCardContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        padding: '20px',
        borderRadius: tokens.borderRadiusLarge,
        border: `2px solid ${tokens.colorNeutralStroke1}`,
        backgroundColor: tokens.colorNeutralBackground1,
        position: 'relative',
        overflow: 'hidden',
        transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
        ':hover': {
            transform: 'translateY(-2px)',
            boxShadow: `0 8px 32px ${tokens.colorNeutralShadowAmbient}`,
        },
        ':focus-within': {
            boxShadow: `0 0 0 2px ${tokens.colorBrandStroke2}`,
        },
    },

    triggerStatusBadge: {
        position: 'absolute',
        top: '12px',
        right: '12px',
        fontSize: tokens.fontSizeBase200,
        fontWeight: tokens.fontWeightMedium,
        zIndex: 1,
    },

    triggerNewCardHeader: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '12px',
        marginTop: '8px',
    },

    triggerCardIconTitle: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '16px',
        width: '100%',
    },

    triggerCardTitleSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
        flex: 1,
    },

    triggerTypeSelection: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '16px',
        marginTop: '8px',
    },

    triggerTypeCard: {
        display: 'flex',
        flexDirection: 'column',
        padding: '16px',
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        backgroundColor: tokens.colorNeutralBackground2,
        cursor: 'pointer',
        transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
        position: 'relative',
        overflow: 'hidden',
        ':hover': {
            backgroundColor: tokens.colorNeutralBackground1Hover,
            transform: 'translateY(-1px)',
            boxShadow: `0 4px 16px ${tokens.colorNeutralShadowAmbient}`,
        },
        ':active': {
            transform: 'translateY(0)',
            boxShadow: `0 2px 8px ${tokens.colorNeutralShadowAmbient}`,
        },
        ':focus': {
            outline: 'none',
            boxShadow: `0 0 0 2px ${tokens.colorBrandStroke2}`,
        },
    },

    triggerTypeCardDisabled: {
        cursor: 'not-allowed',
        opacity: 0.6,
        ':hover': {
            transform: 'none',
            backgroundColor: tokens.colorNeutralBackground2,
            boxShadow: 'none',
        },
    },

    triggerTypeContent: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '12px',
        marginBottom: '12px',
        flex: 1,
    },

    triggerTypeIconContainer: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '32px',
        height: '32px',
        borderRadius: tokens.borderRadiusSmall,
        backgroundColor: tokens.colorBrandBackground2,
        flexShrink: 0,
    },

    triggerTypeIcon: {
        fontSize: '20px',
        color: tokens.colorBrandForeground1,
        flexShrink: 0,
    },

    triggerTypeText: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
        flex: 1,
    },

    triggerTypeTitle: {
        fontSize: tokens.fontSizeBase300,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground1,
        lineHeight: tokens.lineHeightBase300,
    },

    triggerTypeDescription: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
        lineHeight: tokens.lineHeightBase200,
    },

    triggerTypeFooter: {
        display: 'flex',
        justifyContent: 'flex-end',
        alignItems: 'center',
        marginTop: 'auto',
    },

    triggerQuickActions: {
        display: 'flex',
        gap: '8px',
        paddingTop: '16px',
        borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
        justifyContent: 'center',
    },

    triggerQuickAction: {
        fontSize: tokens.fontSizeBase200,
        padding: '6px 12px',
        borderRadius: tokens.borderRadiusSmall,
        transition: 'all 0.2s ease',
        ':hover': {
            backgroundColor: tokens.colorNeutralBackground1Hover,
        },
    },

    promptImprovementContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    promptImprovementActions: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        alignSelf: 'flex-end',
    },
    promptImprovementButton: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        fontSize: tokens.fontSizeBase200,
    },
    promptImprovementInline: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        padding: '12px',
        borderRadius: tokens.borderRadiusMedium,
        backgroundColor: tokens.colorNeutralBackground2,
        border: `1px solid ${tokens.colorNeutralStroke1}`,
    },
    promptImprovementInlineGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    promptImprovementDialog: {
        maxWidth: '700px',
        width: '90vw',
    },
    promptImprovementContent: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        maxHeight: '60vh',
        overflowY: 'auto',
    },
    promptImprovementSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    promptImprovementSectionTitle: {
        fontSize: tokens.fontSizeBase300,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground1,
    },
    promptImprovementList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        padding: '12px',
        borderRadius: tokens.borderRadiusMedium,
        backgroundColor: tokens.colorNeutralBackground2,
        border: `1px solid ${tokens.colorNeutralStroke1}`,
    },
    promptImprovementItem: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground1,
        lineHeight: tokens.lineHeightBase200,
    },
    promptImprovementEmpty: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
        fontStyle: 'italic',
    },
    promptPreview: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        padding: '12px',
        borderRadius: tokens.borderRadiusMedium,
        backgroundColor: tokens.colorNeutralBackground2,
        border: `1px solid ${tokens.colorNeutralStroke1}`,
        fontFamily: tokens.fontFamilyMonospace,
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground1,
        whiteSpace: 'pre-wrap',
        maxHeight: '200px',
        overflowY: 'auto',
    },
    promptImprovementDialogActions: {
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '8px',
        paddingTop: '16px',
        borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    },

    wideInstructionsField: {
        width: '100%',
        '& textarea': {
            minHeight: '140px',
            fontSize: tokens.fontSizeBase300,
            lineHeight: tokens.lineHeightBase400,
            padding: '16px 20px',
            borderRadius: tokens.borderRadiusMedium,
            backgroundColor: tokens.colorNeutralBackground1,
        },
        '& .fui-Field__label': {
            fontSize: tokens.fontSizeBase400,
            fontWeight: tokens.fontWeightSemibold,
            marginBottom: tokens.spacingVerticalS,
        },
    },

    warningMessage: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalXS,
        marginTop: tokens.spacingVerticalXXS,
        minHeight: '20px',
        color: tokens.colorPaletteRedForeground1,
    },

    warningIcon: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorPaletteRedForeground1,
        flexShrink: 0,
    },

    alignmentSpacer: {
        minHeight: '20px',
        marginTop: tokens.spacingVerticalXXS,
    },

    yamlEditor: {
        fontFamily: tokens.fontFamilyMonospace,
        fontSize: tokens.fontSizeBase200,
        minHeight: '400px',
        maxHeight: 'none',
        height: 'auto',
        width: '100%',
        resize: 'vertical',
        padding: '12px',
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke1}`,
        backgroundColor: tokens.colorNeutralBackground1,
        color: tokens.colorNeutralForeground1,
        whiteSpace: 'pre',
        overflowWrap: 'normal',
        overflowX: 'auto',
        overflowY: 'auto',
        lineHeight: '1.4',
        boxSizing: 'border-box',
        ':focus-within': {
            outline: `2px solid ${tokens.colorBrandStroke1}`,
            outlineOffset: '1px',
        },
    },

    reviewContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },

    reviewCard: {
        backgroundColor: tokens.colorNeutralBackground1,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRadius: tokens.borderRadiusMedium,
        padding: '16px',
    },

    reviewCardHeader: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '12px',
        width: '100%',
    },

    reviewCardIcon: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '24px',
        height: '24px',
        color: tokens.colorBrandForeground1,
    },

    reviewCardSubtitle: {
        color: tokens.colorNeutralForeground2,
        marginTop: '4px',
    },

    reviewCardDetail: {
        color: tokens.colorNeutralForeground3,
        marginTop: '4px',
        fontStyle: 'italic',
    },

    reviewDetails: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        marginTop: '12px',
    },

    reviewDetailRow: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '8px',
    },

    reviewDetailLabel: {
        fontWeight: tokens.fontWeightSemibold,
        minWidth: '80px',
        color: tokens.colorNeutralForeground2,
    },

    reviewDetailHint: {
        color: tokens.colorNeutralForeground3,
        fontStyle: 'italic',
    },

    reviewInstructions: {
        whiteSpace: 'pre-wrap',
        wordBreak: 'break-word',
        backgroundColor: tokens.colorNeutralBackground3,
        padding: '8px 12px',
        borderRadius: tokens.borderRadiusSmall,
        fontSize: tokens.fontSizeBase200,
        flex: 1,
    },

    reviewActions: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: '24px',
        paddingTop: '16px',
        borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    },
});
