let _startTime = datetime("##startTime##");
let _endTime = datetime("##endTime##");
let _siteName = "##siteName##";
let _eventPrimaryStampName = "##eventPrimaryStampName##";
let _functionName = "##functionName##";
let _filteredEvents = dynamic(["FunctionStarted", "FunctionCompleted"]);
FunctionsLogs
| where PreciseTimeStamp between (_startTime .. _endTime)
| where AppName =~ _siteName
| where EventStampName == _eventPrimaryStampName
| where FunctionName == _functionName
| where Summary startswith "Trigger Details: PartionId"
| parse Summary with 'Trigger Details: Parti' *': ' PartitionId:string ', Offset: ' Offset:string ', EnqueueTimeUtc: ' EnqueueTimeRange:string', SequenceNumber:' SequenceNumber:string ', Count: ' MessageCount:int
| extend EnqueueTimeStart = todatetime(substring(EnqueueTimeRange, 0, 28)), EnqueueTimeEnd = todatetime(substring(EnqueueTimeRange, 29))
| extend Delay = datetime_diff("Second", PreciseTimeStamp, make_datetime(EnqueueTimeStart))
| project PreciseTimeStamp, RoleInstance, AppName, FunctionName, PartitionId, EnqueueTimeStart, EnqueueTimeEnd,Delay, Offset, SequenceNumber, MessageCount,FunctionInvocationId, Summary,EventName,Source
| project PreciseTimeStamp,Delay
| summarize percentiles(Delay, 5, 50, 90, 95,99) 
