let _startTime = datetime("##startTime##");
let _endTime = datetime("##endTime##");
let _siteName = "##siteName##";
let _eventPrimaryStampName = "##eventPrimaryStampName##";
let _functionName = "##functionName##";
let _filteredEvents = dynamic(["FunctionStarted", "FunctionCompleted"]);
FunctionsLogs
| where PreciseTimeStamp between (_startTime .. _endTime)
| where AppName =~ _siteName
| where EventStampName == _eventPrimaryStampName
| where FunctionName == _functionName
| where Summary startswith "Trigger Details: PartionId"
| parse Summary with 'Trigger Details: Parti' *': ' PartitionId:string ', Offset: ' Offset:string ', EnqueueTimeUtc: ' EnqueueTimeRange:string', SequenceNumber:' SequenceNumber:string ', Count: ' MessageCount:int
| distinct PartitionId
| summarize PartitionCount = count()
