let _startTime = datetime("##startTime##");
let _endTime = datetime("##endTime##");
let _siteName = "##siteName##";
let _eventPrimaryStampName = "##eventPrimaryStampName##";
let _functionName = "##functionName##";
let _eventIpAddress = "##eventIpAddress##";
let samplesAggregation = 1ms;
let aggregation = 1s;
FunctionsLogs
| where PreciseTimeStamp between (_startTime .. _endTime)
| where AppName =~ _siteName
| where EventPrimaryStampName == _eventPrimaryStampName
| where FunctionName == _functionName
| where EventName == "FunctionCompleted"
| where EventIpAddress == _eventIpAddress
| extend Duration = toint(extract("Duration=([0-9.]+)", 1, Summary)) 
| mv-expand  samples = range(PreciseTimeStamp - Duration * samplesAggregation, PreciseTimeStamp, samplesAggregation) 
| extend StartTime = PreciseTimeStamp - Duration * samplesAggregation 
| extend StopTime = PreciseTimeStamp 
| project todatetime(samples), StartTime, StopTime, Duration,FunctionInvocationId,FunctionName ,EventIpAddress
| summarize count_FunctionInvocationId=count() by bin(samples, samplesAggregation) ,FunctionName,EventIpAddress
| summarize PeakThroughput = max(count_FunctionInvocationId), MinConurrency = min(count_FunctionInvocationId) by bin(samples, aggregation) ,FunctionName,EventIpAddress
| project PeakTimestamp=todatetime(samples),PeakThroughput
| order by PeakThroughput desc 
| take 1
