let _startTime = datetime("##startTime##");
let _endTime = datetime("##endTime##");
let _siteName = "##siteName##";
let _eventPrimaryStampName = "##eventPrimaryStampName##";
FunctionsLogs
| where PreciseTimeStamp between (_startTime .. _endTime)
| where AppName =~ _siteName
| where EventPrimaryStampName == _eventPrimaryStampName
| where not(Summary startswith "Ping Status" or Summary startswith "[HostMonitor" or Summary startswith "[channel]")
| summarize Count = count() by EventIpAddress
| order by Count desc
| top 1 by Count
