// ------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All rights reserved.
// ------------------------------------------------------------

using FirstPartyAgent.Core.Models;
using FirstPartyAgent.Core.Services;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.Net;
using System.Text.RegularExpressions;

namespace FirstPartyAgent.FunctionApp
{
    public class GitHubTriageAgentController
    {
        private readonly ILogger<GitHubTriageAgentController> _logger;
        private readonly IChatService _chatService;

        public GitHubTriageAgentController(
            ILogger<GitHubTriageAgentController> logger,
            IChatService chatService)
        {
            _logger = logger;
            _chatService = chatService;
        }

        [Function("TriageGithubIssue")]
        public async Task<HttpResponseData> TriageGitHubIssue(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = "TriageGithubIssue")] HttpRequestData req)
        {
            string gitHubIssueBody = await req.ReadAsStringAsync();

            if (string.IsNullOrEmpty(gitHubIssueBody))
            {
                var badResponse = req.CreateResponse(HttpStatusCode.BadRequest);
                await badResponse.WriteAsJsonAsync(new { error = "Invalid request body" });
                return badResponse;
            }

            var gitHubEvent = JsonConvert.DeserializeObject<GitHubIssueEvent>(gitHubIssueBody);

            if (gitHubEvent.Action.Contains("label", StringComparison.OrdinalIgnoreCase))
            {
                // Todo: Auto index the issue to reflect latest state before returning.
                var responseForIgnoringLabelEvents = req.CreateResponse(HttpStatusCode.OK);
                await responseForIgnoringLabelEvents.WriteStringAsync("Ignoring events related to labels.");
                await responseForIgnoringLabelEvents.Body.FlushAsync();
                return responseForIgnoringLabelEvents;
            }

            var initiatedBy = gitHubEvent?.Sender?.Login?.ToString() ?? "unknown";
            if (initiatedBy.Contains("sreagent", StringComparison.OrdinalIgnoreCase) || initiatedBy.Contains("sre-agent", StringComparison.OrdinalIgnoreCase))
            {
                var responseForIgnoringSreAgentEvents = req.CreateResponse(HttpStatusCode.OK);
                await responseForIgnoringSreAgentEvents.WriteStringAsync("Ignoring events initiated by sreagent.");
                await responseForIgnoringSreAgentEvents.Body.FlushAsync();
                return responseForIgnoringSreAgentEvents;
            }

            var requestBody = new MessageRequestBody
            {
                AgentMode = "GithubIssueTagger",
                Message = $"Process the following.\n\nAction taken: {gitHubEvent?.Action}\nIssue URL: {gitHubEvent?.Issue?.Url}",
                Title = gitHubEvent?.Issue?.Number is not null
                    ? $"{gitHubEvent.Repository.Name} - Issue #{gitHubEvent.Issue.Number}"
                    : string.Empty,
                Sender = "TriageGithubIssueFunction",
                SessionId = Guid.NewGuid().ToString(),
            };

            _logger.LogInformation($"Agent Invoked with message - {JsonConvert.SerializeObject(requestBody)}");

            var gitHubDeliveryId = req.Headers.TryGetValues("X-GitHub-Delivery", out var deliveryId) ? deliveryId.FirstOrDefault() : $"AutoGeneratedId:{Guid.NewGuid()}";

            // Start a background thread to run ProcessMessageAsync and detach. Return a 202 Accepted response immediately.
            _ = Task.Run(async () =>
            {
                try
                {
                    _logger.LogInformation($"Processing GitHub issue. DeliveryId: {gitHubDeliveryId} RequestBody: {JsonConvert.SerializeObject(requestBody)}");

                    // Wait for a minute, this allows any existing github automation to complete. e.g. Adding labels to the issue.
                    await Task.Delay(60000);

                    // Process the message using the injected chat service.
                    var chatResponse = await _chatService.ProcessMessageAsync(requestBody);
                    _logger.LogInformation($"GitHub issue processed successfully. DeliveryId: {gitHubDeliveryId} Response: {JsonConvert.SerializeObject(chatResponse)}");
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error processing GitHub issue. DeliveryId: {gitHubDeliveryId} Error: {ex.Message}");
                }
            });

            // Return the processed response.
            var response = req.CreateResponse(HttpStatusCode.Accepted);
            return response;
        }

        [Function("TriageGithubIssueReply")]
        public async Task<HttpResponseData> TriageGithubIssueReply(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = "TriageGithubIssueReply")] HttpRequestData req)
        {
            // Deserialize the request body into your MessageRequestBody model.
            var requestBody = await req.ReadFromJsonAsync<MessageRequestBody>();
            {
                _logger.LogInformation($"Agent Invoked with message - {JsonConvert.SerializeObject(requestBody)}");
            }

            if (requestBody == null || string.IsNullOrEmpty(requestBody.Message))
            {
                var badResponse = req.CreateResponse(HttpStatusCode.BadRequest);
                await badResponse.WriteAsJsonAsync(new { error = "Invalid request body" });
                return badResponse;
            }

            var match = Regex.Match(requestBody.Title ?? string.Empty, @"Issue\s+#(\d+)", RegexOptions.IgnoreCase);
            string issueId = match.Success ? match.Groups[1].Value.Trim() : string.Empty;

            var msgRequestBody = new MessageRequestBody
            {
                AgentMode = "GithubIssueTagger",
                Message = requestBody.Message,
                Sender = requestBody.Sender,
                SessionId = requestBody.SessionId,
                Title = issueId
            };

            // Process the message using the injected chat service.
            var chatResponse = await _chatService.ProcessMessageAsync(msgRequestBody);

            // Return the processed response.
            var response = req.CreateResponse(HttpStatusCode.OK);
            await response.WriteAsJsonAsync(chatResponse);
            return response;
        }
    }
}

