script:
  prompt: "resize the storage volume to 15Gi for the storage-pod in `resize-pv` namespace in aks cluster {{.aksClusterName}}"
setup: "setup.sh"
setupWindows: "setup.ps1"
verifier: "verify.sh"
verifierWindows: "verify.ps1"
cleanup: "cleanup.sh"
cleanupWindows: "cleanup.ps1"
disabled: true
