import { makeStyles, tokens } from '@fluentui/react-components';

export const useTracePanelStyles = makeStyles({
    traceContainer: {
        display: 'flex',
        gridColumnStart: 1,
        gridColumnEnd: 4,
        flexGrow: 1,
        height: '0%',
        '@media (width > 767px)': {
            flexDirection: 'row',
        },
        '@media (width <=  767px)': {
            flexDirection: 'column',
        },
    },
    dialogTitle: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '10px',
        opacity: '1',
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
        flex: 'none',
    },
    dialogBody: {
        gap: '0px',
        '@media (width > 767px)': {
            height: '80vh',
        },
        '@media (width <=  767px)': {
            height: '100vh',
        },
    },
    traceDescription: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: '16px',
        opacity: 1,
        paddingTop: tokens.spacingVerticalS,
        paddingRight: tokens.spacingHorizontalXXL,
        paddingBottom: tokens.spacingVerticalS,
        paddingLeft: tokens.spacingHorizontalXXL,
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        flexWrap: 'nowrap',
    },
    traceDescriptionField: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: '6px',
        opacity: '1',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        flexWrap: 'nowrap',
    },
    traceDescriptionStatus: {
        width: '164px',
        height: '24px',
        minWidth: '24px',
        borderRadius: tokens.borderRadiusLarge,

        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: '2px',
        opacity: '1',
        paddingTop: tokens.spacingVerticalNone,
        paddingRight: tokens.spacingHorizontalXS,
        paddingBottom: tokens.spacingVerticalNone,
        paddingLeft: tokens.spacingHorizontalXS,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        flexWrap: 'nowrap',
    },
    traceDescriptionStatusIcon: {
        color: tokens.colorStatusSuccessForeground3,
    },
    traceDescriptionStatusText: {
        fontFamily: tokens.fontFamilyBase,
        fontWeight: '600',
        fontStyle: 'Semibold',
        fontSize: tokens.fontSizeBase200,
        leadingTrim: 'NONE',
        lineHeight: tokens.lineHeightBase200,
        letterSpacing: '0%',
        textAlign: 'center',
        verticalAlign: 'middle',
        color: tokens.colorStatusSuccessForeground3,
        paddingRight: tokens.spacingHorizontalXXS,
        paddingLeft: tokens.spacingHorizontalXXS,
    },
    leftPane: {
        flex: 1,
        minWidth: 0,
        overflowY: 'auto',
        backgroundColor: tokens.colorNeutralBackground3,
    },
    rightPane: {
        overflow: 'hidden',
        flex: 1,
        minWidth: 0,
        '@media (width > 767px)': {
            borderLeft: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
        },
        '@media (width <=  767px)': {
            borderTop: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
        },
    },
    rightPaneInner: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
        overflowY: 'hidden',
        height: '100%',
    },
    rightPaneContent: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: '16px',
        opacity: 1,
        paddingTop: tokens.spacingVerticalXXL,
        paddingRight: tokens.spacingHorizontalXXL,
        paddingBottom: tokens.spacingVerticalXXL,
        paddingLeft: tokens.spacingHorizontalXXL,
        overflowY: 'auto',
    },
    rightPaneHeaderWrapper: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: '10px',
        borderBottom: '1px solid #ccc',
        padding: `10px ${tokens.spacingHorizontalXXL}`,
    },
    rightPaneHeader: {
        display: 'flex',
        flexDirection: 'column',
        gap: '2px',
    },
    rightPaneHeaderText: {
        fontWeight: 'bold',
    },
    rightPaneHeaderDuration: {
        marginLeft: 'auto',
    },
    rightPaneSection: {
        width: `calc(100% - ${tokens.spacingHorizontalXXL} * 2)`,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        borderRadius: tokens.borderRadiusLarge,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        gap: '12px',
        opacity: '1',
        padding: tokens.spacingHorizontalXL,
        backgroundColor: tokens.colorNeutralBackground3,
    },
    rightPaneSectionHeader: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyItems: 'space-between',
        gap: '6px',
    },
    rightPaneSectionHeaderText: {
        fontFamily: tokens.fontFamilyBase,
        fontWeight: 600,
        fontStyle: 'Semibold',
        fontSize: tokens.fontSizeBase300,
        lineHeight: tokens.lineHeightBase300,
        letterSpacing: '0%',
    },
    rightPaneSubsectionsContainer: {},
    rightPaneSubsection: {
        display: 'flex',
        flexDirection: 'column',
        justifyItems: 'space-between',
        gap: tokens.spacingVerticalSNudge,
        marginTop: '10px',
    },
    rightPaneSubsectionHeader: {
        fontFamily: tokens.fontFamilyBase,
        fontWeight: 600,
        fontStyle: 'Semibold',
        fontSize: tokens.fontSizeBase300,
        lineHeight: tokens.lineHeightBase300,
        letterSpacing: '0%',
    },
    rightPaneSubsectionBody: {
        borderRadius: tokens.borderRadiusMedium,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStrokeDisabled}`,
        opacity: 1,
        padding: '6px',
        backgroundColor: tokens.colorNeutralBackground1,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        flexWrap: 'nowrap',
    },
    rightPaneSubsectionBodyExpanded: {
        borderRadius: tokens.borderRadiusMedium,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStrokeDisabled}`,
        opacity: 1,
        padding: '6px',
        backgroundColor: tokens.colorNeutralBackground1,
        overflowX: 'auto',
    },
    messageBar: {
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStrokeDisabled}`,
    },
});
