import { makeStyles, tokens } from '@fluentui/react-components';

export const useTracePanelStyles = makeStyles({
    traceContainer: {
        display: 'flex',
        gridColumnStart: 1,
        gridColumnEnd: 4,
        flexGrow: 1,
        height: '0%',
        '@media (width > 767px)': {
            flexDirection: 'row',
        },
        '@media (width <=  767px)': {
            flexDirection: 'column',
        },
    },
    dialogTitle: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '10px',
        opacity: '1',
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
        flex: 'none',
    },
    dialogBody: {
        gap: '0px',
        '@media (width > 767px)': {
            height: '80vh',
        },
        '@media (width <=  767px)': {
            height: '100vh',
        },
    },
    traceDescription: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: '16px',
        opacity: 1,
        paddingTop: tokens.spacingVerticalS,
        paddingRight: tokens.spacingHorizontalXXL,
        paddingBottom: tokens.spacingVerticalS,
        paddingLeft: tokens.spacingHorizontalXXL,
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        flexWrap: 'nowrap',
    },
    traceDescriptionField: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: '6px',
        opacity: '1',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        flexWrap: 'nowrap',
    },
    traceDescriptionStatus: {
        width: '164px',
        height: '24px',
        minWidth: '24px',
        borderRadius: tokens.borderRadiusLarge,

        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: '2px',
        opacity: '1',
        paddingTop: tokens.spacingVerticalNone,
        paddingRight: tokens.spacingHorizontalXS,
        paddingBottom: tokens.spacingVerticalNone,
        paddingLeft: tokens.spacingHorizontalXS,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        flexWrap: 'nowrap',
    },
    traceDescriptionStatusIcon: {
        color: tokens.colorStatusSuccessForeground3,
    },
    traceDescriptionStatusText: {
        fontFamily: tokens.fontFamilyBase,
        fontWeight: '600',
        fontStyle: 'Semibold',
        fontSize: tokens.fontSizeBase200,
        leadingTrim: 'NONE',
        lineHeight: tokens.lineHeightBase200,
        letterSpacing: '0%',
        textAlign: 'center',
        verticalAlign: 'middle',
        color: tokens.colorStatusSuccessForeground3,
        paddingRight: tokens.spacingHorizontalXXS,
        paddingLeft: tokens.spacingHorizontalXXS,
    },
    leftPane: {
        flex: 1,
        minWidth: 0,
        overflowY: 'auto',
        backgroundColor: tokens.colorNeutralBackground3,
    },
    rightPane: {
        overflow: 'hidden',
        flex: 1,
        minWidth: 0,
        '@media (width > 767px)': {
            borderLeft: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
        },
        '@media (width <=  767px)': {
            borderTop: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
        },
    },
    rightPaneInner: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
        overflowY: 'hidden',
        height: '100%',
    },
    rightPaneContent: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: tokens.spacingVerticalM,
        opacity: 1,
        paddingTop: tokens.spacingVerticalL,
        paddingRight: tokens.spacingHorizontalL,
        paddingBottom: tokens.spacingVerticalL,
        paddingLeft: tokens.spacingHorizontalL,
        overflowY: 'auto',
    },
    rightPaneHeaderWrapper: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: tokens.spacingHorizontalS,
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        padding: `${tokens.spacingVerticalM} ${tokens.spacingHorizontalXXL}`,
    },
    rightPaneHeader: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalXXS,
        flex: 1,
        minWidth: 0,
    },
    rightPaneHeaderText: {
        fontWeight: tokens.fontWeightSemibold,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    },
    rightPaneHeaderDuration: {
        marginLeft: 'auto',
    },
    rightPaneSection: {
        width: '100%',
        boxSizing: 'border-box',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        borderRadius: tokens.borderRadiusMedium,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        gap: tokens.spacingVerticalS,
        padding: tokens.spacingHorizontalM,
        backgroundColor: tokens.colorNeutralBackground3,
    },
    rightPaneSectionHeader: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyItems: 'space-between',
        gap: '6px',
    },
    rightPaneSectionHeaderText: {
        fontFamily: tokens.fontFamilyBase,
        fontWeight: 600,
        fontStyle: 'Semibold',
        fontSize: tokens.fontSizeBase300,
        lineHeight: tokens.lineHeightBase300,
        letterSpacing: '0%',
    },
    rightPaneSubsectionsContainer: {},
    rightPaneSubsection: {
        display: 'flex',
        flexDirection: 'column',
        justifyItems: 'space-between',
        gap: tokens.spacingVerticalXS,
        marginTop: tokens.spacingVerticalS,
    },
    rightPaneSubsectionHeader: {
        fontFamily: tokens.fontFamilyBase,
        fontWeight: 600,
        fontStyle: 'Semibold',
        fontSize: tokens.fontSizeBase300,
        lineHeight: tokens.lineHeightBase300,
        letterSpacing: '0%',
    },
    rightPaneSubsectionBody: {
        borderRadius: tokens.borderRadiusMedium,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStrokeDisabled}`,
        opacity: 1,
        padding: '6px',
        backgroundColor: tokens.colorNeutralBackground1,
        overflow: 'hidden',
        whiteSpace: 'pre-wrap',
        wordBreak: 'break-word',
        maxHeight: '100px', // ~5 lines at default line height
        display: '-webkit-box',
        WebkitLineClamp: 5,
        WebkitBoxOrient: 'vertical',
    },
    rightPaneSubsectionBodyExpanded: {
        borderRadius: tokens.borderRadiusMedium,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStrokeDisabled}`,
        opacity: 1,
        padding: '6px',
        backgroundColor: tokens.colorNeutralBackground1,
        overflowX: 'auto',
        whiteSpace: 'pre-wrap',
        wordBreak: 'break-word',
        maxHeight: '400px', // Expanded but still scrollable for very long content
        overflowY: 'auto',
    },
    messageBar: {
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStrokeDisabled}`,
    },
});
