{
 "title": "App group dashboard",
 "tags": [
  "azure",
  "sreagent"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "appResourceId",
    "label": "App Resource Id",
    "query": {
     "query": "label_values(app_group_availability,resource_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_group_health{resource_id=\"$appResourceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "app_group_availability{resource_id=\"$appResourceId\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Avg cpu usage for past 30 mins",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "app_group_avg_cpu_usage{resource_id=\"$appResourceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg memory usage(MB) of past 30 mins",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "app_group_avg_memory_usage{resource_id=\"$appResourceId\"} / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Costs in dollars",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "app_group_costs{resource_id=\"$appResourceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "app_group_transactions{resource_id=\"$appResourceId\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}