// ------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All rights reserved.
// ------------------------------------------------------------

using System.Collections.Generic;
using Agent.Core.Helpers;
using Agent.Core.Interfaces;
using Agent.Web.Authorization;
using Microsoft.AspNetCore.Mvc;
using ArmOperations = Agent.Core.Constants.ArmOperations;

namespace Agent.Web.Controllers;

/// <summary>
/// Serves locally generated artifact files created by the Code Interpreter plugin.
/// Supports PDF, CSV, images, and other common file types generated by Python scripts.
/// Files are read from the 'reports' directory under <see cref="AppContext.BaseDirectory"/>.
/// Both /api/files and legacy /api/reports routes are supported for backward compatibility.
/// </summary>
[ApiController]
[Route("api/files")]            // Preferred new route
[Route("api/reports")]          // Legacy route (do not remove until callers migrated)
public class FilesController(IAgentFileStorageService agentFileStorageService) : ControllerBase
{
    private static readonly string ReportsRoot = Path.Combine(AppContext.BaseDirectory, "reports");

    // Allowed file extensions for security - comprehensive list for code interpreter outputs
    private static readonly HashSet<string> AllowedExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        // Documents and reports
        ".pdf", ".html", ".htm", ".md", ".txt", ".rtf",

        // Data and spreadsheets
        ".csv", ".tsv", ".xlsx", ".xls", ".xlsm", ".ods",

        // Structured data
        ".json", ".xml", ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf",

        // Images (matplotlib, seaborn, plotly, PIL outputs)
        ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".tiff", ".tif", ".svg", ".webp", ".ico",
        ".eps", ".ps", ".pgf", ".raw", ".rgba",

        // Office documents
        ".docx", ".doc", ".pptx", ".ppt", ".odt", ".odp", ".ods", ".odg",

        // Code and text files
        ".py", ".ipynb", ".r", ".sql", ".sh", ".bat", ".ps1", ".log",

        // Archive formats (for packaged outputs)
        ".zip", ".tar", ".gz", ".7z",

        // Audio/Video (for multimedia data analysis outputs)
        ".mp3", ".wav", ".mp4", ".avi", ".mov", ".mkv",

        // Scientific/Technical formats
        ".h5", ".hdf5", ".nc", ".mat", ".npz", ".pkl", ".pickle",

        // Web formats
        ".css", ".js", ".mjs"
    };

    // MIME type mappings
    private static readonly Dictionary<string, string> MimeTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        // Documents and reports
        { ".pdf", "application/pdf" },
        { ".html", "text/html" },
        { ".htm", "text/html" },
        { ".md", "text/markdown" },
        { ".txt", "text/plain" },
        { ".rtf", "application/rtf" },

        // Data and spreadsheets
        { ".csv", "text/csv" },
        { ".tsv", "text/tab-separated-values" },
        { ".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
        { ".xls", "application/vnd.ms-excel" },
        { ".xlsm", "application/vnd.ms-excel.sheet.macroEnabled.12" },
        { ".ods", "application/vnd.oasis.opendocument.spreadsheet" },

        // Structured data
        { ".json", "application/json" },
        { ".xml", "application/xml" },
        { ".yaml", "text/yaml" },
        { ".yml", "text/yaml" },
        { ".toml", "application/toml" },
        { ".ini", "text/plain" },
        { ".cfg", "text/plain" },
        { ".conf", "text/plain" },

        // Images
        { ".png", "image/png" },
        { ".jpg", "image/jpeg" },
        { ".jpeg", "image/jpeg" },
        { ".gif", "image/gif" },
        { ".bmp", "image/bmp" },
        { ".tiff", "image/tiff" },
        { ".tif", "image/tiff" },
        { ".svg", "image/svg+xml" },
        { ".webp", "image/webp" },
        { ".ico", "image/x-icon" },
        { ".eps", "application/postscript" },
        { ".ps", "application/postscript" },
        { ".pgf", "application/x-pgf" },
        { ".raw", "application/octet-stream" },
        { ".rgba", "application/octet-stream" },

        // Office documents
        { ".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
        { ".doc", "application/msword" },
        { ".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
        { ".ppt", "application/vnd.ms-powerpoint" },
        { ".odt", "application/vnd.oasis.opendocument.text" },
        { ".odp", "application/vnd.oasis.opendocument.presentation" },
        { ".odg", "application/vnd.oasis.opendocument.graphics" },

        // Code and text files
        { ".py", "text/x-python" },
        { ".ipynb", "application/x-ipynb+json" },
        { ".r", "text/x-r" },
        { ".sql", "text/x-sql" },
        { ".sh", "text/x-shellscript" },
        { ".bat", "text/x-batch" },
        { ".ps1", "text/x-powershell" },
        { ".log", "text/plain" },

        // Archive formats
        { ".zip", "application/zip" },
        { ".tar", "application/x-tar" },
        { ".gz", "application/gzip" },
        { ".7z", "application/x-7z-compressed" },

        // Audio/Video
        { ".mp3", "audio/mpeg" },
        { ".wav", "audio/wav" },
        { ".mp4", "video/mp4" },
        { ".avi", "video/x-msvideo" },
        { ".mov", "video/quicktime" },
        { ".mkv", "video/x-matroska" },

        // Scientific/Technical formats
        { ".h5", "application/x-hdf5" },
        { ".hdf5", "application/x-hdf5" },
        { ".nc", "application/x-netcdf" },
        { ".mat", "application/x-matlab-data" },
        { ".npz", "application/x-numpy-data" },
        { ".pkl", "application/x-pickle" },
        { ".pickle", "application/x-pickle" },

        // Web formats
        { ".css", "text/css" },
        { ".js", "text/javascript" },
        { ".mjs", "text/javascript" }
    };

    /// <summary>
    /// Download an artifact file by filename.
    /// Supports various file types generated by the Code Interpreter plugin.
    /// Files are read directly from the local reports directory.
    /// </summary>
    [HttpGet("{fileName}")]
    [AuthorizeArmOperation(ArmOperations.AgentThreadReadActionId)] // reuse read action for artifact retrieval
    public IActionResult Get(string fileName)
    {
        // Basic validation
        if (string.IsNullOrWhiteSpace(fileName))
        {
            return BadRequest("fileName required");
        }

        // Security: Check for invalid characters
        if (fileName.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0)
        {
            return BadRequest("invalid file name");
        }

        // Security: Prevent path traversal attacks - check for any path separators
        if (fileName.Contains('/') || fileName.Contains('\\') || fileName.Contains(".."))
        {
            return BadRequest("invalid path - only filenames allowed");
        }

        // Security: Validate file extension
        var extension = Path.GetExtension(fileName);
        if (string.IsNullOrEmpty(extension) || !AllowedExtensions.Contains(extension))
        {
            return BadRequest($"file type not allowed. Supported types: {string.Join(", ", AllowedExtensions)}");
        }

        // Security: Build and validate the full path (prevents path traversal and symlink attacks)
        if (!PathSecurityHelper.TryGetSafeFilePath(ReportsRoot, fileName, out var canonicalFilePath) || canonicalFilePath == null)
        {
            return BadRequest("access denied - file must be in reports directory");
        }

        // Check if file exists locally
        if (!System.IO.File.Exists(canonicalFilePath))
        {
            return NotFound();
        }

        var stream = System.IO.File.OpenRead(canonicalFilePath);
        var mimeType = MimeTypes.TryGetValue(extension, out var type) ? type : "application/octet-stream";
        return File(stream, mimeType, fileName);
    }

    /// <summary>
    /// Download an artifact file by thread ID and filename.
    /// Uses IAgentFileStorageService to retrieve thread-specific files.
    /// Supports nested paths for files in subdirectories.
    /// </summary>
    [HttpGet("{threadId}/{**filePath}")]
    [AuthorizeArmOperation(ArmOperations.AgentThreadReadActionId)]
    public async Task<IActionResult> GetByThread(Guid threadId, string filePath)
    {
        // Basic validation
        if (string.IsNullOrWhiteSpace(filePath))
        {
            return BadRequest("filePath required");
        }

        // Security: Prevent path traversal attacks - check for parent directory traversal
        if (filePath.Contains(".."))
        {
            return BadRequest("invalid path - parent directory traversal not allowed");
        }

        // Security: Validate file extension (check the actual filename at the end of the path)
        var fileName = Path.GetFileName(filePath);
        var extension = Path.GetExtension(fileName);
        if (string.IsNullOrEmpty(extension) || !AllowedExtensions.Contains(extension))
        {
            return BadRequest($"file type not allowed. Supported types: {string.Join(", ", AllowedExtensions)}");
        }

        // Download from thread file storage
        var localFilePath = await agentFileStorageService.DownloadThreadFileAsync(threadId, filePath);
        if (localFilePath == null)
        {
            return NotFound();
        }

        var stream = System.IO.File.OpenRead(localFilePath);
        var mimeType = MimeTypes.TryGetValue(extension, out var type) ? type : "application/octet-stream";
        return File(stream, mimeType, fileName);
    }
}
