let antaresStamps = dynamic(['##antaresStamps##']);
let appName = "##appName##";
let endTime = datetime("##endTime##");
let numRows = int(##numRows##);
let privateStampName = "##privateStampName##";
let startTime = datetime("##startTime##");
FunctionsPlatformLogs
| where PreciseTimeStamp between(startTime .. endTime)
| where EventPrimaryStampName in (antaresStamps)
| where SiteName in ("##siteNames##")
| where Message contains "Pod allocation failed due to no capacity"
| summarize count_= count() by SiteName, bin(PreciseTimeStamp, 10m)
| project PreciseTimeStamp, SiteName, count_
