let antaresStamps = dynamic(['##antaresStamps##']);
let appName = "##appName##";
let endTime = datetime("##endTime##");
let numRows = int(##numRows##);
let privateStampName = "##privateStampName##";
let startTime = datetime("##startTime##");
FunctionsPlatformLogs
| where PreciseTimeStamp between(startTime .. endTime)
| where EventPrimaryStampName in (antaresStamps)
| where SiteName in ("##siteNames##")
| where Message contains "Throttling site worker assignment due to:"
| summarize count() by Message
| project Message, count_
