// ------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All rights reserved.
// ------------------------------------------------------------

namespace Agent.Runtime.Workflow;

/// <summary>
/// Context information for workflow execution.
/// This is set programmatically and not generated by LLM.
/// </summary>
public class WorkflowExecutionContext
{
    /// <summary>
    /// Unique identifier for this workflow execution.
    /// </summary>
    public string WorkflowId { get; set; } = string.Empty;

    /// <summary>
    /// Current step number in the workflow.
    /// </summary>
    public int StepNumber { get; set; }

    /// <summary>
    /// Total number of agents executed so far.
    /// </summary>
    public int ExecutedAgentCount { get; set; }

    /// <summary>
    /// Maximum allowed agents in this workflow.
    /// </summary>
    public int MaxAgentCount { get; set; } = 10;

    /// <summary>
    /// All parameters accumulated throughout the workflow execution.
    /// </summary>
    public WorkflowParameters AccumulatedParameters { get; set; } = new();

    /// <summary>
    /// Parent orchestrator agent name.
    /// </summary>
    public string? OrchestratorAgent { get; set; }

    /// <summary>
    /// Workflow execution start time.
    /// </summary>
    public DateTime StartedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Creates a deep clone of this execution context for independent branch execution.
    /// Each branch gets its own parameter context while maintaining workflow metadata.
    /// </summary>
    public WorkflowExecutionContext Clone()
    {
        return new WorkflowExecutionContext
        {
            WorkflowId = WorkflowId,
            StepNumber = StepNumber,
            ExecutedAgentCount = ExecutedAgentCount,
            MaxAgentCount = MaxAgentCount,
            AccumulatedParameters = new WorkflowParameters(AccumulatedParameters.Values),
            OrchestratorAgent = OrchestratorAgent,
            StartedAt = StartedAt
        };
    }
}
