# https://aka.ms/obpipelines/triggers
trigger:
  batch: true
  branches:
    include:
    - main

parameters:
- name: timeoutMinutes
  type: number
  default: 60

variables:
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    iterationCount: 1
  ${{ elseif eq(variables['Build.Reason'], 'BatchedCI') }}:
    iterationCount: 1
  ${{ else }}:
    iterationCount: 5

steps:
- script: echo Integration Test Pipeline Run $(Build.BuildNumber)!
  displayName: 'Starting Evals run'

- task: UseDotNet@2
  continueOnError: false
  displayName: '🧰 Setup .NET 9'
  inputs:
    version: 9.x
    packageType: 'sdk'

- task: NuGetAuthenticate@1
  inputs:
    forceReinstallCredentialProvider: false # Optional

# Restore nuget
- script: dotnet restore src/Agent/Agent.Evals/Agent.Evals.csproj
  env:
    NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS: 60
    NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS: 60

  displayName: 'Restore nuget'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'SRE_AGENT_TESTING_SERVICE_CONNECTION'
    KeyVaultName: 'sre-agent-keyvault'
    SecretsFilter: '*'
    RunAsPreJob: false

# Start DTS emulator container
- script: docker run -d --rm --name dts-emulator -p 14280:8080 -p 14282:8082 -e ClientAuth__DisableAuthentication=true mcr.microsoft.com/dts/dts-emulator:v0.0.6
  displayName: 'Start DTS emulator container'
  timeoutInMinutes: 5

- script: src/run-gremlin-emulator.sh
  displayName: 'Start Gremlin emulator container'
  timeoutInMinutes: 5

# Execute the test
- script: dotnet test --no-restore --logger trx --results-directory $(Build.SourcesDirectory)/TestResults/ --settings evals.runsettings
  workingDirectory: $(Build.SourcesDirectory)/src/Agent/Agent.Evals
  env:
    OpenAIEndpoint: $(SRE_AGENT_OPENAI_ENDPOINT)
    OpenAIKey: $(EvalsOpenAIKey)
    OpenAIModel: $(SRE_AGENT_OPENAI_MODEL)
    IterationCount: $(iterationCount)
  timeoutInMinutes: ${{ parameters.timeoutMinutes }}
  displayName: 'Running evals'
  continueOnError: true

- script: dotnet test --no-restore --logger trx --results-directory $(Build.SourcesDirectory)/TestResults/ --settings evals.runsettings
  workingDirectory: $(Build.SourcesDirectory)/src/Agent/Agent.Evals
  env:
    OpenAIEndpoint: https://sre3ppipe-openai-swedencentral.openai.azure.com/
    OpenAIKey: $(EvalsOpenAIKey41)
    OpenAIModel: sre3ppipe-gpt-41
    IterationCount: $(iterationCount)
  timeoutInMinutes: ${{ parameters.timeoutMinutes }}
  displayName: 'Running evals (gpt-4.1)'
  continueOnError: true

- task: PublishTestResults@2
  condition: always()
  inputs:
    testRunner: VSTest
    testResultsFiles: '$(Build.SourcesDirectory)/TestResults/**/*.trx'

# upload test results to blob storage
- task: AzureCLI@2
  displayName: 'Upload test results to blob storage'
  inputs:
    azureSubscription: 'SRE_AGENT_TESTING_SERVICE_CONNECTION'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Uploading test results to blob storage"
      az storage blob upload-batch \
        --connection-string "$(BlobStorageConnectionString)" \
        --destination test-results \
        --source $(Build.SourcesDirectory)/TestResults \
        --pattern *.trx \
        --overwrite true

# Publish test result to event hub
- script: dotnet run --project src/Agent/Agent.Evals.Cmd/Agent.Evals.Cmd.csproj
  condition: always()
  env:
    SRE_AGENT_TESTING_TEST_RESULTS_LOCATION: '$(Build.SourcesDirectory)/TestResults/'
    SRE_AGENT_EVENT_HUB_CONNECTION_STRING: $(TestResultEventHubConnectionStr)
  timeoutInMinutes: ${{ parameters.timeoutMinutes }}
  displayName: 'Uploading evals tests results to event hub'

# Stop the DTS emulator container
- script: docker stop dts-emulator
  condition: always()
  displayName: 'Stop DTS emulator container'
  continueOnError: true

- script: docker stop gremlin
  condition: always()
  displayName: 'Stop Gremlin emulator container'
  continueOnError: true