// ============================================================
// SRE Agent Extension File Loader Module
// ============================================================
// 
// This module loads YAML configuration files for agents and
// tools, processing them into structured extension data for
// deployment.
// 
// This file is generated by 'srectl extension generate-ev2'
// based on your agent and tool folder contents. You can edit
// this file manually if needed for small adjustments, or
// regenerate it using the CLI command.
// ============================================================

// ------------------------------------------------------------
// Agent Configuration Files
// ------------------------------------------------------------
// Loads agent YAML files and parses them into structured data
// for deployment configuration.
// ------------------------------------------------------------
output subagents array = [
  // {{AGENT_YAML_FILES}}
]

// ------------------------------------------------------------
// Tool Configuration Files
// ------------------------------------------------------------
// Loads tool YAML files and extracts extension data for
// integration with the SRE Agent deployment.
// ------------------------------------------------------------
output tools array = [
  // {{TOOL_YAML_FILES}}
]
