// Defines a table to identify 3P customers

// AgentDocumentDBState is updated every ~2 hours; determine the most recent update.
let UpdateFrequency = 2h;
// Determine the most recent snapshot
let LatestSnapshot =
    toscalar(
    All('AgentDocumentDBState')
    | extend snapshot = bin(PreciseTimeStamp, UpdateFrequency)
    | summarize max(snapshot)
    );
// Also the first snapshot available, to avoid counting a surplus of "births" in that period
let EarliestSnapshot = toscalar(
    All('AgentDocumentDBState')
    | extend snapshot = bin(PreciseTimeStamp, UpdateFrequency)
    | summarize min(snapshot)
    );
// Identify 3P customers
let ThirdPartyCustomers = cluster("customerdomrptwus3prod.westus3.kusto.windows.net")
    .database("customerdomdata")
    .Product360CustomerSubscriptions
    | where OfferType !contains "Internal" and isnotempty(CloudCustomerGuid)
    | project
        SubscriptionId,
        OfferType,
        CloudCustomerName,
        OfferName,
        BillingType,
        TPName,
        TPNameTranslated,
        TPID,
        SegmentName,
        IndustryName,
        CloudCustomerGuid; // (SubscriptionId, CloudCustomerGuid) is a unique key
// Inventory all 3P agents, their lifespans, and whether they've been deleted.
let AgentCensus = All('AgentDocumentDBState')
    | extend snapshot = bin(PreciseTimeStamp, UpdateFrequency)
    | where isnotempty(agentEndpoint)
    | join kind=inner ThirdPartyCustomers
        on $left.subscriptionId == $right.SubscriptionId
    | summarize
        lastSnapshot = max(snapshot),
        firstSnapshot = min(snapshot),
        agentLifetime = max(snapshot) - min(snapshot)
        by
        agentEndpoint,
        subscriptionId
    // Agents can be created and deleted in the same snapshot.
    // Consider them deleted if they were not present in the *penultimate* snapshot.
    | extend isDeleted = lastSnapshot < LatestSnapshot - UpdateFrequency
    // Opposite problem at the start: some agents predate the data window, so we don't observe their birth.
    | extend isNew = firstSnapshot > EarliestSnapshot + UpdateFrequency;
// Summarize by all customers.
let Customers = AgentCensus
    | join kind=leftouter ThirdPartyCustomers on $left.subscriptionId == $right.SubscriptionId
    | summarize
        numSubscriptions = dcount(subscriptionId),
        runningAgents = sum(tolong(not(isDeleted))),
        deletedAgents = sum(tolong(isDeleted)),
        newAgents = sum(tolong(isNew)), // agents we observed the birth of
        oldAgents = count() - sum(tolong(isNew)), // agents that predated our data window
        firstSeen = min(firstSnapshot),
        lastSeen = max(lastSnapshot),
        agentDays = sum(agentLifetime)
        by
        CloudCustomerName,
        TPNameTranslated,
        BillingType,
        SegmentName,
        IndustryName,
        CloudCustomerGuid
    | extend
        FirstWeek = GetFridayWeekStart(firstSeen),
        LastWeek = GetFridayWeekStart(lastSeen),
        isChurned = runningAgents == 0;

