import { ApiVersions } from '../ApiVersions';
import { ArmTemplateBuilder } from '../ArmTemplateBuilder/ArmTemplateBuilder';
import { ArmTemplateResource } from '../ArmTemplateBuilder/ArmTemplateResource';
import {
    ArmServiceType,
    ArmTemplateParameter,
    ArmTemplateParameterName,
    ArmTemplateResourceFragment,
    GrafanaParameterName as ParamName,
} from '../ArmTemplateBuilder/ArmTemplateTypes';

export interface GrafanaTemplateResourceOptions {
    namePrefix: string;
}

export class GrafanaTemplateResource extends ArmTemplateResource<object> {
    get type(): string {
        return ArmServiceType.DashboardGrafana;
    }

    parameters: Record<string, ArmTemplateParameter> = {
        [ParamName.GrafanaName]: {
            type: 'string',
            defaultValue: "[format('{0}-grafana', parameters('namePrefix'))]",
        },
    };

    constructor(builder: ArmTemplateBuilder) {
        super(builder);
    }

    addResourceToBuilder(): void {
        this._builder.resources.push(this);
    }

    _getTemplateFragmentHelper(): ArmTemplateResourceFragment<object> {
        return {
            apiVersion: ApiVersions.grafana20241001,
            name: `[parameters('${ParamName.GrafanaName}')]`,
            type: ArmServiceType.DashboardGrafana,
            location: `[parameters('${ArmTemplateParameterName.Location}')]`,
            sku: {
                name: 'Standard',
            },
            identity: {
                type: 'SystemAssigned',
            },
            properties: {
                apiKey: 'Enabled',
                autoGeneratedDomainNameLabelScope: 'TenantReuse',
                deterministicOutboundIP: 'Enabled',
                grafanaIntegrations: {
                    azureMonitorWorkspaceIntegrations: [],
                },
                publicNetworkAccess: 'Enabled',
                zoneRedundancy: 'Disabled',
            },
        };
    }
}
