let _start = datetime("##startTime##");
let _end = datetime("##endTime##");
let _siteName = "##siteName##";
let _functionName = "##functionName##";
// summarizationTimeBucket = 5m by default
let summarizationTimeBucket = ##summarizationTimeBucket##;
FunctionsLogs
| where PreciseTimeStamp between(_start .. _end)
| where AppName == _siteName
| where FunctionName == _functionName
| where EventName == "FunctionStarted"
| summarize Count = count() by bin(PreciseTimeStamp, summarizationTimeBucket), EventStampName
| project Count, PreciseTimeStamp, EventStampName
| order by PreciseTimeStamp asc
