let start = datetime("##startTime##");
let end = datetime("##endTime##");
let stampName = "##eventPrimaryStampName##";
let siteName = "##siteName##";
ScaleControllerEvents
| where PreciseTimeStamp between(start .. end)
| where EventPrimaryStampName == stampName
| where SiteName == siteName
| where Message startswith "Agg"
| summarize Count = count() by bin(PreciseTimeStamp, 1h)
| project Count, PreciseTimeStamp