let _start = datetime("##startTime##");
let _end = datetime("##endTime##");
let _stampName = "##eventPrimaryStampName##";
let _siteName = "##siteName##";
ScaleControllerEvents
| where PreciseTimeStamp between(_start .. _end)
| where EventPrimaryStampName == _stampName
| where SiteName == _siteName
| where Message contains "AggregateScaleStatus"
| summarize Count = count() by bin(PreciseTimeStamp, 1h)
| project Count, PreciseTimeStamp