let _start = datetime("##startTime##");
let _end = datetime("##endTime##");
let _stampName = "##eventPrimaryStampName##";
let _siteName = "##siteName##";
// summarizationTimeBucket = 1m by default
let summarizationTimeBucket = ##summarizationTimeBucket##;
AntaresDataServiceApiTransactions
| where PreciseTimeStamp between(_start .. _end)
| where EventPrimaryStampName == _stampName
| where OperationName == "EnsureWorkersForSite"
| parse RequestUrl with * "sites/" AppName "/" * "count=" CountString "&" *
| where AppName == _siteName
| extend Count = toint(CountString)
| summarize MaxCount = max(Count) by bin(PreciseTimeStamp, summarizationTimeBucket), SiteName=AppName
| project MaxCount, PreciseTimeStamp, SiteName
