let start = datetime("##startTime##");
let end = datetime("##endTime##");
let stampName = "##eventPrimaryStampName##";
let siteName = "##siteName##";
// summarizationTimeBucket = 5m by default
let summarizationTimeBucket = ##summarizationTimeBucket##;
FunctionsLogs
| where PreciseTimeStamp between(start .. end)
| where EventPrimaryStampName == stampName
| where AppName == siteName
| extend WorkerId = strcat(EventPrimaryStampName, "_", RoleInstance)
| summarize Count = dcount(WorkerId) by bin(PreciseTimeStamp, summarizationTimeBucket)
| project Count, PreciseTimeStamp
