let _start = datetime("##startTime##");
let _end = datetime("##endTime##");
let _stampName = "##eventPrimaryStampName##";
let _siteName = "##siteName##";
let _level = ##level##;
ScaleControllerEvents
| where PreciseTimeStamp between(_start .. _end)
| where EventPrimaryStampName == _stampName
| where SiteName == _siteName
| where Level < _level
| take 100
| project PreciseTimeStamp, RoleInstance, Message, Exception, Version, Level
