<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="aca-appsettings*.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" />
		<PackageReference Include="Azure.Search.Documents" />
		<PackageReference Include="Azure.Storage.Blobs" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.SemanticKernel" />
		<PackageReference Include="Markdig" />
		<PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureOpenAI" />
		<PackageReference Include="System.Linq" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Agent.Core\Agent.Core.csproj" />
		<ProjectReference Include="..\Agent.Plugins\Agent.Plugins.csproj" />
		<ProjectReference Include="..\Agent.Runtime\Agent.Runtime.csproj" />
	</ItemGroup>

	<ItemGroup>
      <None Include="AlertDetails\245c5900-d024-479f-9768-8aa8f1beb28e.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
      <None Include="AlertDetails\dbee4297-3491-4bac-92f8-5471208ff66d.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Include="AlertDetails\7c5a4fca-bd4d-4272-baa1-6f4abe6f24a2.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Include="AlertDetails\97950ded-8bbc-4bda-bcfa-e74aa45c1381.json">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Include="ICMAlertConfigs\7c5a4fca-bd4d-4272-baa1-6f4abe6f24a2.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
      <None Include="ICMAlertConfigs\245c5900-d024-479f-9768-8aa8f1beb28e.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
      <None Include="ICMAlertConfigs\dbee4297-3491-4bac-92f8-5471208ff66d.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Include="ICMAlertConfigs\97950ded-8bbc-4bda-bcfa-e74aa45c1381.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Include="ICMAlertConfigs\e6f9db3c-80ab-485c-a428-ed3a0b4c24c3.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Include="ICMAlertConfigs\e3b2c8f4-7a1d-4c9e-8f3a-2d6b9a1e5c4f.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
    <None Include="ICMAlertConfigs\0da2f663-321c-47a3-80b7-78dcb9e9a263.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="ICMAlertConfigs\000fa255-4323-41ce-ac8a-369e6bfe0284.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
	  <None Include="Plugins\PluginConfig.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
    <!-- Flex Consumption SKU Start-->
    <None Update="AlertDetails\a4508d33-6d76-4ceb-b61e-50166e784a9c.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AlertDetails\d3d66242-7588-46d9-95af-52a04d86d87c.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AlertDetails\e9221b03-8344-4182-97dc-09bab5e8cb46.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ICMAlertConfigs\614bb35c-96b0-4e5d-825d-5f2a5c6d9a8a.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ICMAlertConfigs\a4508d33-6d76-4ceb-b61e-50166e784a9c.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ICMAlertConfigs\d2126c3e-10d7-4d99-b404-7ad2f8438f60.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ICMAlertConfigs\d3d66242-7588-46d9-95af-52a04d86d87c.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ICMAlertConfigs\f9110571-1b04-484b-b10f-ee3d130b1447.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <!-- Flex Consumption SKU End-->
	</ItemGroup>

	<ItemGroup>
	  <None Update="ICMAlertConfigs\5a77158c-8385-49f8-8f96-019a641df17b.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="ICMAlertConfigs\c1168c0a-13db-43d0-8188-062d5c273c08.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="ICMAlertConfigs\f9110571-1b04-484b-b10f-ee3d130b1447.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Plugins\Definitions\Queries\*.kql">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Plugins\GenevaActionsPlugin\GenevaActions.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
  
  <!-- Add system prompt files -->
  <ItemGroup>
    <None Update="FirstPartyAgents\ACA\**\*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <!-- Add sub-agents plan files -->
  <ItemGroup>
    <None Update="FirstPartySubAgents\ACA\**\*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

</Project>
