<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Search.Documents" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.SemanticKernel" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Agent.Core\Agent.Core.csproj" />
		<ProjectReference Include="..\Agent.Runtime\Agent.Runtime.csproj" />
	</ItemGroup>

</Project>
