<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Search.Documents" />
		<PackageReference Include="Azure.Storage.Blobs" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.SemanticKernel" />
		<PackageReference Include="Markdig" />
		<PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureOpenAI" />
		<PackageReference Include="System.Linq" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Agent.Core\Agent.Core.csproj" />
		<ProjectReference Include="..\Agent.Plugins\Agent.Plugins.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="AlertDetails\7c5a4fca-bd4d-4272-baa1-6f4abe6f24a2.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Include="AlertDetails\97950ded-8bbc-4bda-bcfa-e74aa45c1381.json">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Include="ICMAlertConfigs\7c5a4fca-bd4d-4272-baa1-6f4abe6f24a2.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Include="ICMAlertConfigs\97950ded-8bbc-4bda-bcfa-e74aa45c1381.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Include="ICMAlertConfigs\e6f9db3c-80ab-485c-a428-ed3a0b4c24c3.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Include="Plugins\PluginConfig.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <None Update="ICMAlertConfigs\5a77158c-8385-49f8-8f96-019a641df17b.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="ICMAlertConfigs\c1168c0a-13db-43d0-8188-062d5c273c08.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="ICMAlertConfigs\f9110571-1b04-484b-b10f-ee3d130b1447.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Plugins\GenevaActionsPlugin\GenevaActions.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
