let region = "##region##";
let managedClusterName = "##managedClusterName##";
let recordsCount = toscalar(
    ExternalAuthEvents
    | where EnvironmentName contains managedClusterName
    | where msg contains "request recieved"
    // Look for any successful auth events
    | take 1
    | count
);
// Return a clear boolean flag
print IsAspireEnabled = iff(recordsCount > 0, true, false)
| project IsAspireEnabled
