let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let managedClusterName = "##managedClusterName##";
let threshold = toint("##threshold##");
SwiftNetworkingEvents
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where EnvironmentName == managedClusterName
| where msg contains "failed to resolve . for dns server"
| summarize FailureCount = count(), StartTime = min(TIMESTAMP), EndTime = max(TIMESTAMP)
| where FailureCount > threshold
