// Get DNS server manager operations to identify DNS resolution issues affecting outbound connections
let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let local_LegionEnvironmentName = "##legionEnvironmentName##";
let local_ResourceNamespace = "##resourceNamespace##";
let local_PodName = "##podName##";

Log
| where TIMESTAMP between (queryFrom .. queryTo)
| where LegionEnvironmentName == local_LegionEnvironmentName
| where PodName == local_PodName
| where ResourceNamespace == local_ResourceNamespace
| where env_name == "Microsoft.Legion.Common.Podr.AbstractDnsServerManager"  
    or env_name == "Microsoft.Legion.Common.Podr.DnsListenerManager"
    or env_name == "Microsoft.Legion.Common.Podr.CoreDnsManager"
| project TIMESTAMP, Message, Operation, Value, env_dt_traceId
