let queryFrom = datetime("##queryFrom##");
let queryTo = datetime("##queryTo##");
let managedClusterName = "##managedClusterName##";
let containerAppJobName = "##containerAppJobName##";
ContainerAppControllerEvents
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where EnvironmentName == managedClusterName
| where ContainerAppJobName == containerAppJobName
| where JobExecutionStatus == "Failed"
| extend JobExecutionJsonJson = parse_json(JobExecutionJson)
| extend JobExecutionStatusDetails = JobExecutionJsonJson.status
| project PreciseTimeStamp, JobExecutionName, JobExecutionStatus, JobExecutionStatusDetails