let fromDate = datetime("##fromDate##");
let toDate = datetime("##toDate##");
let queryTraceId = "##env_dt_traceId##";
ContainerAppsAdminEvents
| where PreciseTimeStamp between (fromDate .. toDate)
| where Level < 4
| where env_dt_traceId == queryTraceId
| summarize StartTime=min(PreciseTimeStamp),EndTime=max(PreciseTimeStamp) by message
| project StartTime, EndTime, Message=message
| order by StartTime asc
| limit 50
| project StartTime, EndTime, Message
