let queryFrom = datetime("##queryFrom##");
let queryTo = datetime("##queryTo##");
let environmentName =  "##managedClusterName##";
let jobName = "##containerAppJobName##";
EventProcessorEvents
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where EnvironmentName == environmentName
| where
    (ExecutionName contains strcat(jobName, "-")) or
    (InvolvedObjectKind == "ContainerAppJob" and InvolvedObjectName contains jobName)
| where Type != "Normal"
| where Internal == true
| where msg !contains "exit code '0'" and msg !contains "ManuallyStopped"
// | where Reason != ""
| summarize by msg, Reason, Count//, Type, ExecutionName, InvolvedObjectKind//, JobName,  InvolvedObjectName, InvolvedObjectNamespace
| project Message=msg, Reason, Count
