let qFrom = datetime("##fromDate##");
let qTo = datetime("##toDate##");
let qClusterName = "##managedClusterName##";
let qCCP = toscalar(ManagedClusterSnapshot
| where PreciseTimeStamp between (qFrom .. qTo)
| where name == qClusterName
| summarize arg_max(PreciseTimeStamp, namespace) by name
| project namespace)
;
let qArea = "";
set best_effort=true;
let alerts = AKSAlertmanager
| where PreciseTimeStamp between (qFrom .. qTo)
| where cluster_id == qCCP and severity in ('critical', 'warning')
| where isempty(qArea) or (isnotempty(qArea) and area == qArea)
| project PreciseTimeStamp, startsAt, endsAt, status, alertname, area, severity, node
| summarize cnt = count(), nodes = make_set_if(node, isnotempty(node)) by bin(PreciseTimeStamp, 5m), alertname, startsAt, endsAt, status, area, severity
//| make-series cnt = sum(cnt), take_any(nodes) default=0 on PreciseTimeStamp in range(qFrom, qTo, 5m) by alertname, startsAt, endsAt, status, area, severity
//| mv-expand PreciseTimeStamp to typeof(datetime), cnt to typeof(int)
| where cnt > 0
;
let areas = datatable (PreciseTimeStamp:datetime, alertname:string, area:string, severity:string, description:string) [
    datetime(null), '', 'node', '', '',
];
// populate a base table will all data to show all areas defaulting to healthy
let defaultTimeline = areas 
| extend PreciseTimeStamp = qFrom
| where isempty(qArea) or (isnotempty(qArea) and area == qArea)
| make-series count() default=0 on PreciseTimeStamp in range(qFrom, qTo, 5m) by alertname, area, severity, description
| project-away count_
| mv-expand PreciseTimeStamp to typeof(datetime) 
;
defaultTimeline
| join kind=leftouter (alerts) on PreciseTimeStamp, $left.area == $right.area
| extend area = coalesce(area, area1)
| extend alertname = coalesce(alertname, alertname1)
| extend severity = coalesce(severity, severity1)
| project-away *1, description
| summarize 
    all = make_set_if(alertname, isnotempty(alertname)),
    warnings = make_set_if(alertname, severity == 'warning'), 
    criticals = make_set_if(alertname, severity == 'critical'), 
    nodes = make_set(nodes),
    take_any (startsAt, endsAt) 
    by PreciseTimeStamp, area
| extend warnings = array_sort_asc(warnings)
| extend criticals = array_sort_asc(criticals)
| extend all = array_sort_asc(all)
| extend Key = array_strcat(all, '-')
| order by area asc, PreciseTimeStamp asc
| extend StartTime = PreciseTimeStamp
| serialize
// Filter out rows where things don't change - keeps the first and last row of each range
| where 
    (area != next(area) or area != prev(area)) or 
    (Key != next(Key) or Key != prev(Key)) 
// End time is when the next row starts
| extend EndTime = next(StartTime)
// Keep only rows start a range
| where area != prev(area) or Key != prev(Key) 
| extend Content = iff(array_length(all) > 0, strcat(array_length(all), ' Alerts'), 'Healthy')
| extend Tooltip = strcat(
    Content,
    "<br/>Criticals: ", array_strcat(criticals, ", "),
    "<br/>Warnings: ", array_strcat(warnings, ", "),
    "<br/>Nodes: ", array_strcat(nodes, ", ")
)
| extend EndTime = iif(isnull(EndTime), datetime_add('minute', 1, StartTime), EndTime)
| extend Health = case (
    array_length(criticals) > 0, 'error',
    array_length(warnings) > 0, 'degraded',
    'healthy'
)
| extend area ='Alerts: Node'
| extend GroupBy = area
| project StartTime, EndTime, Content, Tooltip, Health, GroupBy, warnings, criticals
