let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let capp_name = "##containerAppName##";
let capp_rg = "##resourceGroupName##";
let capp_sub = "##subscriptionId##";
let managedClusterName = toscalar(GetManagedClusterName(capp_name, capp_rg, capp_sub));
Heartbeats
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where ContainerAppName == capp_name
| where EnvironmentName == managedClusterName
| extend parsedJson = parse_json(AppJson)
| extend latestReadyRevisionName = tostring(parsedJson.status.latestReadyRevisionName)
| extend currentActiveRevisionName = tostring(parsedJson.status.currentActiveRevisionName)
| extend RevisionRunningState = tostring(parsedJson.status.containerAppRunningState)
| extend time_state = todynamic(strcat("{\"timestamp\": \"", PreciseTimeStamp, "\", \"state\": \"", RevisionRunningState, "\"}"))
| project PreciseTimeStamp, RevisionName, RevisionRunningState, time_state
| summarize time_state_array = make_set(time_state) by RevisionName
| project RevisionName, time_state_array
| mv-apply element = todynamic(RevisionName) on (
    mv-expand time_state_array
    | extend timestamp = todatetime(parse_json(time_state_array)["timestamp"])
    | extend state = tostring(parse_json(time_state_array)["state"])
    | extend revision_name = tostring(element)
    | order by timestamp asc
    | extend stateChanged = state != prev(state)
    | extend stateMissingForMoreThanAnHour = timestamp - prev(timestamp) > 75m
    | extend SessionIndex = row_cumsum(iff(stateChanged or stateMissingForMoreThanAnHour, 1, 0))
    | summarize StartTime = min(timestamp), EndTime = max(timestamp) by revision_name, state, SessionIndex
    | project StartTime, EndTime, revision_name, state
    | order by StartTime asc
    | extend EndTime = iff((not(isnull(next(StartTime)))) and next(StartTime) - EndTime < 75m, next(StartTime), EndTime)
    | extend EndTime = iff(StartTime == EndTime, datetime_add('minute', 1, StartTime), EndTime)
)
| project
    StartTime,
    EndTime,
    State = state,
    RevisionName = revision_name,
    HealthStatus = case(
        state contains "Running", "Healthy", "Unhealthy"
    )
| order by StartTime asc
| project StartTime, EndTime, RevisionName, State, HealthStatus
