let local_cappName = "##containerAppName##";
let local_cappResourceGroup = "##resourceGroupName##";
let local_cappSubscription = "##subscriptionId##";
let local_location = "##region##";
let globalFrom = datetime("##fromDate##");
let globalTo = datetime("##toDate##");

let testRegions = cluster('cappstest.westus.kusto.windows.net').database('capps').ContainerAppDBState
| where PreciseTimeStamp between (globalFrom .. globalTo);

All("ContainerAppDBState")
| where PreciseTimeStamp between (globalFrom .. globalTo)
| union testRegions
| where (containerAppName == local_cappName or containerAppsJobName == local_cappName)
      and (isempty(local_cappResourceGroup) or resourceGroup =~ local_cappResourceGroup)
      and (isempty(local_cappSubscription) or subscription =~ local_cappSubscription)
      and (isempty(local_location) or Tenant == local_location)
| summarize arg_max(PreciseTimeStamp, provisioningState) by 
    cappName = iif(isempty(containerAppName), containerAppsJobName, containerAppName),
    type = iif(isempty(containerAppName), "job", "containerApp"),
    cappResourceGroup = resourceGroup,
    cappSubscription = subscription,
    environmentId,
    managedClusterName,    
    createdTimeUtc,
    Region = Tenant,
    workloadProfileType
| project
    Region,
    ContainerAppName=cappName,
    ResourceType=type,
    ResourceGroup=cappResourceGroup,
    Subscription=cappSubscription,
    ManagedEnvironmentId=environmentId,
    managedClusterName,    
    createdTimeUtc,
    provisioningState,
    workloadProfileType
| order by createdTimeUtc desc
| project Region, ContainerAppName, ContainerAppType=ResourceType, ResourceGroupName=ResourceGroup, SubscriptionID=Subscription, ContainerAppEnvironmentID=ManagedEnvironmentId, managedClusterName, CreatedTime=createdTimeUtc, provisioningState, workloadProfileType
