let fromTime = datetime("##fromDate##");
let toTime = datetime("##toDate##");
let managedCluster = "##managedClusterName##";
let nodeList = ContainerAppControllerEvents
| where ['time'] between ( fromTime .. toTime)
| where msg =='Node Heartbeat'
| where EnvironmentName == managedCluster
| where NodeName != "" and NodeName != "virtual-node-legion-linux"
| distinct NodeName;
ContainerAppControllerEvents
| where ['time'] between ( fromTime .. toTime)
| where msg =='Node Heartbeat'
| where EnvironmentName == managedCluster
| where NodeName in (nodeList)
| extend NodeReady = tostring(extract("Ready: (True|False)", 1, NodeStatus))
| extend NodeHeartbeat = iff(NodeReady=="True","Ready","Not Ready")
| project PreciseTimeStamp,NodeName,NodeHeartbeat
| order by NodeName,PreciseTimeStamp asc
| extend SessionIndex = row_cumsum(iff(NodeHeartbeat != prev(NodeHeartbeat), 1, 0))
| extend SessionIndex = strcat(NodeName,"#",row_cumsum(iff(NodeHeartbeat !=  prev(NodeHeartbeat) and NodeName == prev(NodeName), 1, 0)))
| summarize StartTime=min( PreciseTimeStamp), EndTime=max(PreciseTimeStamp) by NodeName,NodeHeartbeat,SessionIndex
| order by NodeName,StartTime asc
| project StartTime, EndTime, NodeName, NodeHeartbeat=NodeHeartbeat
