let fromTime = datetime("##fromDate##");
let endTime = datetime("##toDate##");
let cappSubscription = "##subscriptionId##";
let cappResourceGroup = "##resourceGroupName##";
let queryResourceName = "##resourceName##";
ContainerAppsAdminEvents
| where PreciseTimeStamp between (fromTime .. endTime)
| where EventId == 2
| where statusCode != -1
| where requestMethod != "GET"
| where subscription =~ cappSubscription
| where resourceGroup =~ cappResourceGroup
| where resourceName =~ queryResourceName 
| project PreciseTimeStamp,requestPath,requestMethod,statusCode,requestBody,durationInMilliseconds,env_dt_traceId
