let local_cappName = "##containerAppName##";
let local_cappResourceGroup = "##resourceGroupName##";
let local_cappSubscription = "##subscriptionId##";
let globalFrom = datetime("##fromDate##");
let globalTo = datetime("##toDate##");
ContainerAppDBState
| where PreciseTimeStamp between (globalFrom .. globalTo)
| where containerAppName =~ local_cappName
      and resourceGroup == local_cappResourceGroup
      and subscription == local_cappSubscription
| summarize arg_max(PreciseTimeStamp, provisioningState) by
    cappName = iif(isempty(containerAppName), containerAppsJobName, containerAppName),
    workloadProfileType
| order by PreciseTimeStamp desc
| extend InfraLayer = iff(workloadProfileType == "Consumption", "Legion", "AKS")
| take 1
| project InfraLayer
