let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let containerAppOrJobName = "##containerAppOrJobName##"; 
ContainerAppDBState
| where TIMESTAMP between (queryFrom .. queryTo)
| where containerAppName =~ containerAppOrJobName or containerAppsJobName =~ containerAppOrJobName
| summarize StartTime=min(PreciseTimeStamp),EndTime=max(PreciseTimeStamp) by workloadProfileType
| project  StartTime, EndTime, WorkloadProfileType = workloadProfileType
