let fromDate = datetime("##fromDate##");
let toDate = datetime("##toDate##");
let _subscriptionId = "##subscriptionId##";
let _resourceGroupName = "##resourceGroupName##";
let _sessionPoolName =  "##sessionPoolName##";
let _managedEnvironmentName = "##managedEnvironmentName##";
let _poolGroupName = strcat(_sessionPoolName, "-", _subscriptionId, "-", _resourceGroupName);
let _managedClusterName = toscalar(ManagedEnvironmentDBState
| where PreciseTimeStamp between (fromDate-2h .. toDate)
| where subscription == _subscriptionId and resourceGroup == _resourceGroupName and environmentName == _managedEnvironmentName
| summarize arg_max(PreciseTimeStamp, *)
| distinct managedClusterName);
ActivatorEvents
| where PreciseTimeStamp between (fromDate .. toDate)
| where Tenant == _managedClusterName
| where SessionPoolName == _sessionPoolName or Payload contains _poolGroupName
| extend LogMessage = coalesce(Log, msg)
| where level == "error"
| project PreciseTimeStamp, Message=LogMessage, LogLevel=level, stacktrace, error, RequestUrl=Url, ContainerName=_ContainerName, LegionRCPEndpoint, RequestPayload=Payload, StatusCode, SessionIdentifier, RequestId, SessionPoolName

