let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let regionalMdmAccount = strcat("ContainerAppsShoebox", "##region##");
let metricName = "UsageNanoCores";
let containerAppArmId = "##resourceId##";
let samplingType = 'Max';
let whereClause = strcat("| where containerAppArmId == '", containerAppArmId, "'");
GetSparseMdm(queryFrom, queryTo, regionalMdmAccount, "k4apps-metrics", metricName, "'containerAppArmId'", samplingType, whereClause)
| extend value = column_ifexists("Max",-1)
| project Timestamp = TimestampUtc, CpuUsageNanoCores = value
