let startTime = datetime("##fromDate##");
let endTime = datetime("##toDate##");
let cappSubscription = "##subscriptionId##";
let cappResourceGroup = "##resourceGroupName##";
let cappName = "##containerAppName##";
ContainerAppDBState
| where TIMESTAMP between (startTime .. endTime)
| where subscription == cappSubscription
| where resourceGroup == cappResourceGroup
| where containerAppName == cappName or containerAppsJobName == cappName
| summarize  max(TIMESTAMP) by managedClusterName
| distinct managedClusterName
| join kind=leftouter (ManagedEnvironmentDBState
| where TIMESTAMP between (startTime .. endTime)
| extend EnvironmentType =iff(isLegionEnabled or hasWorkloadProfiles, "V2", "V1")
| summarize  max(TIMESTAMP) by managedClusterName,EnvironmentType,hasCustomerVnetForEnv
) on $left.managedClusterName == $right.managedClusterName
| project-away managedClusterName1,max_TIMESTAMP
| project ManagedClusterName=managedClusterName, EnvironmentType=EnvironmentType, HasCustomerVNet=hasCustomerVnetForEnv
