let fromTime = datetime("##fromDate##");
let toTime = datetime("##toDate##");
let managedClusterName = "##managedClusterName##";
EnvoyFrontEndEvents
| where PreciseTimeStamp between (fromTime .. toTime)
| where EnvironmentName == managedClusterName
| where _ContainerName == "envoy"
| where Log !contains "\"GET /"
| where Log !contains "\"POST /"
//| where Log !contains ' to envoy_controller_cluster closed' // will print if controller was restarted
| extend logtime = substring(Log, 1, 23), logContent = substring(Log, 25)
| project Timestamp=logtime, Role, ContainerGroupName=_ContainerGroupName, logContent
| limit 1000
