let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let capp_name = "##containerAppName##";
let capp_rg = "##resourceGroupName##";
let capp_sub = "##subscriptionId##";
let capp_revision = "##revisionName##";
let managedClusterName = toscalar(GetManagedClusterName(capp_name, capp_rg, capp_sub));    
All("EventProcessorEvents")
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where RevisionName == capp_revision
| where EnvironmentName == managedClusterName
| order by PreciseTimeStamp desc
| project PreciseTimeStamp, RevisionName, Reason, Message=msg
