let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let clusterName = "##managedClusterName##";
let containerAppOrJobName = "##containerAppOrJobName##";
EventProcessorEvents
| where PreciseTimeStamp >= queryFrom and PreciseTimeStamp <= queryTo
| where EnvironmentName =~ clusterName
| where isempty(containerAppOrJobName) or ContainerAppName =~ containerAppOrJobName or JobName =~ containerAppOrJobName
| where Reason == "OOMKilled"
| project PreciseTimeStamp, ManagedClusterName = EnvironmentName, ContainerAppName, RevisionName, ReplicaName, Count, resourceId
| take 100
