let fromTime = datetime("##fromDate##");
let toTime = datetime("##toDate##");
let managedClusterName = "##managedClusterName##";
EnvoyFrontEndEvents
| where PreciseTimeStamp between (fromTime .. toTime)
| where EnvironmentName == managedClusterName
| where _ContainerName == "envoy"
| where Log !contains "\"GET /"
| where Log !contains "\"POST /"
//| where Log !contains ' to envoy_controller_cluster closed' // will print if controller was restarted
| project TimeStamp = substring(Log, 1, 23), NodeName = Role, PodName = _ContainerGroupName, Log = substring(Log, 25)
| limit 1000
