let startTime = datetime("##fromDate##");
let endTime = datetime("##toDate##");
let managedClusterName = "##managedClusterName##";
EnvoyControllerEvents
| where PreciseTimeStamp between (startTime .. endTime)
| where EnvironmentName == managedClusterName
| where isnotempty(Log) or isnotempty( error ) or isnotempty(msg)
| extend LogMessage = coalesce(Log, msg)
| project PreciseTimeStamp,LogMessage, error, NodeName=Role, PodId=_ContainerGroupId, PodName=_ContainerGroupName, ContainerName=_ContainerName, ContainerImage=_ContainerImage, caller
| limit 1000
