let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let managedClusterName = "##managedClusterName##";
let metricName = "##metricName##";
let duration = ##duration##;
let threshold = toreal("##threshold##");

let baseQuery = MetricsEvents
| where PreciseTimeStamp between (queryFrom.. queryTo)
| where EnvironmentName =~ managedClusterName
| where msg == "Metric Output"
| where isnotempty(Value)
| project PreciseTimeStamp, Value, Metric, VMNodeWhereMetricCaptured=Role, PodName;

let sumMetric = baseQuery
| where Metric == strcat(metricName, "_sum")
| summarize totalValues=sum(todouble(Value)) by bin(PreciseTimeStamp, duration), VMNodeWhereMetricCaptured, PodName;

let countMetric = baseQuery
| where Metric == strcat(metricName, "_count")
| summarize totalCount=sum(toint(Value)) by bin(PreciseTimeStamp, duration), VMNodeWhereMetricCaptured, PodName;

sumMetric
| join kind=inner countMetric on PreciseTimeStamp, VMNodeWhereMetricCaptured, PodName
| extend avgValue = (totalValues / totalCount)
| where avgValue > threshold
| project PreciseTimeStamp, avgValue, totalCount, VMNodeWhereMetricCaptured, PodName;
