let globalFrom = datetime("##fromDate##");
let globalTo = datetime("##toDate##");
let local_cappName = "##containerAppName##";
let local_revisionName = "##revisionName##";

EventProcessorEvents
| where PreciseTimeStamp between (globalFrom .. globalTo)
| where ContainerAppName == local_cappName or JobName == local_cappName
| where RevisionName == local_revisionName
| where Reason == "ProbeFailed"
| where Internal = true
| summarize FailureCount = count() by TimeSlot = bin(PreciseTimeStamp, 30m), msg
| project TimeSlot, msg, FailureCount
| order by TimeSlot asc, FailureCount desc
| limit 500
