let cappsSiteName = "##containerAppName##";
let capp_rg = "##resourceGroupName##";
let capp_sub = "##subscriptionId##";
let BT = datetime("##fromDate##");
let ET = datetime("##toDate##");
let cappsClusterName = "##managedClusterName##";
HttpScalerEvents
| where PreciseTimeStamp between (BT .. ET)
| where EnvironmentName == cappsClusterName
| where ScaledObjectName has cappsSiteName or Log has cappsSiteName
| where msg != "Aggregated metrics"
| where msg !has 'the object has been modified; please apply your changes to the latest version and try again'
| take 100
