let cappsSiteName = "##containerAppName##";
let capp_rg = "##resourceGroupName##";
let capp_sub = "##subscriptionId##";
let BT = datetime("##fromDate##");
let ET = datetime("##toDate##");
let cappsClusterName = "##managedClusterName##";
HttpScalerEvents
| where PreciseTimeStamp between (BT .. ET)
| where EnvironmentName == cappsClusterName
| where ScaledObjectName has cappsSiteName or Log has cappsSiteName
| where msg != "Aggregated metrics"
| extend Message = strcat(Log, msg)  
| take 100
| project PreciseTimeStamp, ManagedClusterName=EnvironmentName, ScaledObjectName, Message
