let globalFrom = datetime("##fromDate##");
let globalTo = datetime("##toDate##");
let local_subscriptionId = "##subscriptionId##";
let local_resourceGroup = "##resourceGroupName##";
let local_cappName = "##containerAppName##";
let itemtype = "containerApp";
 
ContainerAppControllerEvents
| where PreciseTimeStamp between (globalFrom .. globalTo)
| extend json = iff(itemtype == "job", JobJson, AppJson)
| where isnotempty(json)
| extend itemName = iff(itemtype == "job", ContainerAppJobName, ContainerAppName)
| where itemName == local_cappName
| where json contains local_subscriptionId and json contains local_resourceGroup and json contains local_cappName
| summarize arg_max(PreciseTimeStamp, json)
| extend data=parse_json(json)
| where data has "probes"
| project PreciseTimeStamp, ContainersSpec=data.spec.template.containers
