let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let capp_name = "##containerAppName##";
let capp_rg = "##resourceGroupName##";
let capp_sub = "##subscriptionId##";
let capp_revision = "##revisionName##";
let managedCluster = "##managedClusterName##";
ContainerAppControllerEvents
| where TIMESTAMP between (queryFrom .. queryTo)
| where Tenant == managedCluster
| where msg == "HPA Heartbeat"
| where ContainerAppName == capp_name
| extend metrics = parse_json(Details).metrics
| mv-expand metric = metrics
| extend metricName = tostring(metric.name)
| extend curr_raw    = todouble(replace("m", "", tostring(metric.currentValue))),
         target_raw  = todouble(replace("m", "", tostring(metric.targetValue)))
| extend current = iif(metric.currentValue  endswith "m", curr_raw   / 1000.0, curr_raw),
         target  = iif(metric.targetValue   endswith "m", target_raw / 1000.0, target_raw)
| extend ScalingResult = iif(current > target * 1.1,  "Scaling out is triggered when the value exceeds the target value, considering tolerance.", iif(current < target * 0.9, "Scaling in may occur when the value exceeds the target value, considering the tolerance.", "No scaling occurs as the value does not exceed the target value, considering tolerance"))
| extend Tolerance = 0.1
| summarize MaxValue = max(current), MinValue = min(current) by metricName, target, ScalingResult
| project MetricName=metricName, MaxValue, MinValue, TargetValue=target, Tolerance=0.1, ScalingResult
