let queryFrom = datetime("##queryFrom##");
let queryTo = datetime("##queryTo##");
let cappName = "##cappName##";
let cappClusterName = "##cappClusterName##";
ContainerAppControllerEvents
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where EnvironmentName == cappClusterName
| where msg == "Container Apps Job Heartbeat"
| extend json = JobJson
| where isnotempty(json)
| extend itemName = ContainerAppJobName
| where itemName == cappName
| where json contains cappName
| summarize Timestamp=min(PreciseTimeStamp) by json
| extend d=parse_json(json)
| project Timestamp, Configuration=d.spec.configuration, Template=d.spec.template, Labels=d.metadata.labels, Status=d.status
| order by Timestamp asc
