let queryFrom = datetime("##queryFrom##");
let queryTo = datetime("##queryTo##");
let managedClusterName = "##managedClusterName##";
let jobExecutionName = "##jobExecutionName##";
ContainerAppControllerEvents
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where EnvironmentName == managedClusterName
| where JobExecutionName == jobExecutionName
| where msg contains "Job Execution Heartbeat"
//| summarize arg_max(PreciseTimeStamp, *) by JobExecutionName
//| where JobExecutionStatus == "Failed"
| extend JobExecutionJsonJson = parse_json(JobExecutionJson)
| extend JobExecutionStatusDetails = JobExecutionJsonJson.status
| project PreciseTimeStamp, JobExecutionName, JobExecutionStatus, JobExecutionStatusDetails