let queryFrom = datetime("##queryFrom##");
let queryTo = datetime("##queryTo##");
let environmentName =  "##managedClusterName##";
let jobExecutionName = "##jobExecutionName##";
EventProcessorEvents
| where PreciseTimeStamp  between (queryFrom .. queryTo)
| where EnvironmentName == environmentName
| where ExecutionName == jobExecutionName
//| where Type != "Normal"
| where Internal == true
| project PreciseTimeStamp, Message=msg, Reason, Count, KubernetsEventType=Type
