let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let clusterName = "##managedClusterName##";
ManagedEnvironmentDBState
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where managedClusterName =~ clusterName
| where chartVersion != ""
| project PreciseTimeStamp,Content=chartVersion
| order by PreciseTimeStamp asc
| extend SessionIndex = row_cumsum(iff(Content != prev(Content), 1, 0))
| summarize StartTime = min(PreciseTimeStamp), EndTime = max(PreciseTimeStamp) by Content, SessionIndex
| project StartTime, EndTime, Content
| order by StartTime asc
| extend EndTime = iff((not(isnull(next(StartTime)))), next(StartTime), EndTime)
| extend EndTime = iif(StartTime == EndTime, datetime_add('minute', 1, StartTime), EndTime)
| where prev(Content) != ""
| project StartTime
