let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let clusterName = "##managedClusterName##";
let revisionName = "##revisionName##";
LegionVKVirtualKubeletEvents
| where TIMESTAMP between (queryFrom .. queryTo)
| where EnvironmentName == clusterName
| where name startswith revisionName or RequestUrl contains revisionName
| where level != "info" or (method!="" and method !contains "GET")
| where msg!="" or ErrorMessage != ""
| project TIMESTAMP,PodName=name,Message=msg,Error=ErrorMessage,Method=method,Reason=PodMessage
