let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let regionalMdmAccount = strcat("ContainerAppsShoebox", "##region##");
let metricName = "##metricName##";
let containerAppArmId = "##containerAppArmId##";
let samplingType = '##samplingType##';
let Threshold = "##threshold##";
let whereClause = strcat("| where containerAppArmId == '", containerAppArmId, "'");
GetSparseMdm(queryFrom, queryTo, regionalMdmAccount, "k4apps-metrics", metricName, "'containerAppArmId'", samplingType, whereClause)
| extend value = column_ifexists("Max",-1)
| summarize maxMemoryPercentage = max(value)
| extend HasMdmData = iif(maxMemoryPercentage>=0,true,false)
| extend ExceededThreshold = iif(maxMemoryPercentage >= toint(Threshold), true,false)
| project HasMdmData,ExceededThreshold
