let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let regionalMdmAccount = strcat("ContainerAppsShoebox", "##region##");
let metricName = "##metricName##";
let containerAppArmId = "##containerAppArmId##";
let whereClause = strcat("| where containerAppArmId == '", containerAppArmId, "'");
GetSparseMdm(queryFrom, queryTo, regionalMdmAccount, "k4apps-metrics", metricName, "'containerAppArmId', 'podName'", "Count", whereClause) 
| extend valueMax = column_ifexists("Max",-1)
| extend valuePodName = column_ifexists("podName","")
| summarize Times=make_list(TimestampUtc), make_list(valueMax) by valuePodName
| extend series_decompose_anomalies(list_valueMax)
| project Times,series_decompose_anomalies_list_valueMax_ad_flag
| extend zipped=zip(Times, series_decompose_anomalies_list_valueMax_ad_flag)
| mv-expand zipped
| extend TimestampUtc = todatetime(zipped[0]), anomalyScore = toint(zipped[1])
| project-away Times, series_decompose_anomalies_list_valueMax_ad_flag, zipped
| where anomalyScore < 0
| distinct TimestampUtc
| take 1000
