let fromTime = datetime("##fromDate##");
let toTime = datetime("##toDate##");
let customerEnvironmentName = "##environmentName##";
let customerResourceGroupName = "##resourceGroupName##";
let customerSubscriptionId = "##subscriptionId##";
ManagedEnvironmentDBState
| where TIMESTAMP between (fromTime .. toTime)
| where subscription =~ customerSubscriptionId and
        resourceGroup =~ customerResourceGroupName and
        environmentName =~ customerEnvironmentName 
| project
    PreciseTimeStamp,
    managedClusterName,
    environmentSubscription = subscription,
    environmentResourceGroup = resourceGroup,
    environmentName,
    environmentProvisioningState,
    managedClusterProvisioningState,
    powerState,
    targetPowerState,
    chartVersionUpgradeErrors,
    managedClusterProvisioningError,
    environmentDeploymentErrors,
    kubernetesVersionUpgradeErrors
| order by PreciseTimeStamp asc
| serialize rn = row_number()
| extend isEnvironmentProvisioningStateChanged = iff(prev(environmentProvisioningState) == environmentProvisioningState, 0, 1)
| extend isManagedClusterProvisioningStateChanged = iff(prev(managedClusterProvisioningState) == managedClusterProvisioningState, 0, 1)
| extend isPowerStateChanged = iff(prev(powerState) == powerState, 0, 1)
| extend isTargetPowerStateChanged = iff(prev(targetPowerState) == targetPowerState, 0, 1)
| extend isChartVersionUpgradeErrorsChanged = iff(prev(chartVersionUpgradeErrors) == chartVersionUpgradeErrors, 0, 1)
| extend isManagedClusterProvisioningErrorChanged = iff(prev(managedClusterProvisioningError) == managedClusterProvisioningError, 0, 1)
| extend isEnvironmentDeploymentErrorsChanged = iff(prev(environmentDeploymentErrors) == environmentDeploymentErrors, 0, 1)
| extend isKubernetesVersionUpgradeErrorsChanged = iff(prev(kubernetesVersionUpgradeErrors) == kubernetesVersionUpgradeErrors, 0, 1)
| where rn == 1
  or isEnvironmentProvisioningStateChanged==1 
  or isManagedClusterProvisioningStateChanged==1 
  or isPowerStateChanged==1
  or isTargetPowerStateChanged==1
  or isChartVersionUpgradeErrorsChanged==1
  or isManagedClusterProvisioningErrorChanged==1
  or isEnvironmentDeploymentErrorsChanged==1
  or isKubernetesVersionUpgradeErrorsChanged==1
| project StartTime=PreciseTimeStamp,managedClusterName,environmentProvisioningState,managedClusterProvisioningState,powerState,targetPowerState,chartVersionUpgradeErrors,managedClusterProvisioningError,environmentDeploymentErrors,kubernetesVersionUpgradeErrors