let globalFrom = datetime("##fromDate##");
let globalTo = datetime("##toDate##");
let local_environmentLocation = "##region##";
let local_environmentName = "##environmentName##";
let local_environmentResourceGroup = "##resourceGroupName##";
let local_environmentSubscription = "##subscriptionId##";
let local_managedClusterName = "##managedClusterName##";
All("ManagedEnvironmentDBState")
| where PreciseTimeStamp between (globalFrom .. globalTo)
| where environmentName =~ local_environmentName
| where isempty(local_environmentResourceGroup) or resourceGroup =~ local_environmentResourceGroup
| where isempty(local_environmentSubscription) or subscription =~ local_environmentSubscription
| where isempty(local_managedClusterName) or managedClusterName =~ local_managedClusterName
| where isempty(local_environmentLocation) or Tenant =~ local_environmentLocation
| summarize arg_max(PreciseTimeStamp, subscription, resourceGroup, environmentName, environmentCreatedTime, environmentProvisioningState, environmentDeploymentErrors, powerState, targetPowerState,
                    isLegionEnabled, isInternal, hasCustomerVnetForEnv,hasCustomerVnetForCluster,hasMaintenanceConfiguration, managedSubscription, managedClusterCreatedTime,managedClusterProvisioningState,  managedClusterProvisioningError,
                    chartVersion, targetChartVersion, chartVersionUpgradeErrors, kubernetesVersion, targetKubernetesVersion, kubernetesVersionUpgradeErrors, hasPrivateEndpoints, tier, customHelmValues) by Tenant, managedClusterName, loadBalancerId
| extend environmentType = case(isLegionEnabled == true, "V2", "V1")
| join kind=inner (GetRegions | project Name, KustoUrl) on $left.Tenant == $right.Name
| project
    Region = Tenant,
    environmentCreatedTime,
    environmentSubscription = subscription,
    environmentResourceGroup = resourceGroup,
    environmentName,
    environmentType,
    isLegionEnabled = tostring(isLegionEnabled),
    isInternal = tostring(isInternal),
    hasCustomerVnetForEnv = tostring(hasCustomerVnetForEnv),
    hasCustomerVnetForCluster = tostring(hasCustomerVnetForCluster),
    hasPrivateEndpoints = tostring(hasPrivateEndpoints),
    hasMaintenanceConfiguration = tostring(hasMaintenanceConfiguration),
    managedClusterCreatedTime,
    managedSubscription,
    managedClusterName,
    customHelmValues,
    tier,
    currentChartVersion = chartVersion,
    targetChartVersion,
    currentKubernetesVersion = kubernetesVersion,
    targetKubernetesVersion,
    loadBalancerResourceUrl=loadBalancerId
