let globalFrom = datetime("##fromDate##");
let globalTo = datetime("##toDate##");
let local_environmentLocation = "##region##";
let local_environmentName = "##environmentName##";
let local_environmentResourceGroup = "##resourceGroupName##";
let local_environmentSubscription = "##subscriptionId##";
ManagedEnvironmentDBState
| where PreciseTimeStamp between (globalFrom .. globalTo)
| where environmentName =~ local_environmentName
| where isempty(local_environmentResourceGroup) or resourceGroup =~ local_environmentResourceGroup
| where isempty(local_environmentSubscription) or subscription =~ local_environmentSubscription
| where isempty(local_environmentLocation) or Tenant =~ local_environmentLocation
| summarize arg_max(PreciseTimeStamp, subscription, resourceGroup, environmentName,  environmentProvisioningState, environmentDeploymentErrors,chartVersionUpgradeErrors, kubernetesVersionUpgradeErrors,powerState, targetPowerState, managedClusterProvisioningState,managedClusterProvisioningError) by Tenant, managedClusterName, loadBalancerId
| project
    environmentSubscription = subscription,
    environmentResourceGroup = resourceGroup,
    environmentName,
    environmentProvisioningState,
    environmentDeploymentErrors,
    managedClusterProvisioningState,
    managedClusterProvisioningError,
    powerState,
    targetPowerState,
    chartVersionUpgradeErrors,
    kubernetesVersionUpgradeErrors
