let globalFrom = datetime("##fromDate##");
let globalTo = datetime("##toDate##");
let local_environmentLocation = "##region##";
let local_environmentName = "##environmentName##";
let local_environmentResourceGroup = "##resourceGroupName##";
let local_environmentSubscription = "##subscriptionId##";
ManagedEnvironmentDBState
| where PreciseTimeStamp between (globalFrom .. globalTo)
| where environmentName =~ local_environmentName
| where isempty(local_environmentResourceGroup) or resourceGroup =~ local_environmentResourceGroup
| where isempty(local_environmentSubscription) or subscription =~ local_environmentSubscription
| where isempty(local_environmentLocation) or Tenant =~ local_environmentLocation
| summarize arg_max(PreciseTimeStamp, subscription, resourceGroup, environmentName, environmentCreatedTime, environmentProvisioningState, environmentDeploymentErrors, powerState, targetPowerState,
                    isLegionEnabled, isInternal, hasCustomerVnetForEnv, hasMaintenanceConfiguration, managedSubscription, managedClusterCreatedTime,managedClusterProvisioningState,  managedClusterProvisioningError,
                    chartVersion, targetChartVersion, chartVersionUpgradeErrors, kubernetesVersion, targetKubernetesVersion, kubernetesVersionUpgradeErrors, hasPrivateEndpoints, tier, customHelmValues) by Tenant, managedClusterName, loadBalancerId
| extend environmentType = case(isLegionEnabled == true, "V2", "V1")
| join kind=inner (GetRegions | project Name, KustoUrl) on $left.Tenant == $right.Name
| project
    Region = Tenant,
    environmentCreatedTime,
    environmentSubscription = subscription,
    environmentResourceGroup = resourceGroup,
    environmentName,
    environmentType,
    environmentProvisioningState,
    environmentDeploymentErrors,
    isLegionEnabled,
    isInternal,
    hasCustomerVnet = tostring(hasCustomerVnetForEnv),
    hasPrivateEndpoints = tostring(hasPrivateEndpoints),
    hasMaintenanceConfiguration = tostring(hasMaintenanceConfiguration),
    managedClusterCreatedTime,
    managedSubscription,
    managedClusterName,
    customHelmValues,
    tier,
    managedClusterProvisioningState,
    managedClusterProvisioningError,
    powerState,
    targetPowerState,
    currentChartVersion = chartVersion,
    targetChartVersion,
    chartVersionUpgradeErrors,
    currentKubernetesVersion = kubernetesVersion,
    targetKubernetesVersion,
    kubernetesVersionUpgradeErrors,
    KustoUrl,
    loadBalancerResourceUrl=loadBalancerId
