let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let regionalMdmAccount = strcat("ContainerAppsShoebox", "##region##");
let metricName = "##metricName##";
let containerAppArmId = "##containerAppArmId##";
let samplingType = '##samplingType##';
let Threshold = "##threshold##";
let whereClause = strcat("| where containerAppArmId == '", containerAppArmId, "'");
GetMdmResult(queryFrom, queryTo, regionalMdmAccount, "k4apps-metrics", metricName, "'containerAppArmId'", samplingType, whereClause)
| where Max >= toint(Threshold)
| summarize rowCount = count()
| project HasData = rowCount > 0
