let fromDate = datetime("##fromDate##");
let toDate = datetime("##toDate##");
let _managedClusterName = "##managedClusterName##";
ContainerAppsAdminEvents
| where TIMESTAMP between (fromDate .. toDate)
| where operationEntityType in ('', 'KubeEnvironment','ManagedCluster')
| where Level <= 3
| where managedClusterName == _managedClusterName
| extend exception = iff(isempty(exception), message, exception)
| summarize arg_max(exception, PreciseTimeStamp, managedClusterName,operationType,operationEntityType) by env_dt_traceId
| summarize FirstSeen=min(PreciseTimeStamp),LastSeen=max(PreciseTimeStamp),count=count() by operationType,operationEntityType,exception
| order by FirstSeen asc
| limit 50
