let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let managedClusterName = "##managedClusterName##";
let podNamePrefix = "##podNamePrefix##";
let podNamespace = "##podNamespace##";
let podStatus= ContainerAppControllerEvents
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where EnvironmentName == managedClusterName
| where msg == 'Pod Heartbeat'
| where PodNamespace == podNamespace
| where PodName contains podNamePrefix
| project PreciseTimeStamp,PodName,PodStatus,NodeName,PodContainerStatus
| extend containers = parse_json(PodContainerStatus)
| mv-expand containers
| extend restartCount= todecimal(containers.restartCount)
| summarize StartTime = min(PreciseTimeStamp),EndTime=max(PreciseTimeStamp),restartCount= max(restartCount) by PodName,PodStatus,NodeName
| project StartTime, EndTime, PodName, NodeName, PodStatus, Health = iff(PodStatus in ("Running","Succeeded"),"Healthy","Degraded"), restartCount;
let podContainerFailures = ContainerAppControllerEvents
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where EnvironmentName == managedClusterName
| where msg == 'Pod Heartbeat'
| where PodNamespace == podNamespace
| where PodName startswith podNamePrefix
| extend podContainer = parse_json(PodContainerStatus)
| mv-expand podContainer
| extend ContainerName = tostring(podContainer.name)
| extend ContainerReady = tostring(podContainer.ready)
| extend ContainerImage = tostring(podContainer.image)
| summarize StartTime = min(PreciseTimeStamp),EndTime=max(PreciseTimeStamp) by PodName, ContainerName, ContainerReady,ContainerImage,NodeName
| where isnotempty( ContainerName)
| extend ContainerState = iff(ContainerReady=="true","Ready","Not Ready")
| where ContainerReady == "false"
| project StartTime,EndTime,PodName,ContainerName,ContainerState,ContainerImage,NodeName;
union podStatus,podContainerFailures
