let fromTime = datetime("##fromDate##");
let toTime = datetime("##toDate##");
let queryManagedCluster = "##managedClusterName##";
PrivateLinkDBState
| where TIMESTAMP between (fromTime-15d .. toTime)
| where managedClusterName == queryManagedCluster
| summarize arg_max(TIMESTAMP,
    frontendVmssName,
    frontendVmssCreatedTime,
    frontendVmssProvisioningState,
    tcpBridgeVersion,
    privateEndpointConnectionName,
    privateEndpointConnectionProxyName,
    privateEndpointId,
    privateEndpointConnectionProvisioningState,
    connectionStatus,
    storageAccountName)
