let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let managedClusterName = "##managedClusterName##";
let podNamePrefix = "##podNamePrefix##";
let podNamespace = "##podNamespace##";
ContainerAppControllerEvents
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where EnvironmentName == managedClusterName
| where msg == 'Pod Heartbeat'
| where PodNamespace == podNamespace
| where PodName contains podNamePrefix
| project PreciseTimeStamp,PodName,PodStatus,NodeName,PodContainerStatus
| summarize StartTime = min(PreciseTimeStamp),EndTime=max(PreciseTimeStamp) by PodName,PodStatus,NodeName
| project StartTime, EndTime, PodName, NodeName, PodStatus, Health = iff(PodStatus in ("Running","Succeeded"),"Healthy","Degraded")
