let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let clusterName = "##managedClusterName##";
let revisionName = "##revisionName##";
SystemLogs
| where PreciseTimeStamp between (queryFrom-1h .. queryTo+1h)
| where ResourceNamespace == clusterName
| where PodName startswith revisionName
| where Operation == 'MarkPodEvicted' or Value contains 'HostShutdown'
| extend OperationMessage = coalesce(Value, Message)
| project PreciseTimeStamp,PodName,OperationName=Operation,Message=OperationMessage 
