let startTime = datetime("##fromDate##");
let endTime = datetime("##toDate##");
let cappRevisionName = "##revisionName##";
let cappName = "##containerAppName##";
let cappRg = "##resourceGroupName##";
let cappSub = "##subscriptionId##";
let appArmId = strcat("/subscriptions/", cappSub, "/resourceGroups/", cappRg, "/providers/Microsoft.App/containerApps/", cappName);
let managedClusterName = toscalar(GetManagedClusterName(cappName, cappRg, cappSub));
// Get Replica Counts
let duration = endTime - startTime;
let bins = datatable(span: timespan, bucket: timespan, mdm_bucket: string) [
    5m, 1m, '1m',
    1d, 1m, '1m',
    2d, 15m, '15m',
    3d, 30m, '30m',
    7d, 1h, '1h'
];
let spans = bins | where duration >= span | top 1 by span desc;
let bucket = coalesce(toscalar(spans | project bucket), 1d);
let mdm_bucket = coalesce(toscalar(spans | project mdm_bucket), '1d');
let genevaAccountName = "ContainerAppsMdm";
let dimension_list = "'containerAppArmId','revisionName'";
let theSchema = datatable (TimestampUtc: datetime, revisionName: string, Max: real) [];
let replicaData = evaluate geneva_metrics_request(
    genevaAccountName,
    strcat(
        @"metricNamespace('k4apps-metrics')",
        @".metric('Replicas')",
        @".dimensions(", dimension_list, ")",
        @".samplingTypes('Max')",
        @"| where containerAppArmId == '", appArmId, "'",
        @"| zoom Max = max(Max) by ", mdm_bucket
    ),
    startTime,
    endTime
)
| union theSchema
| where revisionName == cappRevisionName
| project ReplicaTimestamp = TimestampUtc, ReplicaCount = Max;
// Get Traffic Counts
let trafficData = 
    All("EnvoyFrontEndLogsTable")
    | where PreciseTimeStamp between (startTime .. endTime)
    | where RevisionName == cappRevisionName
    | where EnvironmentName == managedClusterName
    | make-series RequestsCount = count() default = 0 on PreciseTimeStamp in range (startTime, endTime, 5m) by Status_string
    | mv-expand RequestsCount, PreciseTimeStamp
    | project TrafficTimestamp = todatetime(PreciseTimeStamp), Status = Status_string, Requests = toint(RequestsCount);
// Final Join
replicaData
| join kind=fullouter (
    trafficData
) on $left.ReplicaTimestamp == $right.TrafficTimestamp
| project 
    Timestamp = coalesce(ReplicaTimestamp, TrafficTimestamp),
    ReplicaCount,
    Status,
    Requests
| order by Timestamp asc
| where ReplicaCount >0
