let startTime = datetime("##fromDate##");
let endTime = datetime("##toDate##");
let managedClusterName = "##managedClusterName##";
SwiftNetworkingEvents
| where PreciseTimeStamp between (startTime .. endTime)
| where EnvironmentName == managedClusterName
| where _ContainerName == "swift-load-balancer"
| where isnotempty(error) or isnotempty(Log) or isnotempty(msg)
| extend LogMessage = coalesce(Log, msg)
| project PreciseTimeStamp, logger, LogMessage, error, NodeName=Role, PodId=_ContainerGroupId, PodName=_ContainerGroupName, ContainerName=_ContainerName, ContainerImage=_ContainerImage, caller
