let queryFrom = datetime("##queryFrom##");
let queryTo = datetime("##queryTo##");
let jobExecutionName = "##jobExecutionName##";
let managedClusterName = "##managedClusterName##";
LegionVKVirtualKubeletEvents
| where PreciseTimeStamp between(queryFrom .. queryTo)
| where EnvironmentName == managedClusterName
| where level != "info"
| where pod startswith jobExecutionName or msg contains jobExecutionName or error contains jobExecutionName
| summarize by phase, msg, error,  RequestMethod, ResponseHttpStatusCode
| take 1000
