let queryFrom = datetime("##queryFrom##");
let queryTo = datetime("##queryTo##");
let jobExecutionName = "##jobExecutionName##";
let managedClusterName = "##managedClusterName##";
LegionVKVirtualKubeletEvents
| where PreciseTimeStamp between(queryFrom .. queryTo)
| where EnvironmentName == managedClusterName
| where pod startswith jobExecutionName or msg contains jobExecutionName or error contains jobExecutionName
| project PreciseTimeStamp, ManagedClusterName = EnvironmentName, level, pod, phase, msg, RequestMethod, ResponseHttpStatusCode, error, queue, TraceId
| order by PreciseTimeStamp asc
