let queryFrom = datetime("##fromDate##");
let queryTo = datetime("##toDate##");
let capp_name = "##containerAppName##";
let capp_rg = "##resourceGroupName##";
let capp_sub = "##subscriptionId##";
let managedClusterName = toscalar(GetManagedClusterName(capp_name, capp_rg, capp_sub));    
ContainerAppControllerEvents
| where PreciseTimeStamp between (queryFrom .. queryTo)
| where ContainerAppName == capp_name
| where EnvironmentName == managedClusterName
| order by PreciseTimeStamp desc
| summarize arg_max(PreciseTimeStamp, *) by RevisionName
| order by PreciseTimeStamp desc
| extend Name = RevisionName
| extend parsedJson = parse_json(RevisionJson)
| extend WorkloadProfileName = tostring(parsedJson.metadata.labels['k8se.microsoft.com/workloadProfileName'])
| extend WorkloadProfileType = tostring(parsedJson.metadata.labels['k8se.microsoft.com/workloadProfileCategory'])
| extend Namespace = tostring(parsedJson.metadata.namespace)
| extend CreationTimestamp = tostring(parsedJson.metadata.creationTimestamp)
| extend RestartTime = tostring(parsedJson.metadata.annotations['k8se.microsoft.com/restartedAt'])
| extend AppType = tostring(parsedJson.spec.appType)
| extend HttpOptionsEnabled = tobool(parsedJson.spec.httpOptions.enabled)
| extend HttpOptionsExternal = tobool(parsedJson.spec.httpOptions.external)
| extend HttpOptionsPort = toint(parsedJson.spec.httpOptions.port)
| extend Http2Enabled = tobool(parsedJson.spec.httpOptions.http2.enabled)
| extend HttpsOnly = tobool(parsedJson.spec.httpOptions.httpsOnly)
| extend Stopped = tobool(parsedJson.spec.scaleOptions.stopped)
| extend MinReplicaCount = toint(coalesce(parsedJson.spec.scaleOptions.minReplicaCount, 0))
| extend MaxReplicaCount = toint(parsedJson.spec.scaleOptions.maxReplicaCount)
| extend HttpScalingRuleName = tostring(parsedJson.spec.scaleOptions.http.name)
| extend HttpScalingRuleConcurrentRequests = toint(parsedJson.spec.scaleOptions.http.concurrentRequests)
| extend ObservedGeneration = toint(parsedJson.status.observedGeneration)
| extend RevisionProvisioningState = tostring(parsedJson.status.appProvisioningState)
| extend RevisionHealthStatus = tostring(parsedJson.status.appHealthStatus)
| extend RevisionRunningState = tostring(parsedJson.status.appRunningState)
| extend legionRevisionName = iff(WorkloadProfileName has "consumption", Name, "")
| extend WorkloadProfileNameUpdated = iff(isempty(WorkloadProfileName) and isempty(WorkloadProfileType), "V1 Environment", WorkloadProfileName)
| extend AppReadyForTrafficState = tostring(parsedJson.status.appReadyForTrafficState)
| distinct Name, ManagedClusterName = EnvironmentName, ContainerAppName, Namespace, ReadyReplicas, CreationTimestamp, WorkloadProfileNameUpdated, RestartTime, AppType, 
    HttpOptionsEnabled, HttpOptionsExternal, HttpOptionsPort, Http2Enabled, HttpsOnly, Stopped, MinReplicaCount, MaxReplicaCount,
    HttpScalingRuleName, HttpScalingRuleConcurrentRequests, ObservedGeneration, RevisionProvisioningState, RevisionHealthStatus, 
    RevisionRunningState, AppReadyForTrafficState, PreciseTimeStamp, legionRevisionName
