let fromTime = datetime("##fromDate##");
let toTime = datetime("##toDate##");
let resourceName = trim(@"^\s+|\s+$","##resourceName##");
let searchRegin = "##region##";
let searchSubscription = "##subscriptionId##";
let containerAppSearchResult = All("ContainerAppDBState")
| where TIMESTAMP between (fromTime-1d .. toTime)
| where resourceName != ""
| where containerAppName =~ resourceName or containerAppsJobName =~ resourceName
| extend ResourceType = iif(isempty(containerAppName), "ContainerAppsJob", "ContainerApp")
| extend managedEnvironmentResourceGroup = tostring(split(environmentId,"/")[4])
| extend managedEnvironmentName = tostring(split(environmentId,"/")[8])
| summarize arg_max(TIMESTAMP,ResourceType,region=Tenant,subscription,
  containerAppResourceGroup=resourceGroup,
  managedEnvironmentResourceGroup,
  managedEnvironmentName,
  provisioningState,
  workloadProfileType) by containerAppName,containerAppsJobName,managedClusterName
| join kind=inner (All("ManagedEnvironmentDBState")
| where TIMESTAMP between (fromTime-1d .. toTime)
| summarize arg_max(TIMESTAMP,customHelmValues) by managedClusterName
| extend jobsConsumptionV2OnLegion=parse_json(customHelmValues)["jobsConsumptionV2OnLegion"]
| extend consumptionV2OnLegion=parse_json(customHelmValues)["consumptionV2OnLegion"]
| project-away customHelmValues
) on $left.managedClusterName==$right.managedClusterName
| extend IsRunOnLegion = iif(workloadProfileType=="Consumption" and jobsConsumptionV2OnLegion!=false and consumptionV2OnLegion !=false,"True","False");
let environmentSearchResult = All("ManagedEnvironmentDBState")
| where TIMESTAMP between (fromTime-1d .. toTime)
| where resourceName != ""
| where environmentName =~ resourceName or managedClusterName =~ resourceName
| extend ResourceType = iif(managedClusterName =~ resourceName, "ManagedCluster", "ManagedEnvironment")
| summarize arg_max(TIMESTAMP,ResourceType,region=Tenant,subscription,
  managedEnvironmentName=environmentName,
  managedEnvironmentResourceGroup=resourceGroup,
  environmentProvisioningState) by managedClusterName;
let sessionPoolSearchResult = AllSession("SessionPoolDBState")
| where PreciseTimeStamp  between (fromTime-1d .. toTime)
| where resourceName != ""
| where sessionPoolName =~ resourceName
| extend ResourceType = "SessionPool"
| summarize arg_max(TIMESTAMP,ResourceType,region=Tenant,subscription,
  sessionPoolResourceGroup=resourceGroup) by sessionPoolName;
union containerAppSearchResult,environmentSearchResult,sessionPoolSearchResult
| where ResourceType != ""
| where isempty(searchRegin) or region =~ searchRegin
| where isempty(searchSubscription) or subscription =~ searchSubscription
| project ResourceType,region,SubscriptionID=subscription,managedClusterName,managedEnvironmentName,containerAppName,containerAppsJobName,IsRunOnLegion,provisioningState,sessionPoolName,ContainerAppResourceGroupName=containerAppResourceGroup,ManagedEnvironmentResourceGroupName=managedEnvironmentResourceGroup,environmentProvisioningState,sessionPoolResourceGroupName=sessionPoolResourceGroup

