# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
  - member: jennylaw
    role: Maintain
  - member: howang
    role: Maintain
  - member: sanmeht
    role: Maintain
  - member: ruslany
    role: Maintain
  - member: shgup
    role: Maintain
  - member: ellhamai
    role: Maintain
  - member: jijohn
    role: Maintain
  - member: ebcarek
    role: Maintain
  - member: visagarwal
    role: Maintain
  - member: yashnisar
    role: Maintain
# Teams
  - team: antsanchit
    role: Write
  - team: howangdr
    role: Write
  - team: antshekharsg
    role: Write
  - team: srea-devs
    role: Read
  - team: srea-readers
    role: Read
  - team: k4appscore
    role: Write
# Core Identity - SRE Agent External Partners: https://coreidentity.microsoft.com/manage/Entitlement/entitlement/sreagentexte-f1fv
# Each top level Core Identity Group has two subgroups
  - team: crg-sreagentexte-f1fv-reader-4wok
    role: Read
  - team: ccg-sreagentexte-f1fv-reader-bgy1-1
    role: Read
  - team: ccg-sreagentexte-f1fv-reader-tz0s-1
    role: Read
  - team: crg-sreagentexte-f1fv-contributor-y512
    role: Write
  - team: ccg-sreagentexte-f1fv-contributor-dczl-1
    role: Write
  - team: ccg-sreagentexte-f1fv-contributor-up2b-1
    role: Write
  - member: csigs
    role: Write
  - team: srea-ux-devs
    role: Write
