# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
  - member: jennylaw
    role: Maintain
  - member: howang
    role: Maintain
  - member: sanmeht
    role: Maintain
  - member: ruslany
    role: Maintain
  - member: shgup
    role: Maintain
  - member: ellhamai
    role: Maintain
  - member: jijohn
    role: Maintain
  - member: ebcarek
    role: Maintain
  - member: travisharris
    role: Write
  - member: visagarwal
    role: Maintain
  - member: yashnisar
    role: Write
  - member: zhaoziqi
    role: Write
  - member: zhenqxu
    role: Write
  - member: yefuwang
    role: Write
  - member: layliu
    role: Write
  - member: zhenghanzhou
    role: Write
  - member: xiangy
    role: Write
  - member: liuqi
    role: Write
  - member: andimarc
    role: Write
  - member: stpelleg
    role: Write
  - member: nicolaslayne
    role: Write
  - member: yoonaoh
    role: Write
  - member: evtheodo
    role: Write
  - member: tmauldin
    role: Write
  - member: eriwan
    role: Write
  - member: zuh
    role: Write
  - member: hanren
    role: Write
  - team: k4appscore
    role: Read
  - team: antsanchit
    role: Write
  - team: antshekharsg
    role: Write
  - team: srea-devs
    role: Read
  - team: srea-readers
    role: Read
# Core Identity - SRE Agent External Partners: https://coreidentity.microsoft.com/manage/Entitlement/entitlement/sreagentexte-f1fv
# Each top level Core Identity Group has two subgroups
  - team: crg-sreagentexte-f1fv-reader-4wok
    role: Read
  - team: ccg-sreagentexte-f1fv-reader-bgy1-1
    role: Read
  - team: ccg-sreagentexte-f1fv-reader-tz0s-1
    role: Read
  - team: crg-sreagentexte-f1fv-contributor-y512
    role: Write
  - team: ccg-sreagentexte-f1fv-contributor-dczl-1
    role: Write
  - team: ccg-sreagentexte-f1fv-contributor-up2b-1
    role: Write
  - member: csigs
    role: Write
  - team: srea-ux-devs
    role: Write
