<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Gremlin.Net" Version="3.7.3" />
	<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agent.Core\Agent.Core.csproj" />
  </ItemGroup>

</Project>
