<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.ResourceManager.ApiCenter" />
    <PackageReference Include="Azure.ResourceManager.ApiManagement" />
    <PackageReference Include="Azure.Security.KeyVault.Keys" />
    <PackageReference Include="Gremlin.Net" />
    <PackageReference Include="Microsoft.AspNetCore.OData" />
    <PackageReference Include="Microsoft.Azure.Cosmos" />
    <PackageReference Include="Microsoft.Azure.Cosmos.Encryption" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Azure.Search.Documents" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agent.Core\Agent.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agent.Analyzers\Agent.Analyzers.csproj" OutputItemType="Analyzer" />
  </ItemGroup>
</Project>
