<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Agent.Runtime\Agent.Runtime.csproj" />
    <ProjectReference Include="..\Agent.Prometheus\Agent.Prometheus.csproj" />
    <ProjectReference Include="..\Agent.Web\Agent.Web.csproj" />
    <ProjectReference Include="..\Agent.Graph\Agent.Graph.csproj" />
    <ProjectReference Include="..\Agent.Tests.Common\Agent.Tests.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
   <Content Include="TestData\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
   </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Framework\TestAgents\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Framework\TestPrompts\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Plugins\ACA-FirstParty\*.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.test.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData\ToolReplayLogs\chatmessage-format-f41f64f7-d7a3-4061-b42f-33a992aa413e.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TestData\ToolReplayLogs\otel-format-f41f64f7-d7a3-4061-b42f-33a992aa413e.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
