#################################################################################
#                               OneBranch Pipelines                             #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none  # This pipeline should only trigger on pull requests, not on branch pushes

pr:
  autoCancel: true
  drafts: false
  branches:
    include:
    - "*"

# global parameters are configured here and show up in AzDO UI in build queue time. Required for MSBuild and .NET.
# learn more at https://aka.ms/obpipelines/parameters
parameters:
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

variables:
# include common build variables
- template: /.pipelines/templates/Shared.OneBranch.Build.CommonVariables.yaml

- name: RELEASE_NUMBER
  value: $[counter(variables['RELEASE_NUMBER'], 0)]

extends:
  template: /.pipelines/templates/Shared.OneBranch.Build.yaml
  parameters:
    isOfficialBuild: false # Force NonOfficial builds
