<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="Azure.AI.OpenAI" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="System.Threading.RateLimiting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agent.Logging\Agent.Logging.csproj" />
  </ItemGroup>
</Project>
