// ------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All rights reserved.
// ------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;
using Agent.Framework.Skills;
using Microsoft.Extensions.AI;

namespace Agent.Framework;

public abstract class RunResultBase<TContext> where TContext : class
{
    /// <summary>
    /// The original input to the run.
    /// </summary>
    public required List<ChatMessage> Input { get; set; }

    /// <summary>
    /// The new items generated by the run.
    /// </summary>
    public required List<ChatMessage> NewItems { get; set; }

    public required List<ChatResponse> RawResponses { get; set; }

    /// <summary>
    /// The current turn of the run.
    /// </summary>
    public required int CurrentTurn { get; set; }

    /// <summary>
    /// The maximum number of turns the run can take.
    /// </summary>
    public required int MaxTurns { get; set; }

    /// <summary>
    /// The output of the run.
    /// </summary>
    public object? Output { get; set; }

    /// <summary>
    /// The context wrapper for the run.
    /// </summary>
    public required RunContextWrapper<TContext> ContextWrapper { get; set; }

    /// <summary>
    /// The manual tool calls made by the run. These should be executed by the caller, and then the results
    /// passed to `Runner.ResumeFromManualToolsAsync`.
    /// </summary>
    public List<ManualToolCall>? ManualToolCalls { get; set; }

    public abstract Agent<TContext> LastAgent { get; }

    public required Trajectory Trajectory { get; init; }

    public required SkillList ActiveSkills { get; init; }
}

public class RunResult<TContext>(Agent<TContext> agent) : RunResultBase<TContext> where TContext : class
{
    public override Agent<TContext> LastAgent { get; } = agent;

    internal Agent<TContext>? OldAgent { get; private set; } = null;

    [MemberNotNullWhen(true, nameof(OldAgent))]
    internal bool AgentChanged()
    {
        return OldAgent != null && OldAgent.Name != LastAgent.Name;
    }
    public bool IsCancellationRequested { get; set; } = false;
    public RunResult<TContext> WithNewAgent(Agent<TContext> newAgent)
    {
        return new RunResult<TContext>(newAgent)
        {
            Input = Input,
            NewItems = NewItems,
            RawResponses = RawResponses,
            CurrentTurn = CurrentTurn,
            MaxTurns = MaxTurns,
            Output = Output,
            ContextWrapper = ContextWrapper,
            ManualToolCalls = ManualToolCalls,
            Trajectory = Trajectory,
            OldAgent = this.LastAgent,
            ActiveSkills = ActiveSkills
        };
    }
}

public class RunResultStreaming<TContext> : RunResultBase<TContext> where TContext : class
{
    public required Agent<TContext> CurrentAgent { get; set; }

    public bool IsComplete { get; set; } = false;

    public required IAsyncEnumerable<ChatResponseUpdate> StreamingResponse { get; set; }

    public override Agent<TContext> LastAgent => CurrentAgent;
}

public class ManualToolCall
{
    public required FunctionCallContent FunctionCall { get; set; }
    public required AIFunction Tool { get; set; }
    public required ChatMessage OriginalMessage { get; set; }
}

public class ManualToolCallResult
{
    public required FunctionCallContent FunctionCall { get; set; }
    public required object? Output { get; set; }
}

public class TurnLimitReachedException<TContext>(
    string message,
    RunResult<TContext> runResult
) : Exception(message) where TContext : class
{
    public RunResult<TContext> RunResult { get; } = runResult;
}
