// ------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All rights reserved.
// ------------------------------------------------------------

using System.Text;
using System.Text.Json;
using Microsoft.Extensions.AI;

namespace Agent.Framework;

public static class Summarizer
{
    public static async Task<string> SummarizeUserTrajectoryAsync(
       IChatClient chatClient,
       IReadOnlyList<ChatMessage> userTrajectory)
    {
        var lastUserMessageIndex = -1;
        var curIndex = 0;
        foreach (var message in userTrajectory)
        {
            if (message.Role == ChatRole.User)
            {
                lastUserMessageIndex = curIndex;
            }
            curIndex++;
        }

        if (lastUserMessageIndex == -1)
        {
            return "No user messages to summarize.";
        }
        else if (lastUserMessageIndex == 0)
        {
            return ExtractUserQuestion(userTrajectory[0].Text);
        }

        var sb = new StringBuilder();
        var messages = userTrajectory
            .Take(lastUserMessageIndex + 1)
            .Where(m => m.Role == ChatRole.User || m.Role == ChatRole.Assistant)
            .SelectMany(m => m.Contents.OfType<TextContent>()
                .Where(c => !c.Text.Contains("overall_assessment", StringComparison.OrdinalIgnoreCase))
                .Select(c => (m.Role, c.Text)))
            .ToList();

        foreach (var message in messages)
        {
            sb.AppendLine($"Role: {message.Role}");

            if (message.Role == ChatRole.Assistant)
            {
                Dictionary<string, string>? op = null;
                try
                {
                    op = JsonSerializer.Deserialize<Dictionary<string, string>>(message.Text);
                }
                catch { }
                if (op is not null
                    && op.TryGetValue("notifyUserMessage", out var text))
                {
                    sb.AppendLine(text);
                    sb.AppendLine();
                }
                else
                {
                    sb.AppendLine(message.Text);
                    sb.AppendLine();
                }
            }
            else if (message.Role == ChatRole.User)
            {
                sb.AppendLine(ExtractUserQuestion(message.Text));
                sb.AppendLine();
            }
        }

        var conversation = sb.ToString();
        var conversationMessage = $"Following is the conversation whose intent you need to extract:\n\n{conversation}";

        var summarizeMessages = new List<ChatMessage>
        {
            new(ChatRole.System,UserTrajectorySummarizerPrompt),
            new(ChatRole.User, conversationMessage)
        };

        var response = await chatClient.GetResponseAsync(summarizeMessages, new ChatOptions
        {
            Temperature = 0.0f,
            ToolMode = ChatToolMode.None,
            ResponseFormat = ChatResponseFormat.Text,
        });

        return response.Text;
    }

    private const string Marker = "User question goes below:";

    private static string ExtractUserQuestion(string text)
    {
        return text.IndexOf(Marker, StringComparison.OrdinalIgnoreCase) is var i && i >= 0
            ? text[(i + Marker.Length)..].Trim()
            : text;
    }

    public static async Task<string> SummarizeActorTrajectoryAsync(
        string userQuery,
        string trajectory,
        IChatClient chatClient)
    {
        var summarizerPrompt = TrajectorySummarizerPrompt
            .Replace("{{userQuery}}", userQuery);

        var summarizerChat = new List<ChatMessage>
        {
            new(ChatRole.System, summarizerPrompt),
            new(ChatRole.User, trajectory),
        };

        var summarizerChatOptions = new ChatOptions
        {
            ToolMode = ChatToolMode.None,
            Temperature = 0,
            ResponseFormat = ChatResponseFormat.Text,
        };

        var trajectorySummary = await chatClient.GetResponseAsync(summarizerChat, summarizerChatOptions);

        return trajectorySummary.Text;
    }

    public const string TrajectorySummarizerPrompt = """
    You are an expert at analyzing and summarizing AI agent interactions. Your task is to create comprehensive summaries of agent trajectories that capture the complete problem-solving journey.

    ## Input Format
    You will receive agent trajectory documents containing:
    - Agent conversations with users
    - Tool calls and their results
    - Agent reasoning and observations
    - Final conclusions and recommendations

    ## Output Requirements

    Create a structured summary in the following format:

    ```markdown
    ## 🎯 **Objective & Plan**
    **Objective:**
    [Detailed objective as understood by agent: 1 sentence]

    **Strategic Approach:**
    [Plan generated by agent: numbered list of the steps]

    ## 🔧 **Tool Execution Sequence**

    ### Phase 1: [Phase Name]
    **Tool Call 1:** [Tool Name]
    - **Parameters:** [Full parameter details]
    - **Purpose:** [Why this tool was chosen: 1 sentence]

    **Results & Observations:**
    - **Key Findings:** [What was discovered: 1 sentence]
    - **Agent Analysis:** [How agent interpreted results: 1-2 sentence]
    - **Decision Impact:** [How this influenced next steps: 1 sentence]

    [Repeat for each tool call...]

    ## 📈 **Key Insights & Conclusions**
    - **Agent conclusion:** [Summary answer to user query: 1-2 sentence]
    ```

    ## Quality Guidelines

    ### Be Comprehensive
    - Don't skip tool calls or reasoning steps
    - Include both successful and failed attempts
    - Capture iterative refinements and course corrections

    ### Maintain Chronological Flow
    - Present events in the order they occurred
    - Show how each step built upon previous findings
    - Highlight decision points and branching logic

    ### Technical Precision
    - Include exact tool parameters and results
    - Preserve technical terminology and specifics
    - Don't summarize away important technical details

    ONLY MENTION THINGS DIRECTLY PRESENT IN THE TRAJECTORY. DO NOT ADD ANY INFORMATION THAT YOU "INFERRED" FROM IT.

    Generate summaries that would allow another agent or human to:
    1. Understand the complete problem-solving approach
    2. Reproduce the investigation methodology
    3. Learn from both successes and failures

    Focus on creating summaries that are comprehensive, concise and precise.

    Following is the agent trajectory for user query: {{userQuery}}
    """;

    private const string UserTrajectorySummarizerPrompt =
    """
    You are an expert conversation analyst.

    Goal
    Summarize** only the user's current intent** in an ongoing, multi-turn chat between a User and an Assistant.
    - Ignore earlier intents that have been fulfilled, abandoned, or superseded.
    - Include any refinements or follow-ups that the user is still pursuing.
    - Use earlier dialogue only to resolve pronouns or context needed to state the latest intent clearly.
    - Express the intent in one concise sentence (≤ 25 words) that starts with a verb(e.g., “Get status of …”, “Show 5xx error trend …”, etc.).

    Example:
    Role: User
    What all apps do you manage?
     → Intent: Get the list of managed apps.

    Role: Assistant
    App A, App B, Cosmos DB.

    Role: User
    What is status of App A?
     → Intent: Get the current status of App A.

    Role: Assistant
    App A is healthy.Which metric would you like to see?

    Role: User
    Show me 5xx errors.
     → Intent: Show the 5xx-error metric for App A.

    Role: Assistant
    (hands back a 5xx-error chart)

    Role: User
    How about Cosmos?
     → Intent: Get the status/metrics for Cosmos DB.
    """;
}
