// ------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All rights reserved.
// ------------------------------------------------------------

using Microsoft.Extensions.AI;

namespace Agent.Framework;

public static class Summarizer
{
    public static async Task<string> SummarizeUserMessagesAsync(
        IChatClient chatClient,
        IReadOnlyList<ChatMessage> messages)
    {
        if (messages == null || !messages.Any())
        {
            return "No messages to summarize.";
        }

        var userMessages = messages.Where(m => m.Role != ChatRole.System && m.Role != ChatRole.Tool)
            .Select(m => new ChatMessage(m.Role,
                m.Contents.OfType<TextContent>()
                    .Where(c => !(c.Text.Contains("overall_assessment", StringComparison.OrdinalIgnoreCase) &&
                               c.Text.Contains("summary_advice", StringComparison.OrdinalIgnoreCase)))
                    .ToArray()))
            .Where(m => m.Contents.Any())
            .ToList();

        if (userMessages.Count == 0)
        {
            return "No user messages to summarize.";
        }
        if (userMessages.Count == 1)
        {
            return string.Join(" ", userMessages.First().Contents.OfType<TextContent>().Select(c => c.Text));
        }

        var conversationText = string.Join("\n", userMessages.Select(m =>
            $"{m.Role}: {string.Join(" ", m.Contents.OfType<TextContent>().Select(c => c.Text))}"));

        var summarizePrompt = $@"Analyze the following conversation and create a summary written from the user's perspective.
Write as if you are the user describing what you want to accomplish. Use first-person language (""I want..."", ""I need..."", ""My goal is..."").

Focus on:
- What I am trying to accomplish
- The main problem or task I need help with
- Key requirements or constraints I have mentioned
- Expected outcomes or goals I want to achieve

Provide a clear, concise summary written as the user's request:

{conversationText}";

        var summarizeMessages = new List<ChatMessage>
        {
            new ChatMessage(ChatRole.System, @"You are tasked with summarizing conversations from the user's perspective.
Your output should be written as if the user themselves is describing their request or problem.
Use first-person language and capture their intent, needs, and goals clearly and concisely.
The summary should sound like the user speaking directly about what they want to accomplish."),
            new ChatMessage(ChatRole.User, summarizePrompt)
        };

        var response = await chatClient.GetResponseAsync(summarizeMessages, new ChatOptions
        {
            Temperature = 0.3f,
            ToolMode = ChatToolMode.None,
            ResponseFormat = ChatResponseFormat.Text,
        });

        // fallback to conversation text if no summary is generated
        return response.Messages.LastOrDefault()?.Contents.OfType<TextContent>().FirstOrDefault()?.Text
               ?? conversationText;
    }

    public static async Task<string> SummarizeActorTrajectoryAsync(
        string userQuery,
        string trajectory,
        IChatClient chatClient)
    {
        var summarizerPrompt = TrajectorySummarizerPrompt
            .Replace("{{userQuery}}", userQuery);

        var summarizerChat = new List<ChatMessage>
        {
            new(ChatRole.System, summarizerPrompt),
            new(ChatRole.User, trajectory),
        };

        var summarizerChatOptions = new ChatOptions
        {
            ToolMode = ChatToolMode.None,
            Temperature = 0,
            ResponseFormat = ChatResponseFormat.Text,
        };

        var trajectorySummary = await chatClient.GetResponseAsync(summarizerChat, summarizerChatOptions);

        return trajectorySummary.Text;
    }

    public const string TrajectorySummarizerPrompt = """
    You are an expert at analyzing and summarizing AI agent interactions. Your task is to create comprehensive summaries of agent trajectories that capture the complete problem-solving journey.

    ## Input Format
    You will receive agent trajectory documents containing:
    - Agent conversations with users
    - Tool calls and their results
    - Agent reasoning and observations
    - Final conclusions and recommendations

    ## Output Requirements

    Create a structured summary in the following format:

    ```markdown
    ## 🎯 **Objective & Plan**
    **Objective:** 
    [Detailed objective as understood by agent: 1 sentence]

    **Strategic Approach:**
    [Plan generated by agent: numbered list of the steps]

    ## 🔧 **Tool Execution Sequence**

    ### Phase 1: [Phase Name]
    **Tool Call 1:** [Tool Name]
    - **Parameters:** [Full parameter details]
    - **Purpose:** [Why this tool was chosen: 1 sentence]

    **Results & Observations:**
    - **Key Findings:** [What was discovered: 1 sentence]
    - **Agent Analysis:** [How agent interpreted results: 1-2 sentence]
    - **Decision Impact:** [How this influenced next steps: 1 sentence]

    [Repeat for each tool call...]

    ## 📈 **Key Insights & Conclusions**
    - **Agent conclusion:** [Summary answer to user query: 1-2 sentence]
    ```

    ## Quality Guidelines

    ### Be Comprehensive
    - Don't skip tool calls or reasoning steps
    - Include both successful and failed attempts
    - Capture iterative refinements and course corrections

    ### Maintain Chronological Flow
    - Present events in the order they occurred
    - Show how each step built upon previous findings
    - Highlight decision points and branching logic

    ### Technical Precision
    - Include exact tool parameters and results
    - Preserve technical terminology and specifics
    - Don't summarize away important technical details

    ONLY MENTION THINGS DIRECTLY PRESENT IN THE TRAJECTORY. DO NOT ADD ANY INFORMATION THAT YOU "INFERRED" FROM IT.

    Generate summaries that would allow another agent or human to:
    1. Understand the complete problem-solving approach
    2. Reproduce the investigation methodology
    3. Learn from both successes and failures

    Focus on creating summaries that are comprehensive, concise and precise.

    Following is the agent trajectory for user query: {{userQuery}}
    """;
}
