let _startTime = datetime("##startTime##");
let _endTime = datetime("##endTime##");
let _siteName = "##siteName##";
let _eventPrimaryStampName = "##eventPrimaryStampName##";
let _functionName = "##functionName##";
FunctionsLogs
| where PreciseTimeStamp between (_startTime .. _endTime)
| where AppName =~ _siteName
| where EventPrimaryStampName == _eventPrimaryStampName
| where not(Summary startswith "Ping Status" or Summary startswith "[HostMonitor" or Summary startswith "[channel]")
| where FunctionName == _functionName
| where EventName == "BlobDoesNotMatchPattern"
| parse Summary with * "it does not match the pattern '" Pattern "'"
| extend containerName = substring(Pattern, 0, indexof(Pattern, "/")), blobPattern = substring(Pattern, indexof(Pattern, "/") + 1)
| project PreciseTimeStamp, EventIpAddress, Pattern, containerName, blobPattern, EventPrimaryStampName
| take 1
