// ------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All rights reserved.
// ------------------------------------------------------------

using System.ComponentModel;
using Agent.Core.Models;
using Agent.Framework;
using Agent.Plugins.Interface;

namespace Agent.Plugins;

[AgentToolPlugin(Category = ToolCategories.Utility)]
public class CodeInterpreterPluginDefinition
{
    private readonly ICodeInterpreterPlugin _plugin;

    public CodeInterpreterPluginDefinition(ICodeInterpreterPlugin plugin)
    {
        _plugin = plugin;
    }

    [Description(@"Execute a safe Python snippet inside an isolated ACA code interpreter session.
Safety:
- Outbound network & process spawning are blocked by static validation (no requests/httpx/urllib/subprocess/os.system/etc)
- Use ONLY for local data transformation, math, simple charts (if libs preinstalled), text formatting.
File handling:
- Files saved to /mnt/data/ are automatically retrieved and returned as markdown links
- Images (matplotlib, seaborn, PIL outputs) return as ![filename](link) for inline display
- Data files, documents, and other outputs return as [Download filename](link)
- Supports comprehensive file types: images, data formats, documents, archives, scientific data
Returns stdout/stderr (truncated) plus auto-retrieved files as ready-to-use markdown links.
Examples:
- Calculate fibonacci numbers and save results to CSV
- Create matplotlib visualizations and save as PNG/SVG
- Generate data analysis reports in multiple formats
- Process datasets and export to Excel, JSON, or HDF5
Avoid: web calls, installing packages, spawning processes.")]
    [AgentTool(ToolMode.Manual)]
    public Task<string> ExecutePythonSnippetAsync(
        [Description("Python code to execute (<=20k chars, no network/process operations)")] string pythonCode,
        [Description("Timeout in seconds (default 120, max 900)")] int timeoutSeconds = 120)
        => _plugin.ExecutePythonSnippetAsync(pythonCode, Math.Clamp(timeoutSeconds, 5, 900));

    [Description(@"Generate a PDF report by executing Python code that writes a PDF file.
Safety & Workflow:
0. Script should save file in /mnt/data/<filename>
1. Your code MUST write the PDF to the provided expectedOutputFilename path. Should refer to the same path as script: /mnt/data/<filename>
2. No external network, package installation, or process spawning allowed.
3. Tool returns ONLY a status message with a markdown download link in format [Link Text](/api/files/<filename>).
Examples:
- Produce a simple PDF summary with text.
Tip: Use reportlab if available, otherwise craft a minimal PDF manually.
Return format: Returns success message with markdown link like: '✅ PDF report generated successfully. Download: [Download report.pdf](/api/files/report.pdf)'")]
    [AgentTool(ToolMode.Manual)]
    public Task<string> GeneratePdfReportAsync(
        [Description("Python code producing the PDF (no network/process operations)")] string pythonCode,
        [Description("Path inside session for produced PDF, e.g. 'report.pdf'")] string expectedOutputFilename,
        [Description("Local filename to save as (e.g. 'daily_summary.pdf')")] string saveAsFilename,
        [Description("Timeout in seconds (default 180, max 900)")] int timeoutSeconds = 180)
        => _plugin.GeneratePdfReportAsync(pythonCode, expectedOutputFilename, saveAsFilename, Math.Clamp(timeoutSeconds, 5, 900));

    [Description(@"List all files in the current code interpreter session's /mnt/data directory.
Useful for:
- Discovering what files were generated by previous Python executions
- Checking available data files before processing
- Verifying output files were created successfully
Returns JSON array with file metadata (name, size, modified timestamp).")]
    [AgentTool(ToolMode.Manual)]
    public Task<string> ListSessionFilesAsync()
        => _plugin.ListSessionFilesAsync();

    [Description(@"Download and retrieve a file from the code interpreter session's /mnt/data directory.
Use cases:
- Retrieve generated visualizations (matplotlib, seaborn, plotly outputs) for inline display
- Download data analysis results (CSV, Excel, JSON, HDF5, pickle files)
- Get reports and documents (PDF, HTML, Markdown, Office documents)
- Access code files, notebooks, and scientific data formats
- Retrieve any file type commonly produced by Python data science libraries
Return format:
- For images: Returns markdown for inline rendering (![alt](link)) plus download link ([Link Text](link))
- For other files: Returns markdown download link in format [Link Text](/api/files/<filename>)
Supported file types: Images (PNG, JPG, GIF, SVG, WebP, BMP, TIFF, EPS), Data (CSV, TSV, Excel, JSON, XML, YAML, HDF5, NetCDF, pickle), Documents (PDF, HTML, MD, Office formats), Code (PY, IPYNB, R, SQL), Archives (ZIP, TAR, GZ), and more.
The file is saved locally and made available via /api/files endpoint. All responses include ready-to-use markdown links.")]
    [AgentTool(ToolMode.Manual)]
    public Task<string> GetSessionFileAsync(
        [Description("Filename in session /mnt/data (e.g. 'chart.png', 'output.csv')")] string filename,
        [Description("Local filename to save as (e.g. 'analysis_chart.png')")] string saveAsFilename)
        => _plugin.GetSessionFileAsync(filename, saveAsFilename);
}
