import { defineMessages } from 'react-intl';

export const PortalResources = defineMessages({
    azureSreAgents: {
        defaultMessage: 'Azure SRE Agents',
        id: 'He4/qi',
    },
    azureSreAgent: { defaultMessage: 'Azure SRE Agent', id: 'Erci0g' },
    azureSreAgentsPreview: { defaultMessage: 'Azure SRE Agents (Preview)', id: 'Q5mdr7' },
    previewCapitalized: { defaultMessage: 'PREVIEW', id: 'Isedjj' },
    add: { defaultMessage: 'Add', id: '2/2yg+' },
    agents: { defaultMessage: 'Agents', id: 'GBnvl1' },
    invalidUrl: { defaultMessage: 'Must be a valid URL', id: '48WMIb' },
    learnMore: { defaultMessage: 'Learn more', id: 'TdTXXf' },
    externalAgents: { defaultMessage: 'External agents', id: 'hNjyCX' },
    agentName: { defaultMessage: 'Agent name', id: 'ctcA0c' },
    docs: { defaultMessage: 'Docs', id: '/6/sPX' },
    enterName: { defaultMessage: 'Enter name', id: 'OJ2u8k' },
    subscription: { defaultMessage: 'Subscription', id: 'R/6nsx' },
    resourceGroup: { defaultMessage: 'Resource group', id: '+uAdUZ' },
    agentPermissions: { defaultMessage: 'Agent permissions', id: 'qGXY+e' },
    back: { defaultMessage: 'Back', id: 'cyR7Kh' },
    basics: { defaultMessage: 'Basics', id: 'itC9lG' },
    next: { defaultMessage: 'Next', id: '9+Ddtu' },
    cancel: { defaultMessage: 'Cancel', id: '47FYwb' },
    create: { defaultMessage: 'Create', id: 'VzzYJk' },
    createNew: { defaultMessage: 'Create new', id: '5WK7jL' },
    filterItems: { defaultMessage: 'Filter items...', id: 'DdD2hE' },
    signOut: { defaultMessage: 'Sign out', id: 'xXbJso' },
    signInWithDifferentAccount: { defaultMessage: 'Sign in with a different account', id: 'oHGFwy' },
    signIn: { defaultMessage: 'Sign in', id: 'SQJto2' },
    signInAgain: { defaultMessage: 'Sign in again', id: 'scfgdM' },
    sessionExpired: { defaultMessage: 'Session expired', id: '3OGyhq' },
    sessionExpiredMessage: {
        defaultMessage: 'Your session has expired. Please sign in again to continue.',
        id: 'ZXiFgI',
    },
    chatWithAgent: { defaultMessage: 'Chat with agent', id: 'arLfuy' },
    close: { defaultMessage: 'Close', id: 'rbrahO' },
    createYourFirstAgent: { defaultMessage: 'Create your first Azure SRE Agent', id: 'H/i1A+' },
    createYourFirstAgentSubtext: {
        defaultMessage:
            'Azure SRE Agents reduce site reliability costs by proactively identifying issues, automating tasks, and preventing downtime.',
        id: 'TleXgd',
    },
    createAgent: { defaultMessage: 'Create agent', id: 'UrGI9K' },
    viewPopularSkills: { defaultMessage: 'View popular skills', id: 'Ch3IdZ' },
    settings: { defaultMessage: 'Settings', id: 'D3idYv' },
    portalFeedback: { defaultMessage: 'Portal feedback', id: '2GuZPR' },
    feedbackSubmitted: { defaultMessage: 'Thank you for your feedback!', id: 'Nrc9ba' },
    feedbackPlaceholder: { defaultMessage: 'Share any thoughts, issues, or other feedback about the portal...', id: 'DJ9GSQ' },
    positive: { defaultMessage: 'Positive', id: 'dHVUaP' },
    negative: { defaultMessage: 'Negative', id: 'kVQ1fo' },
    submit: { defaultMessage: 'Submit', id: 'wSZR47' },
    themes: { defaultMessage: 'Themes', id: 'Avsnjl' },
    system: { defaultMessage: 'System', id: '+CwN9C' },
    light: { defaultMessage: 'Light', id: '3cc4Ct' },
    dark: { defaultMessage: 'Dark', id: 'tOdNiY' },
    language: { defaultMessage: 'Language', id: 'y1Z3or' },
    expandNavigation: { defaultMessage: 'Expand navigation', id: '3wVEAO' },
    collapseNavigation: { defaultMessage: 'Collapse navigation', id: 'IoApza' },
    defaultSelectedSubscriptions: { defaultMessage: 'Default selected subscriptions', id: 'BMjugG' },
    selectSubscriptions: { defaultMessage: 'Select subscriptions...', id: 'E7zWqc' },
    subscriptionsSelected: {
        defaultMessage: '{count, plural, one {# subscription} other {# subscriptions}}',
        id: 'OZJBlx',
    },
    reduceSiteReliabilityExpenses: {
        defaultMessage: 'Reduce site reliability expenses with Azure SRE Agents',
        id: 's7mQCK',
    },
    reduceSiteReliabilityExpensesPreview: {
        defaultMessage: 'Reduce site reliability expenses with Azure SRE Agents (Preview)',
        id: 'WBciDp',
    },
    reduceSiteReliabilityExpensesDescription: {
        defaultMessage:
            'Azure SRE Agents reduce site reliability costs by proactively identifying issues, automating tasks, and preventing downtime.',
        id: 'TleXgd',
    },
    review: { defaultMessage: 'Review', id: 'R+J5ox' },
    tryAzureForFree: { defaultMessage: 'Try Azure for free', id: 'wCtBb6' },
    exploreAgentSkills: { defaultMessage: 'Explore agent skills', id: 'i50Kb0' },
    privacyAndCookies: { defaultMessage: 'Privacy & cookies', id: 'DdnNXo' },
    termsAndConditions: { defaultMessage: 'Terms & conditions', id: 'bPyOFk' },
    trademarks: { defaultMessage: 'Trademarks', id: 'I6cq17' },
    notifications: { defaultMessage: 'Notifications', id: 'NAidKb' },
    dismissAll: { defaultMessage: 'Dismiss all', id: 'eHNXXp' },
    dismissCompleted: { defaultMessage: 'Dismiss completed', id: 'P/DTRU' },
    noNotifications: { defaultMessage: 'No notifications', id: 'fpexn2' },
    noNotificationsDescription: {
        defaultMessage: 'Notifications will appear here when actions are performed',
        id: 'W4H4Z9',
    },
    getMoreInfo: { defaultMessage: 'Get more info', id: 'TB6bkn' },
    dismiss: { defaultMessage: 'Dismiss', id: 'TDaF6J' },
    justNow: { defaultMessage: 'Just now', id: 'bxv59V' },
    secondsAgo: {
        defaultMessage: '{count, plural, one {# second ago} other {# seconds ago}}',
        id: 'sYoT7W',
    },
    unexpectedErrorOccurred: { defaultMessage: 'An unexpected error occurred', id: '3IKub9' },
    backToHome: { defaultMessage: 'Back to home', id: 'aIRWQB' },
    minutesAgo: {
        defaultMessage: '{count, plural, one {# minute ago} other {# minutes ago}}',
        id: 'aLBTVj',
    },
    hoursAgo: {
        defaultMessage: '{count, plural, one {# hour ago} other {# hours ago}}',
        id: 'LupnQU',
    },
    daysAgo: {
        defaultMessage: '{count, plural, one {# day ago} other {# days ago}}',
        id: '8OCpdQ',
    },
    none: { defaultMessage: 'None', id: '450Fty' },
    agent: { defaultMessage: 'Agent', id: 'QGVI63' },
    uri: { defaultMessage: 'URI', id: 'UzV6T0' },
    displayName: { defaultMessage: 'Display name', id: 'dOQCL8' },
    searchAgentLinks: { defaultMessage: 'Search agent links', id: 'OeeWFV' },
    agentLinks: { defaultMessage: 'Agent links', id: 'Z9MqPb' },
    addAgentLink: { defaultMessage: 'Add agent link', id: 'PGgs7P' },
    deleteAgentLinks: { defaultMessage: 'Delete agent links', id: 'cP6uU4' },
    deleteAgentLink: { defaultMessage: 'Delete agent link', id: 'mmngrs' },
    confirmDeleteAgentLinks: {
        defaultMessage: 'Are you sure you want to delete the selected agent links?',
        id: '7ynO3Y',
    },
    confirmDeleteAgentLink: {
        defaultMessage: 'Are you sure you want to delete "{name}"?',
        id: 'nKJuTy',
    },
    delete: { defaultMessage: 'Delete', id: 'K3r6DQ' },
    edit: { defaultMessage: 'Edit', id: 'wEQDC6' },
    update: { defaultMessage: 'Update', id: 'BWpuKl' },
    type: { defaultMessage: 'Type', id: '+U6ozc' },
    yes: { defaultMessage: 'Yes', id: 'a5msuh' },
    no: { defaultMessage: 'No', id: 'oUWADl' },
    uriMustStartWith: {
        defaultMessage: 'URI must start with {value}',
        id: 'FMhqpw',
    },
    uriMustEndWith: {
        defaultMessage: 'URI must end with {value}',
        id: 'srMOPI',
    },
    uriMustEndWithAllowedDomain: {
        defaultMessage: 'URI must end with ".azuresre.ai" or ".sre.azure.com"',
        id: 'nQUeKZ',
    },
    uriNotUnique: {
        defaultMessage: 'This URI already exists',
        id: 'gicrFI',
    },
    name: { defaultMessage: 'Name', id: 'HAlOn1' },
    search: { defaultMessage: 'Search', id: 'xmcVZ0' },
    region: { defaultMessage: 'Region', id: 'lnaWo/' },
    requestError: { defaultMessage: 'Request error', id: 'UQUIP7' },
    deleteAgents: { defaultMessage: 'Delete agents', id: 'le4UM7' },
    deleteAgentTitle: { defaultMessage: 'Delete agent', id: 'FKlXAd' },
    deleteAgentsTitle: { defaultMessage: 'Delete agents', id: 'le4UM7' },
    deleteAgentContent: { defaultMessage: 'Are you sure you want to delete "{name}"?', id: 'nKJuTy' },
    deleteAgentsContent: { defaultMessage: 'Are you sure you want to delete {count} agents?', id: '9hO/jE' },
    deleteAgentInProgress: { defaultMessage: 'Deleting "{name}"...', id: '9U5pgE' },
    deleteAgentsInProgress: { defaultMessage: 'Deleting {count} agents...', id: 'UIyZ/V' },
    deleteAgentSuccess: { defaultMessage: '"{name}" deleted successfully', id: 'hwGu/Q' },
    deleteAgentsSuccess: { defaultMessage: '{count} agents deleted successfully', id: 'Zk831H' },
    deleteAgentError: { defaultMessage: 'Failed to delete "{name}"', id: 'fFXU2w' },
    deleteAgentsError: { defaultMessage: 'Failed to delete some agents', id: '/h2P8O' },
    deleteAgentErrorDetail: { defaultMessage: 'Failed to delete "{name}": {error}', id: 'htQs+D' },
    selectAllAgents: { defaultMessage: 'Select all agents', id: '49wxuU' },
    selectAllAgentLinks: { defaultMessage: 'Select all agent links', id: '4CDU6x' },
    selectAgent: { defaultMessage: 'Select {name}', id: 'G65XME' },
    selectAgentLink: { defaultMessage: 'Select {name} link', id: 'xAeeyZ' },
    whitelistErrorMessage: {
        defaultMessage:
            'This subscription is not currently whitelisted to use SRE Agent. Please contact your administrator or support team to request access.',
        id: 'Kbdzt3',
    },
    iframeUnauthorizedMessage: {
        defaultMessage:
            'We were unable to load the URL {agentUxUrl}. This may be due to the existence of a firewall or network restrictions placed on the domain of your agent. Please speak to your network administrator to remove this restriction in order to proceed with interacting with your agent.',
        id: 'kbQZUj',
    },
    iframeZscalerUnauthorizedMessage: {
        defaultMessage:
            "We were unable to load the URL {agentUxUrl}. We've detected that your organization has selected Zscaler to protect you from unknown domains. Please speak to your network administrator to remove the restriction on this domain in order to proceed with interacting with your agent.",
        id: 'GDEEBE',
    },
    externalAgentDomainNotAllowed: {
        defaultMessage: 'The URI must end with ".azuresre.ai" or ".sre.azure.com".',
        id: 'zX8SaB',
    },
    operationCancelled: { defaultMessage: 'Operation cancelled', id: 'g82HU6' },
    directory: { defaultMessage: 'Directory', id: 'RDwKyy' },
    allSubscriptions: { defaultMessage: 'All subscriptions', id: '8yyU6n' },
    allResourceGroups: { defaultMessage: 'All resource groups', id: 'jEU2gk' },
    allRegions: { defaultMessage: 'All regions', id: '456ixe' },
    managedResourceGroups: { defaultMessage: 'Managed resource groups', id: 'yilQrD' },
    fieldRequired: { defaultMessage: 'This field is required.', id: '6B5Jtu' },
    minAgentCount: { defaultMessage: 'Must be at least 1', id: 'i5UGs3' },
    maxAgentCountLimit: { defaultMessage: 'Cannot exceed 100', id: '7We9Y2' },
    sreAgentNameMinMax: { defaultMessage: 'Name must be between 2 and 32 characters', id: '+YDzOd' },
    sreAgentNameAlreadyExists: { defaultMessage: 'An agent with this name already exists in the selected resource group.', id: 'ceCESY' },
    resourceGroupDenyAssignmentError: {
        defaultMessage: 'Some of the selected resource groups have deny assignments that prevent deployments.',
        id: 'GWson9',
    },
    sreAgentNameValidation: {
        defaultMessage:
            'The name must begin and end with a lowercase letter, and contain only lowercase letters, numbers, and hyphens. It cannot contain consecutive hyphens.',
        id: 'B6aNdQ',
    },
    expand: { defaultMessage: 'Expand', id: '0oLj/t' },
    collapse: { defaultMessage: 'Collapse', id: 'W/V6+Y' },
    sreAgentLocationsLoadFailure: { defaultMessage: 'Failed to load SRE Agent locations. Please try again later.', id: 'WE+M5j' },
    refresh: { defaultMessage: 'Refresh', id: 'rELDbB' },
    selectASubscription: { defaultMessage: 'Select a subscription', id: 'LrnSHG' },
    selectAnExistingResourceGroup: { defaultMessage: 'Select an existing resource group', id: 'LkSPVW' },
    selectRegion: { defaultMessage: 'Select region', id: 'tshYzs' },
    registrationFailed: { defaultMessage: 'Registration failed', id: 'G7yB8N' },
    loading: { defaultMessage: 'Loading', id: 'iFsDVR' },
    noResultsFound: { defaultMessage: 'No results found', id: 'hX5PAb' },
    noResourceGroupCreatePermission: {
        defaultMessage: 'You do not have permission to create resource groups under the currently selected subscription.',
        id: 'uqyJPP',
    },
    copy: { defaultMessage: 'Copy', id: '4l6vz1' },
    copied: { defaultMessage: 'Copied', id: 'p556q3' },
    copyToClipboard: { defaultMessage: 'Copy to clipboard', id: 'aCdAsI' },
    sessionId: { defaultMessage: 'Session ID', id: 'b0v+Pu' },
    getSupport: { defaultMessage: 'Get support', id: 'Km7x3v' },
    newItemFormat: { defaultMessage: '(new) {item}', id: 'zJ+8HW' },
    resourceGroupAlreadyExistsInSubscription: {
        defaultMessage: 'A resource group with this name already exists in the selected subscription.',
        id: 'If+Q1B',
    },
    policyErrorFormattedMessage: {
        defaultMessage: "Deployment to this resource group will be blocked by policy: '{field} not allowed'. Policy Assignment ID: {id}",
        id: '75IWbW',
    },
    allowlistWarning: {
        defaultMessage:
            'The subscription you have selected has not been registered to use SRE Agent. Please email us with your subscription ID on sreagentteam@microsoft.com for getting registered.',
        id: 'r0gBch',
    },
    reader: { defaultMessage: 'Reader', id: '3nhWFW' },
    readerDescription: {
        defaultMessage:
            "The agent has read-only permissions on the resource groups it manages. It takes the user's permissions temporarily for approved actions.",
        id: 'C0ZRdE',
    },
    privileged: { defaultMessage: 'Privileged', id: 'TDoBlx' },
    privilegedDescription: {
        defaultMessage:
            'The agent has permissions to take approved actions on resources and resource types detected in its assigned resource groups.',
        id: '3tJfza',
    },
    permissionsLevel: { defaultMessage: 'Agent permissions level', id: '+bJIWo' },
    permissionsDescription: {
        defaultMessage:
            'Assign the agent a level of permissions for the resource groups it manages. The agent can still manage its assigned resources with Reader permissions.',
        id: 'hswM/b',
    },
    learnMoreAboutAgentPermissions: { defaultMessage: 'Learn more about Reader and Privileged permissions', id: 'vu2LMl' },
    registrationFailedMessage: {
        defaultMessage:
            'We were unable to register the Microsoft.App RP due to a lack of permissions which may cause your deployment to fail. Ensure that you have Contributor permissions to this subscription or have your subscription administrator register the RP for you.',
        id: 'GmzN3r',
    },
    doYouWantToContinue: { defaultMessage: 'Do you want to continue?', id: 'xHDoP8' },
    managedResourceGroupDescription: {
        defaultMessage:
            'To assign the agent managed resource groups across subscriptions, you need Owner or User Access Administrator permissions on those resource groups. The agent resource and managed resource groups can be in different regions and subscriptions.',
        id: 'sRU00i',
    },
    learnMoreAboutManagedRgPermissions: { defaultMessage: 'Learn more about permissions for managed resource groups', id: 'ru0BPw' },
    resourceGroupNameLinkAriaLabel: { defaultMessage: 'Open resource group', id: 'tffS9r' },
    readOnlyLock: { defaultMessage: 'Read only lock', id: 'fIp46f' },
    denyAssignments: { defaultMessage: 'Deny assignments', id: 'iM9JZL' },
    policyErrors: { defaultMessage: 'Denied by policy', id: 'ASEuj4' },
    resourceGroupLockError: {
        defaultMessage: 'Some of the selected resource groups have a read only lock on the resource group.',
        id: 'YYx7ap',
    },
    resourceGroupPermissionError: {
        defaultMessage: 'Choose at least 1 resource group that you have Owner or User Access Administrator permissions on.',
        id: 'kyVg+J',
    },
    resourceGroupPolicyError: {
        defaultMessage: 'Some of the selected resource groups have policies that will cause the deployment to fail.',
        id: '+Ov1f1',
    },
    resourceGroupMaxError: { defaultMessage: 'You can choose a maximum of 100 resource groups that the agent will manage.', id: 'axbDHG' },
    removeResourceGroup: { defaultMessage: 'Remove resource group', id: '4USxEK' },
    userPermissions: { defaultMessage: 'User permissions', id: '5M+hLZ' },
    managedResourceGroupsTableAriaLabel: { defaultMessage: 'Managed resource groups table', id: 'V/rQci' },
    agentDetails: { defaultMessage: 'Agent details', id: 'Wf6bDe' },
    all: { defaultMessage: 'All', id: 'zQvVDJ' },
    noResults: { defaultMessage: 'No results', id: 'jHJmjf' },
    apply: { defaultMessage: 'Apply', id: 'EWw/tK' },
    equals: { defaultMessage: 'equals', id: 'Y2QRpS' },
    selectedOutOfTotal: { defaultMessage: '{selectedCount} of {totalCount}', id: '01sZoP' },
    optionsListAriaLabel: { defaultMessage: '{fieldName} options', id: 'dDk23i' },
    pillFilterAriaLabel: {
        defaultMessage: 'Editor to filter the results by column value. {columnName}{delimiter} {filterValue}',
        id: '5j5HnL',
    },
    pillFilterRemoveAriaLabel: { defaultMessage: 'Remove {columnName} filter', id: '/ytgXm' },
    selectResourceGroupsToMonitor: { defaultMessage: 'Select resource groups to monitor', id: 'CfGC/2' },
    resourceGroupName: { defaultMessage: 'Resource group name', id: 'xVPoso' },
    save: { defaultMessage: 'Save', id: 'jvo0vs' },
    selectAll: { defaultMessage: 'Select all', id: '94Fg25' },
    resourceGroupPickerTitle: { defaultMessage: 'Select resource groups', id: 'ftfFhS' },
    resourceGroupsMax: { defaultMessage: 'Select up to {max} resource groups to manage.', id: '6EQs7U' },
    resourceGroupSelected: { defaultMessage: '{0} resource group selected', id: 'nlPgO8' },
    resourceGroupsSelected: { defaultMessage: '{0} resource groups selected', id: 'egr0Oj' },
    showRecommended: { defaultMessage: 'Show recommended', id: 'PfwAB2' },
    showRecommendedTooltip: {
        defaultMessage:
            'To get optimal agent performance for diagnostics, metrics, knowledge, and more, use resource groups that include one or more of these Azure compute services: Azure Kubernetes Service, Functions, Container Apps, or Web Apps.',
        id: '0zGfOk',
    },
    toggleShowRecommendedAriaLabel: { defaultMessage: 'Toggle to show only recommended resource groups', id: 'Kg6ebk' },
    searchResourceGroups: { defaultMessage: 'Search resource groups', id: 'pMlVvA' },
    resourceGroupPickerTableAriaLabel: { defaultMessage: 'Resource groups list', id: 'Ngsqgf' },
    resourceGroupPickerDialogAriaLabel: { defaultMessage: 'Select resource groups dialog', id: '2xRon3' },
    recommendedResourceGroupTooltip: {
        defaultMessage: 'This resource group contains resources supported by SRE Agent',
        id: 'CrmeG3',
    },
    appInsightsSubscription: { defaultMessage: 'Application Insights subscription', id: 'fLcQXf' },
    existingAppInsightsName: { defaultMessage: 'Application Insights name', id: 'I5NZ9z' },
    existingAppInsightsNamePlaceholder: { defaultMessage: 'Select an Application Insights resource', id: 'cqGvFd' },
    applicationInsights: { defaultMessage: 'Application Insights', id: 'WFo96A' },
    useExisting: { defaultMessage: 'Use existing', id: 'I5k4g/' },
    agentNotFound: { defaultMessage: 'Agent not found', id: 'WtU4fE' },
    agentNotFoundDescription: {
        defaultMessage: "The agent you're looking for doesn't exist or may have been deleted. Please verify the resource ID and try again.",
        id: '2mq+ou',
    },
    agentAccessDenied: { defaultMessage: 'You do not have access to this agent', id: 'nakQqT' },
    agentAccessDeniedDescription: {
        defaultMessage: 'You do not have the necessary permissions to access this agent. Please contact your administrator for assistance.',
        id: 'M6fZyT',
    },
    agentLoadError: { defaultMessage: 'Failed to load agent', id: 'Uj2xYe' },
    agentLoadErrorDescription: {
        defaultMessage:
            'We encountered an error while trying to load your agent. Please try again or contact support if the issue persists.',
        id: 'oDZ249',
    },
    resourceId: { defaultMessage: 'Resource ID', id: 'iIoj97' },
    agentLoadTimeout: { defaultMessage: 'Failed to load agent site', id: 'Tu5Fvy' },
    agentLoadTimeoutDescription: {
        defaultMessage:
            'The request either timed out or your browser refused the connection. Check your network status, browser settings and extensions, or VPN settings for conflicts. Your agent may also be cold-starting.',
        id: 'gILrEi',
    },
    ensureNetworkAllows: { defaultMessage: 'Ensure your network allows', id: 'lrM2un' },
    errorDetails: { defaultMessage: 'Error details', id: 'qddSy6' },
    agentUrl: { defaultMessage: 'Agent URL', id: 'iYl35v' },
    agentSpaces: { defaultMessage: 'Agent Spaces', id: '3j71PW' },
    agentSpace: { defaultMessage: 'Agent Space', id: 'UIvVY8' },
    noAgentSpacesFound: { defaultMessage: 'No agent spaces found', id: 'W0NhZW' },
    noAgentSpacesFoundDescription: {
        defaultMessage: 'Agent spaces help organize and manage groups of agents.',
        id: 'wHWHjx',
    },
    currentAgentCount: { defaultMessage: 'Current agents', id: 'In2M6P' },
    maxAgentCount: { defaultMessage: 'Maximum agents', id: 'r8wqt4' },
    memberAgents: { defaultMessage: 'Member Agents', id: '/JGD/D' },
    noMemberAgents: { defaultMessage: 'No agents in this space', id: 'qIuXVW' },
    genevaActionPolicies: { defaultMessage: 'Geneva Action Policies', id: 'svoioC' },
    connectors: { defaultMessage: 'Connectors', id: '2mMJRv' },
    connectorName: { defaultMessage: 'Connector name', id: '1MgY/m' },
    connectorType: { defaultMessage: 'Connector type', id: 'kQSvkP' },
    deleteAgentSpace: { defaultMessage: 'Delete agent space', id: 'MMR8IH' },
    deleteAgentSpaceConfirmation: {
        defaultMessage: 'Are you sure you want to delete this agent space? This action cannot be undone.',
        id: 'XkSqFv',
    },
    agentSpaceDeleted: { defaultMessage: 'Agent space deleted', id: 'sWQvsR' },
    viewInAzurePortal: { defaultMessage: 'View in Azure Portal', id: 'WARz6s' },
    overview: { defaultMessage: 'Overview', id: '9uOFF3' },
    configuration: { defaultMessage: 'Configuration', id: '7OW8BT' },
    searchAgentSpaces: { defaultMessage: 'Search agent spaces', id: 'PXgJ4K' },
    agentSpaceDetails: { defaultMessage: 'Agent space details', id: 'v8dn0Y' },
    description: { defaultMessage: 'Description', id: 'Q8Qw5B' },
    noDescription: { defaultMessage: 'No description', id: '5lVaeB' },
    provisioningState: { defaultMessage: 'Provisioning state', id: 'h5VeVD' },
    deleteAgentSpaceInProgress: { defaultMessage: 'Deleting agent space...', id: 'BT/kww' },
    deleteAgentSpaceSuccess: { defaultMessage: 'Agent space "{name}" deleted successfully', id: 'sL7DgF' },
    deleteAgentSpaceError: { defaultMessage: 'Failed to delete agent space', id: 'mWePlI' },
    deleteAgentSpaceErrorDetail: { defaultMessage: 'Failed to delete "{name}": {error}', id: 'htQs+D' },
    identity: { defaultMessage: 'Identity', id: 'tShbyC' },
    noConnectors: { defaultMessage: 'No connectors configured', id: 'WE9lZK' },
    addConnector: { defaultMessage: 'Add connector', id: 'QDa8Q+' },
    createConnector: { defaultMessage: 'Create connector', id: 'EmN362' },
    deleteConnector: { defaultMessage: 'Delete connector', id: '8urALB' },
    deleteConnectors: { defaultMessage: 'Delete {count} connectors', id: 'kWfaS8' },
    editConnector: { defaultMessage: 'Edit connector', id: '7kPmO3' },
    updateConnector: { defaultMessage: 'Update connector', id: 'GeSTZm' },
    anthropicProviderLabel: { defaultMessage: 'Anthropic', id: 'LftgYR' },
    azureOpenAiProviderLabel: { defaultMessage: 'Azure OpenAI', id: 'MTp7be' },
    getSupportedModelsFailedMessage: { defaultMessage: 'Unable to load available models. Please try again later.', id: 'rhW41X' },
    modelProviderLabel: { defaultMessage: 'Model provider', id: 'DTJ2/l' },
    providerLabel: { defaultMessage: 'Provider', id: 'xaj9Ba' },
    modelLabel: { defaultMessage: 'Model', id: 'rhSI1/' },
    anthropicEuRegionInfoMessage: {
        defaultMessage:
            'Anthropic processes data in the United States and is excluded from European Union Data Boundary (EUDB). This data includes prompts, responses, and resource analysis. If EUDB is required for your use case, select a different model.',
        id: 'UwPEiY',
    },
    anthropicEuRegionLearnMore: {
        defaultMessage: 'Learn more about SRE Agent data handling',
        id: 'KOamvU',
    },
    anthropicNotAvailable: {
        defaultMessage: `Anthropic is not available due to your organization’s data residency policy. Contact your administrator for more information.`,
        id: 'x3nLRm',
    },
    providerPlaceholder: { defaultMessage: 'Select region first', id: 'zUmqxZ' },
    // Connector CRUD operations
    creatingConnector: { defaultMessage: 'Creating connector...', id: 'jE1HXt' },
    createConnectorSuccess: { defaultMessage: 'Connector "{name}" created successfully', id: 'ZqOouB' },
    createConnectorError: { defaultMessage: 'Failed to create connector', id: '/mHau5' },
    createConnectorErrorDetail: { defaultMessage: 'Failed to create connector "{name}": {error}', id: 'Kgx0MQ' },
    updatingConnector: { defaultMessage: 'Updating connector...', id: 'C+2c0E' },
    updateConnectorSuccess: { defaultMessage: 'Connector "{name}" updated successfully', id: '8JRe41' },
    updateConnectorError: { defaultMessage: 'Failed to update connector', id: '2Bb4rY' },
    updateConnectorErrorDetail: { defaultMessage: 'Failed to update connector "{name}": {error}', id: 'JGwNR8' },
    deletingConnector: { defaultMessage: 'Deleting connector...', id: 'Yy5PkJ' },
    deleteConnectorSuccess: { defaultMessage: 'Connector "{name}" deleted successfully', id: 'T/+mFe' },
    deleteConnectorsSuccess: { defaultMessage: '{count} connectors deleted successfully', id: 'fewvU8' },
    deleteConnectorError: { defaultMessage: 'Failed to delete connector', id: 'ocTBQX' },
    deleteConnectorErrorDetail: { defaultMessage: 'Failed to delete connector "{name}": {error}', id: 'ax8DkG' },
    deleteConnectorConfirmation: { defaultMessage: 'Are you sure you want to delete the selected connector(s)?', id: 'W8CNIz' },
    // Connector form fields
    dataSource: { defaultMessage: 'Data source', id: '7C0xai' },
    dataSourcePlaceholder: { defaultMessage: 'Enter data source URL', id: 'Zed+6u' },
    dataSourceKustoHint: { defaultMessage: 'e.g., https://cluster-url/database-name', id: 'INU718' },
    dataSourceKustoFormatError: { defaultMessage: 'Invalid Kusto URL format. Expected: {example}', id: '1cryPp' },
    connectorNamePlaceholder: { defaultMessage: 'Enter connector name', id: '+2NFJn' },
    connectorTypePlaceholder: { defaultMessage: 'Select connector type', id: 'ftDEuE' },
    duplicateConnectorNameError: { defaultMessage: 'A connector with this name already exists', id: 'qf1aUJ' },
    identityPlaceholder: { defaultMessage: 'Select identity', id: '8RdOD0' },
    addIdentity: { defaultMessage: 'Add identity', id: 'xUuESs' },
    systemAssigned: { defaultMessage: 'System assigned', id: 'yh4G7g' },
    userAssigned: { defaultMessage: 'User Assigned', id: 'gOBgIL' },
    // SecretValue and Reveal
    clickToReveal: { defaultMessage: 'Click to reveal', id: 'YtSZPi' },
    revealAll: { defaultMessage: 'Reveal all', id: 'KRdX9D' },
    showValue: { defaultMessage: 'Show value', id: 'IhFpMB' },
    hideValue: { defaultMessage: 'Hide value', id: 'Etd/WH' },
    andMoreItems: { defaultMessage: 'and {count} more...', id: '79TiwE' },
    keyVaultUri: { defaultMessage: 'Key Vault URI', id: 'auFFJa' },
    start: { defaultMessage: 'Start', id: 'mOFG3K' },
    stop: { defaultMessage: 'Stop', id: 'q/uwLT' },
    remove: { defaultMessage: 'Remove', id: 'G/yZLu' },
    // Agent Space Create
    createAgentSpace: { defaultMessage: 'Create agent space', id: 'KRJedt' },
    agentSpaceName: { defaultMessage: 'Agent space name', id: 'YMzjGQ' },
    reviewAndCreate: { defaultMessage: 'Review + Create', id: '18kCI/' },
    projectDetails: { defaultMessage: 'Project details', id: '7gMEKc' },
    projectDetailsDescription: {
        defaultMessage:
            'Select the subscription to manage deployed resources and costs. Use resource groups like folders to organize and manage all your resources.',
        id: 'IVkHOG',
    },
    agentSpaceDetailsDescription: {
        defaultMessage: "Name your agent and choose a region where it'll be deployed and operated.",
        id: 'tBGxhK',
    },
    enableGenevaActions: { defaultMessage: 'Enable Geneva Actions', id: 'INZN6F' },
    genevaActionsEnabled: { defaultMessage: 'Geneva Actions enabled', id: 'QH7pDB' },
    genevaActionsCertificateName: { defaultMessage: 'Geneva Actions Certificate Name', id: 'x2Qj1F' },
    genevaActionsWarning: {
        defaultMessage: 'Geneva Actions configuration is only supported for AME, PME, and Torus tenants.',
        id: 'A3j9BD',
    },
    policies: { defaultMessage: 'Policies', id: 'yV5oYe' },
    policiesDescription: {
        defaultMessage: 'Configure Geneva Actions Policies to establish governance rules controlling agent behavior and capabilities.',
        id: 'sVWcI9',
    },
    allowedActionsDescription: {
        defaultMessage:
            'Centrally configure allowed Geneva Actions at the Agent Space level. Any agent assigned to that Agent Space will inherit the configuration, simplifying identity and authorization management.',
        id: 'mY/BMb',
    },
    actionName: { defaultMessage: 'Action name', id: 'uKLatv' },
    actionNamePlaceholder: { defaultMessage: 'Action name', id: 'uKLatv' },
    extensionPlaceholder: { defaultMessage: 'Extension', id: 'i8CwA4' },
    addAllowedActions: { defaultMessage: 'Add allowed actions', id: 'Vb+GHQ' },
    addAllowedActionsDescription: {
        defaultMessage:
            'Define the Geneva actions that agents can perform on your resources. Specify the extension and action name for each allowed action.',
        id: 'NMwOmQ',
    },
    noAllowedActionsConfigured: { defaultMessage: 'No allowed actions configured', id: 'oayJA3' },
    agentSpaceNameValidation: {
        defaultMessage: 'Name can only contain lowercase letters, numbers, and hyphens. Must start and end with a letter or number.',
        id: 'k8dQr8',
    },
    agentSpaceNameMinMax: { defaultMessage: 'Name must be between 2 and 32 characters', id: '+YDzOd' },
    agentSpaceNameExists: { defaultMessage: 'An agent space with this name already exists', id: 'hR80+Y' },
    creatingAgentSpace: { defaultMessage: 'Creating agent space', id: 'zpbxjU' },
    creatingAgentSpaceDescription: { defaultMessage: "Creating agent space ''{name}''", id: 'ODJPeM' },
    agentSpaceCreatedSuccess: { defaultMessage: "Agent space ''{name}'' created successfully", id: 'bS9DAy' },
    agentSpaceCreatedError: { defaultMessage: "Failed to create agent space ''{name}''", id: 'UB9VOo' },
    agentSpaceCreatedErrorDetail: { defaultMessage: 'Failed to create agent space "{name}": {error}', id: '7inPbA' },
    goToAgentSpace: { defaultMessage: 'Go to agent space', id: 'nu83ZZ' },
    previous: { defaultMessage: 'Previous', id: 'JJNc3c' },
    // Agent Space View
    viewJson: { defaultMessage: 'View JSON', id: 'fqjEXz' },
    apiVersion: { defaultMessage: 'API Version', id: 'kGtbSc' },
    details: { defaultMessage: 'Details', id: 'Lv0zJu' },
    addExistingAgent: { defaultMessage: 'Add existing agent', id: 'xHFZ4R' },
    discard: { defaultMessage: 'Discard', id: 'nmpevl' },
    saving: { defaultMessage: 'Saving...', id: 'TiR/Hq' },
    saved: { defaultMessage: 'Changes saved successfully', id: 'jkwYgX' },
    updateAgentSpace: { defaultMessage: 'Update Agent Space', id: 'p/64yV' },
    updatingAgentSpace: { defaultMessage: 'Updating Agent Space...', id: 'N1fyah' },
    updateAgentSpaceSuccess: { defaultMessage: 'Successfully updated Agent Space', id: 'cY6LgY' },
    updateAgentSpaceError: { defaultMessage: 'Failed to update Agent Space', id: 'rrWPRM' },

    // Agent picker dialog
    selectAgentsStep: { defaultMessage: 'Select agents', id: 'olqcD6' },
    reviewAgentSelection: { defaultMessage: 'Review agent selection', id: 'DWsPy7' },
    agentPickerDescription: {
        defaultMessage:
            'Your SRE Agent Space can have a maximum of {max} agents. Select up to {remaining} SRE Agents to add to your SRE Agent Space. You can only add SRE Agents in the same location as your SRE Agent Space.',
        id: 'KWAsmo',
    },
    searchAgents: { defaultMessage: 'Search agents', id: 'tvKgdj' },
    nSelected: { defaultMessage: '{count} selected', id: 'NKPfmm' },
    noAvailableAgents: { defaultMessage: 'No available agents found', id: 'IC4a5J' },
    noAvailableAgentsDescription: {
        defaultMessage: 'There are no SRE Agents in this location that can be added to the space.',
        id: 'CraXSX',
    },

    // Agent actions
    addAgent: { defaultMessage: 'Add agent', id: 'WyghCH' },
    addingAgentToSpace: { defaultMessage: 'Adding SRE Agent to SRE Agent Space', id: 'MelFEV' },
    addingAgentToSpaceInProgress: { defaultMessage: 'Adding agent to space...', id: 'Lgp9aP' },
    addAgentToSpaceSuccess: { defaultMessage: 'Successfully added SRE Agent {name} to SRE Agent Space {space}', id: 'P7jt+t' },
    addAgentToSpaceError: { defaultMessage: 'Failed to add agent to space', id: 'l+DswI' },

    startingAgent: { defaultMessage: 'Starting SRE Agent', id: 'JSW9Xw' },
    startingAgentInProgress: { defaultMessage: 'Starting agent...', id: 'bB9Or0' },
    startAgentSuccess: { defaultMessage: 'Successfully started SRE Agent {name}', id: 'wJSE2+' },
    startAgentError: { defaultMessage: 'Failed to start agent', id: 'ReAfD+' },
    startAgentErrorDetail: { defaultMessage: 'Failed to start agent: {error}', id: '14MwLi' },

    stoppingAgent: { defaultMessage: 'Stopping SRE Agent', id: 'XDcbqQ' },
    stoppingAgentInProgress: { defaultMessage: 'Stopping agent...', id: 'ArSfTn' },
    stopAgentSuccess: { defaultMessage: 'Successfully stopped SRE Agent {name}', id: 'O/je+Z' },
    stopAgentError: { defaultMessage: 'Failed to stop agent', id: 'zlSKju' },
    stopAgentErrorDetail: { defaultMessage: 'Failed to stop agent: {error}', id: 'wX1xwS' },

    removingAgentFromSpace: { defaultMessage: 'Removing agent from space', id: 'BOjNaA' },
    removingAgentFromSpaceInProgress: { defaultMessage: 'Removing agent from space...', id: 'H9pUrG' },
    removeAgentFromSpaceSuccess: { defaultMessage: 'Successfully removed SRE Agent {name} from space', id: '+JBQtK' },
    removeAgentFromSpaceError: { defaultMessage: 'Failed to remove agent from space', id: 'CITK5s' },
    removeAgentFromSpaceErrorDetail: { defaultMessage: 'Failed to remove agent from space: {error}', id: 'qZ/RsM' },
    removeAgentFromSpaceConfirmation: {
        defaultMessage:
            'Are you sure you want to remove {count, plural, one {this agent} other {these # agents}} from the space? The agents will continue running but will no longer be part of this Agent Space.',
        id: 'UNeAO+',
    },
    removeAgentFromSpaceTitle: { defaultMessage: 'Remove agent from space', id: 'aN6qBi' },
    andMore: { defaultMessage: 'and {count} more...', id: '79TiwE' },

    powerState: { defaultMessage: 'Power state', id: 'clIJ18' },
    running: { defaultMessage: 'Running', id: 'nDyaq/' },
    stopped: { defaultMessage: 'Stopped', id: '1LBny5' },
    resourceGroupColumn: { defaultMessage: 'Resource group', id: '+uAdUZ' },
});

export const ResourceTypeNameResources = defineMessages({
    website: { defaultMessage: 'App Services', id: 'UVD6yh' },
    functionApp: { defaultMessage: 'Function Apps', id: 'L31yBb' },
    storageAccounts: { defaultMessage: 'Storage Accounts', id: '5UUKxL' },
    storageBlobContainers: { defaultMessage: 'Storage Blob Containers', id: '43mD/Y' },
    cosmosDbAccounts: { defaultMessage: 'Cosmos DB Accounts', id: '+zgzmq' },
    sqlServers: { defaultMessage: 'SQL Servers', id: 'zhHihn' },
    sqlDatabases: { defaultMessage: 'SQL Databases', id: 'bXkiU5' },
    sqlManagedInstances: { defaultMessage: 'SQL Managed Instances', id: 'X0e0bZ' },
    aksClusters: { defaultMessage: 'AKS Clusters', id: 'FqRdvb' },
    containerApps: { defaultMessage: 'Container Apps', id: '+TlNdm' },
    redisCache: { defaultMessage: 'Redis Cache', id: 'cmUVb9' },
    virtualMachines: { defaultMessage: 'Virtual Machines', id: 'zEk9h3' },
    postgreSqlFlexibleServers: { defaultMessage: 'PostgreSQL Flexible Servers', id: '1myzs4' },
    postgreSqlServers: { defaultMessage: 'PostgreSQL Servers', id: '/wY7pG' },
    dataFactories: { defaultMessage: 'Data Factories', id: 'C8z3QQ' },
    machineLearningWorkspaces: { defaultMessage: 'Machine Learning Workspaces', id: 'AVMCsG' },
    cognitiveServices: { defaultMessage: 'Cognitive Services', id: 'fSFDgd' },
    searchServices: { defaultMessage: 'Search Services', id: 'ufonOZ' },
    digitalTwins: { defaultMessage: 'Digital Twins', id: '2do8JC' },
    iotHubs: { defaultMessage: 'IoT Hubs', id: 'uh732n' },
    apiManagement: { defaultMessage: 'API Management', id: 'iv5NrP' },
    appConfiguration: { defaultMessage: 'App Configuration', id: 'KJGQ1f' },
    serviceBus: { defaultMessage: 'Service Bus', id: 's0xRD+' },
    logicApps: { defaultMessage: 'Logic Apps', id: 'TzxmIN' },
    applicationInsights: { defaultMessage: 'Application Insights', id: 'WFo96A' },
    logAnalyticsWorkspaces: { defaultMessage: 'Log Analytics Workspaces', id: 'WlHVBb' },
    insights: { defaultMessage: 'App Insights', id: 'hGmeVK' },
    workbooks: { defaultMessage: 'Workbooks', id: 'HCDcpW' },
    sapVirtualInstances: { defaultMessage: 'SAP Virtual Instances', id: 'b43a5F' },
    costManagement: { defaultMessage: 'Cost Management', id: '69g7If' },
});

export const AgentCreateDeploymentNotificationResources = defineMessages({
    agentCreationTitle: { defaultMessage: 'Provisioning SRE Agent', id: '/6Fckw' },
    agentCreationInProgress: {
        defaultMessage: "We've started provisioning your SRE Agent {agentName} to manage your selected resource groups.",
        id: 'pVF2EE',
    },
    agentCreatedSuccessDescription: { defaultMessage: 'SRE Agent {agentName} creation succeeded', id: 'WODKUB' },
    agentCreationFailedDescription: {
        defaultMessage: 'Failed to create the SRE agent {agentName} with the error: {error}',
        id: 'YYWhEp',
    },
    agentCreationValidationTitle: { defaultMessage: 'Validating SRE Agent creation', id: 'OsTw6c' },
    agentCreationValidationInProgress: {
        defaultMessage: 'Validating SRE Agent {agentName} creation in progress',
        id: 'lcvC4k',
    },
    agentCreationValidationSuccessDescription: {
        defaultMessage: 'SRE Agent {agentName} creation validation succeeded',
        id: 'NCTGGm',
    },
    agentCreationValidationRPFailureDescription: {
        defaultMessage:
            'Failed to register Microsoft.App RP for SRE Agent {agentName} creation. Please ensure you have Contributor permissions on the subscription or contact your subscription administrator to register the RP for you.',
        id: 'QwVQbw',
    },
    agentCreationValidationFailedDescription: {
        defaultMessage: 'Failed to validate SRE Agent {agentName} creation with the error: {error}',
        id: 'lNehTG',
    },
    identityFailedDescription: { defaultMessage: 'Failed to setup Managed Identity with the error: {error}', id: 'UuzObe' },
    workspaceFailedDescription: {
        defaultMessage: 'Failed to setup Log Analytics Workspace with the error: {error}',
        id: 'oThNc4',
    },
    templateBuilderFailedDescription: { defaultMessage: 'Invalid template or unable to fetch the template.', id: 'VssvTa' },
    templateBuilderFailedTitle: { defaultMessage: 'Template error', id: 'eKpamp' },
    resourceGroupFailedDescription: { defaultMessage: 'Resource group creation failed.', id: 'jjUD0v' },
    resourceGroupFailedTitle: { defaultMessage: 'Resource group creation', id: 'pW5vuU' },
});

export const DeployResources = defineMessages({
    deploy: { defaultMessage: 'Deploy', id: '556JQK' },
    deploymentName: { defaultMessage: 'Deployment name', id: 'OjYIuI' },
    correlationId: { defaultMessage: 'Correlation ID', id: 'p849eW' },
    startTime: { defaultMessage: 'Start time', id: '/zFP1/' },
    deploymentInProgress: { defaultMessage: 'Deployment in progress...', id: 'gty4jJ' },
    deploymentSucceeded: { defaultMessage: 'Deployment succeeded', id: 'v90qT8' },
    deploymentFailed: { defaultMessage: 'Deployment failed', id: '9M3sYh' },
    tenantRestrictionError: {
        defaultMessage:
            'Agent Spaces are currently limited to 1P tenants and must be allow-listed. Please reach out to the SRE Agent team.',
        id: 'h1r1EI',
    },
    resourceOperations: { defaultMessage: 'Resource operations', id: 'czVHN2' },
    creating: { defaultMessage: 'Creating', id: 'xhfdqv' },
    created: { defaultMessage: 'Created', id: 'ORGv1Q' },
    failed: { defaultMessage: 'Failed', id: 'vXCeIi' },
    updating: { defaultMessage: 'Updating', id: 'S8snIe' },
    running: { defaultMessage: 'Running', id: 'nDyaq/' },
    succeeded: { defaultMessage: 'Succeeded', id: 'LOghU6' },
    noOperations: { defaultMessage: 'No operations found', id: 'vxVGav' },
    loadingOperations: { defaultMessage: 'Loading operations...', id: '1Lx9q5' },
});

export const RolesAndPermissions = defineMessages({
    loadingResourceTypes: { defaultMessage: 'Loading resource types...', id: 'q7CVBv' },
    detectedResourceTypes: { defaultMessage: 'Detected resource types', id: 'zacv31' },
    role: { defaultMessage: 'Role', id: '1ZgrhW' },
    description: { defaultMessage: 'Description', id: 'Q8Qw5B' },
    permissionsTableAriaLabel: { defaultMessage: 'Agent permissions and roles table', id: 'Ab4TgE' },
    currentAgentCount: { defaultMessage: 'Current agent count', id: 'Xh85Ml' },
    maxAgentCount: { defaultMessage: 'Max agent count', id: 'AhdXRl' },
    policies: { defaultMessage: 'Policies', id: 'yV5oYe' },
    genevaActionsConfiguration: { defaultMessage: 'Geneva actions configuration', id: '1t2BaF' },
    authenticationMode: { defaultMessage: 'Authentication mode', id: 'Z2WgoK' },
    extensionName: { defaultMessage: 'Extension name', id: 'oIiHqo' },
    acisEndpoint: { defaultMessage: 'ACIS endpoint', id: 'pM3DKw' },
    clientId: { defaultMessage: 'Client ID', id: 'U5+MBC' },
    allowedActions: { defaultMessage: 'Allowed Actions', id: 'n/e5Mg' },
    approvalRequired: { defaultMessage: 'Approval Required', id: 'G1xeUt' },
    certificateSubjectAlternativeName: { defaultMessage: 'Certificate SAN', id: 's2jhon' },
    genevaActionsCertificateName: { defaultMessage: 'Geneva Actions Certificate Name', id: 'x2Qj1F' },
    readOnlyModeDescription: {
        defaultMessage:
            'Your agent is in read-only mode. The following permissions are required for the agent to build knowledge about your resources. The contributor roles for specific services will not be used to perform any write operations.',
        id: 'P9odAr',
    },
    reviewModeDescription: {
        defaultMessage:
            'Your agent is in review mode. The following permissions are required for the agent to build knowledge about your resources. The agent will use some of these permissions to perform write operations with your approval based on your requests.',
        id: 'p/xAmY',
    },
    autonomousModeDescription: {
        defaultMessage:
            'Your agent is in autonomous mode. The following permissions are required for the agent to build knowledge about your resources. The agent will use some of these permissions to perform write operations autonomously based on your requests.',
        id: '/dxZCE',
    },
    rolesAndPermissionsDescription: {
        defaultMessage: 'The resources you picked have permissions for these roles.',
        id: 'OTGHHm',
    },
    noRolesAndPermissions: {
        defaultMessage: 'To view the roles and permissions the agent will have, choose resource groups for the agent to manage.',
        id: 'Qly58H',
    },
    contributor: { defaultMessage: 'Contributor', id: '+k5t/y' },
    contributorDescription: {
        defaultMessage:
            'Grants full access to manage all resources, but does not allow you to assign roles in Azure RBAC, manage assignments in Azure Blueprints, or share image galleries.',
        id: 'KzMCPo',
    },
    monitoringContributorDescription: {
        defaultMessage: 'Can read all monitoring data and update monitoring settings.',
        id: 'PrFU82',
    },
    containerAppsContributor: { defaultMessage: 'Container Apps Contributor', id: 'i5OUQE' },
    containerAppsContributorDescription: {
        defaultMessage: 'Full management of Container Apps, including creation, deletion, and updates.',
        id: 'Mnvpbx',
    },
    logAnalyticsReader: { defaultMessage: 'Log Analytics Reader', id: 'sI+CCC' },
    logAnalyticsReaderDescription: {
        defaultMessage:
            'View and search all monitoring data as well as view monitoring settings, including viewing the configuration of Azure diagnostics on all Azure resources.',
        id: 'Oom2N7',
    },
    websitesContributor: { defaultMessage: 'Website Contributor', id: 'xtkizV' },
    websitesContributorDescription: {
        defaultMessage: 'Manage websites, but not web plans. Does not allow you to assign roles.',
        id: '3zLsNR',
    },
    webPlanContributor: { defaultMessage: 'Web Plan Contributor', id: '1YPTmM' },
    webPlanContributorDescription: {
        defaultMessage: 'Lets you manage the web plans for websites, but not access to them.',
        id: 'jJE3xY',
    },
    reader: { defaultMessage: 'Reader', id: '3nhWFW' },
    readerDescription: { defaultMessage: 'View all resources, but does not allow you to make any changes.', id: 'LSaaxU' },
    containerAppsOperator: { defaultMessage: 'Container Apps Operator', id: '/WrP/v' },
    containerAppsOperatorDescription: { defaultMessage: 'Read, logstream and exec into Container Apps.', id: 'gn/nvJ' },
    azureKubernetesServiceRbacReader: { defaultMessage: 'Azure Kubernetes Service RBAC Reader', id: 'RrsyUh' },
    azureKubernetesServiceRbacReaderDescription: {
        defaultMessage:
            'Allows read-only access to see most objects in a namespace. It does not allow viewing roles or role bindings. This role does not allow viewing Secrets, since reading the contents of Secrets enables access to ServiceAccount credentials in the namespace, which would allow API access as any ServiceAccount in the namespace (a form of privilege escalation). Applying this role at cluster scope will give access across all namespaces.',
        id: 'gC4xMY',
    },
    azureKubernetesServiceClusterUserRole: { defaultMessage: 'Azure Kubernetes Service Cluster User Role', id: '5V+Txp' },
    azureKubernetesServiceClusterUserRoleDescription: {
        defaultMessage: 'List cluster user credential action.',
        id: 'Bcx/Gz',
    },
    azureKubernetesServiceClusterAdmin: { defaultMessage: 'Azure Kubernetes Service Cluster Admin', id: 'RStTJp' },
    azureKubernetesServiceClusterAdminDescription: {
        defaultMessage: 'List cluster admin credential action.',
        id: '4kCXiz',
    },
    azureKubernetesServiceRbacClusterAdmin: { defaultMessage: 'Azure Kubernetes Service RBAC Cluster Admin', id: 'YZIFAO' },
    azureKubernetesServiceRbacClusterAdminDescription: {
        defaultMessage: 'Lets you manage all resources in the cluster.',
        id: 'nBPow3',
    },
    azureMonitorMonitoringContributor: { defaultMessage: 'Monitoring Contributor', id: 'TAm7bB' },
    azureMonitorMonitoringContributorDescription: {
        defaultMessage: 'Read and write Azure Monitor monitoring settings and data.',
        id: 'mkhNnB',
    },
    applicationInsightsComponentContributor: {
        defaultMessage: 'Application Insights Component Contributor',
        id: 'VlBNux',
    },
    applicationInsightsComponentContributorDescription: {
        defaultMessage: 'Manage Application Insights components.',
        id: 'pqgzm0',
    },
    logAnalyticsContributor: { defaultMessage: 'Log Analytics Contributor', id: 'e0a3XV' },
    logAnalyticsContributorDescription: {
        defaultMessage: 'Read all monitoring data and edit monitoring settings.',
        id: '6zUWZ/',
    },
    postgreSqlContributor: { defaultMessage: 'PostgreSQL Contributor', id: 'gzx/k1' },
    postgreSqlContributorDescription: { defaultMessage: 'TODO', id: 'RVf7gC' }, // TODO
    redisCacheContributor: { defaultMessage: 'Redis Cache Contributor', id: '8nBFW4' },
    redisCacheContributorDescription: { defaultMessage: 'Manage without access.', id: 'hO1Iog' },
    sqlDbContributor: { defaultMessage: 'SQL DB Contributor', id: 'hfIdUs' },
    sqlDbContributorDescription: {
        defaultMessage: "Manage without access. Can't manage security policies or parent SQL servers.",
        id: 'p5T+zv',
    },
    storageBlobDataContributor: { defaultMessage: 'Storage Blob Data Contributor', id: 'ND2EUR' },
    storageBlobDataContributorDescription: {
        defaultMessage: 'Read, write, and delete Azure Storage containers and blobs.',
        id: 'uRMqBi',
    },
    documentDbAccountContributor: { defaultMessage: 'DocumentDB Account Contributor', id: 'ABo5XY' },
    documentDbAccountContributorDescription: { defaultMessage: 'Can read Azure Cosmos DB account data.', id: 'vfndow' },
    storageBlobDataReader: { defaultMessage: 'Storage Blob Data Reader', id: 'Q3p3sz' },
    storageBlobDataReaderDescription: {
        defaultMessage: 'Allows for read access to Azure Storage blob containers and data.',
        id: '4ii5zj',
    },
    monitoringReader: { defaultMessage: 'Monitoring Reader', id: 'Sr4IbA' },
    monitoringReaderDescription: { defaultMessage: 'Can read all monitoring data.', id: 'xdMkcg' },
    storageAccountContributor: { defaultMessage: 'Storage Account Contributor', id: 'cTzjJg' },
    storageAccountContributorDescription: {
        defaultMessage:
            'Lets you manage storage accounts, including accessing storage account keys which provide full access to storage account data.',
        id: 'xXhn+h',
    },
    virtualMachineContributor: { defaultMessage: 'Virtual Machine Contributor', id: 'PXg8+x' },
    virtualMachineContributorDescription: {
        defaultMessage:
            'Lets you manage virtual machines, but not access to them, and not the virtual network or storage account they are connected to.',
        id: 'AeWmvh',
    },
    postgreSqlFlexibleServerLongTermRetentionBackupRole: {
        defaultMessage: 'PostgreSQL Flexible Server Long Term Retention Backup Role',
        id: 'WLw9E7',
    },
    postgreSqlFlexibleServerLongTermRetentionBackupRoleDescription: {
        defaultMessage: 'Manage long-term retention backups for PostgreSQL Flexible Server.',
        id: 'XtnlO8',
    },
    sqlManagedInstanceContributor: { defaultMessage: 'SQL Managed Instance Contributor', id: 'SuVToZ' },
    sqlManagedInstanceContributorDescription: { defaultMessage: 'Manage SQL Managed Instances.', id: '/8MshI' },
    sqlServerContributor: { defaultMessage: 'SQL Server Contributor', id: 'ss/NWY' },
    sqlServerContributorDescription: { defaultMessage: 'Manage SQL servers and their security policies.', id: '0Dhe75' },
    dataFactoryContributor: { defaultMessage: 'Data Factory Contributor', id: 'Wtf3vL' },
    dataFactoryContributorDescription: { defaultMessage: 'Manage Azure Data Factory instances.', id: '0te2Ra' },
    hdInsightOnAksClusterAdmin: { defaultMessage: 'HDInsight on AKS Cluster Admin', id: 'NcxGiD' },
    hdInsightOnAksClusterAdminDescription: { defaultMessage: 'Administer HDInsight clusters on AKS.', id: 'ixb1SP' },
    hdInsightOnAksClusterPoolAdmin: { defaultMessage: 'HDInsight on AKS Cluster Pool Admin', id: 'pAFuFx' },
    hdInsightOnAksClusterPoolAdminDescription: { defaultMessage: 'Administer HDInsight cluster pools.', id: 'WygVDv' },
    azureMlComputeOperator: { defaultMessage: 'AzureML Compute Operator', id: 'Wc5b/J' },
    azureMlComputeOperatorDescription: { defaultMessage: 'Operate Azure Machine Learning compute resources.', id: 'ciB+oy' },
    azureMlDataScientist: { defaultMessage: 'AzureML Data Scientist', id: 'l5sNim' },
    azureMlDataScientistDescription: { defaultMessage: 'Perform data science tasks in Azure Machine Learning.', id: 'i6cLLM' },
    cognitiveServicesContributor: { defaultMessage: 'Cognitive Services Contributor', id: 'Dff3ms' },
    cognitiveServicesContributorDescription: { defaultMessage: 'Manage Cognitive Services accounts.', id: 'wxlJSs' },
    cognitiveServicesOpenAiContributor: { defaultMessage: 'Cognitive Services OpenAI Contributor', id: 'HQhDfV' },
    cognitiveServicesOpenAiContributorDescription: { defaultMessage: 'Manage Azure OpenAI resources.', id: 'ZsLOg3' },
    cognitiveServicesCustomVisionContributor: {
        defaultMessage: 'Cognitive Services Custom Vision Contributor',
        id: '7+b0J0',
    },
    cognitiveServicesCustomVisionContributorDescription: {
        defaultMessage: 'Manage Custom Vision projects.',
        id: '/gCtdO',
    },
    cognitiveServicesLanguageWriter: { defaultMessage: 'Cognitive Services Language Writer', id: 'aqNZbD' },
    cognitiveServicesLanguageWriterDescription: {
        defaultMessage: 'Write access to Language service resources.',
        id: 'CMaDRa',
    },
    cognitiveServicesLuisWriter: { defaultMessage: 'Cognitive Services LUIS Writer', id: '64zSh3' },
    cognitiveServicesLuisWriterDescription: { defaultMessage: 'Write access to LUIS applications.', id: 'cRTR/A' },
    cognitiveServicesQnaMakerEditor: { defaultMessage: 'Cognitive Services QnA Maker Editor', id: 'rjgOC5' },
    cognitiveServicesQnaMakerEditorDescription: { defaultMessage: 'Edit QnA Maker knowledge bases.', id: 'mAyw3x' },
    cognitiveServicesSpeechContributor: { defaultMessage: 'Cognitive Services Speech Contributor', id: 'fFyuVF' },
    cognitiveServicesSpeechContributorDescription: {
        defaultMessage: 'Contribute to Speech service resources.',
        id: '6YXj/s',
    },
    healthcareAgentEditor: { defaultMessage: 'Healthcare Agent Editor', id: 't9I1dY' },
    healthcareAgentEditorDescription: { defaultMessage: 'Edit Healthcare APIs agent configurations.', id: 'Phji5P' },
    searchServiceContributor: { defaultMessage: 'Search Service Contributor', id: 'P3qxV2' },
    searchServiceContributorDescription: { defaultMessage: 'Manage Azure Search services.', id: 'ecG+OD' },
    azureDigitalTwinsDataOwner: { defaultMessage: 'Azure Digital Twins Data Owner', id: 'QIY3dQ' },
    azureDigitalTwinsDataOwnerDescription: { defaultMessage: 'Full access to Azure Digital Twins data.', id: '87v+WY' },
    deviceProvisioningServiceDataContributor: {
        defaultMessage: 'Device Provisioning Service Data Contributor',
        id: '5UfRjw',
    },
    deviceProvisioningServiceDataContributorDescription: {
        defaultMessage: 'Manage Device Provisioning Service data.',
        id: '7N87nD',
    },
    deviceUpdateAdministrator: { defaultMessage: 'Device Update Administrator', id: 'e3itcX' },
    deviceUpdateAdministratorDescription: { defaultMessage: 'Administer Device Update accounts.', id: 'hF5T80' },
    iotHubDataContributor: { defaultMessage: 'IoT Hub Data Contributor', id: 'xqwf/7' },
    iotHubDataContributorDescription: { defaultMessage: 'Full access to IoT Hub data.', id: 'R1RX2a' },
    iotHubRegistryContributor: { defaultMessage: 'IoT Hub Registry Contributor', id: 'lvNWLS' },
    iotHubRegistryContributorDescription: { defaultMessage: 'Manage IoT Hub device registry.', id: '2PnnDB' },
    iotHubTwinContributor: { defaultMessage: 'IoT Hub Twin Contributor', id: '5Sc5rT' },
    iotHubTwinContributorDescription: { defaultMessage: 'Manage IoT Hub device twins.', id: 'gZ5fZs' },
    apiManagementServiceContributor: { defaultMessage: 'API Management Service Contributor', id: 'rZaqtB' },
    apiManagementServiceContributorDescription: { defaultMessage: 'Manage API Management services.', id: 'dR8VUW' },
    apiManagementServiceOperatorRole: { defaultMessage: 'API Management Service Operator Role', id: 'yo67XU' },
    apiManagementServiceOperatorRoleDescription: { defaultMessage: 'Operate API Management services.', id: 'xmsrBu' },
    apiManagementWorkspaceContributor: { defaultMessage: 'API Management Workspace Contributor', id: 'EdEthU' },
    apiManagementWorkspaceContributorDescription: { defaultMessage: 'Manage API Management workspaces.', id: 'd2GmfJ' },
    appConfigurationContributor: { defaultMessage: 'App Configuration Contributor', id: 'IEFW3Y' },
    appConfigurationContributorDescription: { defaultMessage: 'Manage App Configuration stores.', id: '2LQx4N' },
    azureServiceBusDataOwner: { defaultMessage: 'Azure Service Bus Data Owner', id: 'H3ooTI' },
    azureServiceBusDataOwnerDescription: { defaultMessage: 'Full access to Azure Service Bus data.', id: 'nrAnZy' },
    logicAppContributor: { defaultMessage: 'Logic App Contributor', id: 'C3PGqj' },
    logicAppContributorDescription: { defaultMessage: 'Manage Logic Apps.', id: 'ZNMCbm' },
    workbookContributor: { defaultMessage: 'Workbook Contributor', id: '4MeTpL' },
    workbookContributorDescription: { defaultMessage: 'Manage Azure Monitor workbooks.', id: 'Z7Aj91' },
    azureCenterForSapSolutionsAdministrator: {
        defaultMessage: 'Azure Center for SAP solutions administrator',
        id: 'Yp7NCi',
    },
    azureCenterForSapSolutionsAdministratorDescription: {
        defaultMessage: 'Administer SAP workloads on Azure.',
        id: 'wbigtI',
    },
    costManagementContributor: { defaultMessage: 'Cost Management Contributor', id: 'oQ/TUW' },
    costManagementContributorDescription: { defaultMessage: 'Manage cost analysis and budgets.', id: 'sRb5P9' },
    // Reader roles
    hdInsightClusterOperator: { defaultMessage: 'HDInsight Cluster Operator', id: 'xGPsyJ' },
    hdInsightClusterOperatorDescription: {
        defaultMessage: 'Lets you read and modify HDInsight cluster configurations.',
        id: 'XJ+Lww',
    },
    cognitiveServicesCustomVisionReader: { defaultMessage: 'Cognitive Services Custom Vision Reader', id: 'u0xiAh' },
    cognitiveServicesCustomVisionReaderDescription: {
        defaultMessage: "Read-only actions in the project. Readers can't create or update the project.",
        id: 'eBvTo6',
    },
    cognitiveServicesDataReader: { defaultMessage: 'Cognitive Services Data Reader', id: 'SCjiXP' },
    cognitiveServicesDataReaderDescription: { defaultMessage: 'Lets you read Cognitive Services data.', id: 'IQaKwH' },
    cognitiveServicesLanguageReader: { defaultMessage: 'Cognitive Services Language Reader', id: '8NHZQV' },
    cognitiveServicesLanguageReaderDescription: {
        defaultMessage: 'Has access to Read and Test functions under Language portal.',
        id: 'vbdOl/',
    },
    cognitiveServicesLuisReader: { defaultMessage: 'Cognitive Services LUIS Reader', id: 'Pwen/L' },
    cognitiveServicesLuisReaderDescription: {
        defaultMessage: 'Has access to Read and Test functions under LUIS.',
        id: 'aGL+Qo',
    },
    cognitiveServicesQnaMakerReader: { defaultMessage: 'Cognitive Services QnA Maker Reader', id: 'Yk6Co7' },
    cognitiveServicesQnaMakerReaderDescription: {
        defaultMessage: "Let's you read and test a KB only.",
        id: 'Dx3Xj3',
    },
    cognitiveServicesUsagesReader: { defaultMessage: 'Cognitive Services Usages Reader', id: 'c1EiBR' },
    cognitiveServicesUsagesReaderDescription: {
        defaultMessage: 'Minimal permission to view Cognitive Services usages.',
        id: 'GoSIa4',
    },
    searchIndexDataReader: { defaultMessage: 'Search Index Data Reader', id: 'j5Yfyr' },
    searchIndexDataReaderDescription: {
        defaultMessage: 'Grants read access to Azure Cognitive Search index data.',
        id: 'pSfQh6',
    },
    azureDigitalTwinsDataReader: { defaultMessage: 'Azure Digital Twins Data Reader', id: 'hrdmcd' },
    azureDigitalTwinsDataReaderDescription: {
        defaultMessage: 'Read-only role for Digital Twins data-plane properties.',
        id: 'CFJ1OD',
    },
    deviceProvisioningServiceDataReader: { defaultMessage: 'Device Provisioning Service Data Reader', id: 'bN0x+w' },
    deviceProvisioningServiceDataReaderDescription: {
        defaultMessage: 'Allows for full read access to Device Provisioning Service data-plane properties.',
        id: 'dQ5/dh',
    },
    deviceUpdateReader: { defaultMessage: 'Device Update Reader', id: 't3D4PH' },
    deviceUpdateReaderDescription: {
        defaultMessage: 'Gives you read access to management and content operations, but does not allow making changes.',
        id: '+/nU/s',
    },
    iotHubDataReader: { defaultMessage: 'IoT Hub Data Reader', id: 'd8dECB' },
    iotHubDataReaderDescription: {
        defaultMessage: 'Allows for full read access to IoT Hub data-plane properties.',
        id: 'KAYpG9',
    },
    apiManagementServiceReader: { defaultMessage: 'API Management Service Reader Role', id: '4TnjxL' },
    apiManagementServiceReaderDescription: { defaultMessage: 'Read-only access to service and APIs.', id: '8aHHLj' },
    apiManagementWorkspaceReader: { defaultMessage: 'API Management Workspace Reader', id: 'XYSJsS' },
    apiManagementWorkspaceReaderDescription: {
        defaultMessage: 'Has read-only access to entities in the workspace. This role should be assigned on the workspace scope.',
        id: 'UZS12+',
    },
    appConfigurationReader: { defaultMessage: 'App Configuration Reader', id: 'pDUFq5' },
    appConfigurationReaderDescription: {
        defaultMessage: 'Grants permission for read operations for App Configuration resources.',
        id: 'ENnkRe',
    },
    logicAppOperator: { defaultMessage: 'Logic App Operator', id: 'T5+AEf' },
    logicAppOperatorDescription: { defaultMessage: 'Lets you read, enable and disable logic app.', id: '01lT1B' },
    workbookReader: { defaultMessage: 'Workbook Reader', id: 'hPj49L' },
    workbookReaderDescription: { defaultMessage: 'Can read workbooks.', id: '+l+XEu' },
    azureCenterForSapSolutionsReader: { defaultMessage: 'Azure Center for SAP solutions reader', id: 'BKSv0l' },
    azureCenterForSapSolutionsReaderDescription: {
        defaultMessage: 'This role provides read access to all capabilities of Azure Center for SAP solutions.',
        id: 'NAAdaF',
    },
    costManagementReader: { defaultMessage: 'Cost Management Reader', id: '5wGcN7' },
    costManagementReaderDescription: {
        defaultMessage: 'Can view cost data and configuration (e.g. budgets, exports).',
        id: '3t/IhV',
    },
});
