import { defineMessages } from 'react-intl';

export const PortalResources = defineMessages({
    azureSreAgents: {
        defaultMessage: 'Azure SRE Agents',
        id: 'He4/qi',
    },
    azureSreAgent: { defaultMessage: 'Azure SRE Agent', id: 'Erci0g' },
    add: { defaultMessage: 'Add', id: '2/2yg+' },
    agents: { defaultMessage: 'Agents', id: 'GBnvl1' },
    agentName: { defaultMessage: 'Agent name', id: 'ctcA0c' },
    docs: { defaultMessage: 'Docs', id: '/6/sPX' },
    enterName: { defaultMessage: 'Enter name', id: 'OJ2u8k' },
    subscription: { defaultMessage: 'Subscription', id: 'R/6nsx' },
    resourceGroup: { defaultMessage: 'Resource group', id: '+uAdUZ' },
    agentPermissions: { defaultMessage: 'Agent permissions', id: 'qGXY+e' },
    back: { defaultMessage: 'Back', id: 'cyR7Kh' },
    basics: { defaultMessage: 'Basics', id: 'itC9lG' },
    next: { defaultMessage: 'Next', id: '9+Ddtu' },
    cancel: { defaultMessage: 'Cancel', id: '47FYwb' },
    create: { defaultMessage: 'Create', id: 'VzzYJk' },
    createNew: { defaultMessage: 'Create new', id: '5WK7jL' },
    filterItems: { defaultMessage: 'Filter items...', id: 'DdD2hE' },
    signOut: { defaultMessage: 'Sign out', id: 'xXbJso' },
    signInWithDifferentAccount: { defaultMessage: 'Sign in with a different account', id: 'oHGFwy' },
    signIn: { defaultMessage: 'Sign in', id: 'SQJto2' },
    chatWithAgent: { defaultMessage: 'Chat with agent', id: 'arLfuy' },
    close: { defaultMessage: 'Close', id: 'rbrahO' },
    createYourFirstAgent: { defaultMessage: 'Create your first Azure SRE Agent', id: 'H/i1A+' },
    createYourFirstAgentSubtext: {
        defaultMessage:
            'Azure SRE Agents reduce site reliability costs by proactively identifying issues, automating tasks, and preventing downtime.',
        id: 'TleXgd',
    },
    createAgent: { defaultMessage: 'Create agent', id: 'UrGI9K' },
    viewPopularSkills: { defaultMessage: 'View popular skills', id: 'Ch3IdZ' },
    settings: { defaultMessage: 'Settings', id: 'D3idYv' },
    portalFeedback: { defaultMessage: 'Portal feedback', id: '2GuZPR' },
    feedbackSubmitted: { defaultMessage: 'Thank you for your feedback!', id: 'Nrc9ba' },
    feedbackPlaceholder: { defaultMessage: 'Share your thoughts about the portal...', id: 'tYoDsC' },
    positive: { defaultMessage: 'Positive', id: 'dHVUaP' },
    negative: { defaultMessage: 'Negative', id: 'kVQ1fo' },
    submit: { defaultMessage: 'Submit', id: 'wSZR47' },
    themes: { defaultMessage: 'Themes', id: 'Avsnjl' },
    system: { defaultMessage: 'System', id: '+CwN9C' },
    light: { defaultMessage: 'Light', id: '3cc4Ct' },
    dark: { defaultMessage: 'Dark', id: 'tOdNiY' },
    language: { defaultMessage: 'Language', id: 'y1Z3or' },
    reduceSiteReliabilityExpenses: {
        defaultMessage: 'Reduce site reliability expenses with Azure SRE Agents',
        id: 's7mQCK',
    },
    reduceSiteReliabilityExpensesDescription: {
        defaultMessage:
            'Azure SRE Agents reduce site reliability costs by proactively identifying issues, automating tasks, and preventing downtime.',
        id: 'TleXgd',
    },
    review: { defaultMessage: 'Review', id: 'R+J5ox' },
    tryAzureForFree: { defaultMessage: 'Try Azure for free', id: 'wCtBb6' },
    exploreAgentSkills: { defaultMessage: 'Explore agent skills', id: 'i50Kb0' },
    privacyAndCookies: { defaultMessage: 'Privacy & cookies', id: 'DdnNXo' },
    termsAndConditions: { defaultMessage: 'Terms & conditions', id: 'bPyOFk' },
    trademarks: { defaultMessage: 'Trademarks', id: 'I6cq17' },
    notifications: { defaultMessage: 'Notifications', id: 'NAidKb' },
    dismissAll: { defaultMessage: 'Dismiss all', id: 'eHNXXp' },
    dismissCompleted: { defaultMessage: 'Dismiss completed', id: 'P/DTRU' },
    noNotifications: { defaultMessage: 'No notifications', id: 'fpexn2' },
    noNotificationsDescription: {
        defaultMessage: 'Notifications will appear here when actions are performed',
        id: 'W4H4Z9',
    },
    getMoreInfo: { defaultMessage: 'Get more info', id: 'TB6bkn' },
    dismiss: { defaultMessage: 'Dismiss', id: 'TDaF6J' },
    justNow: { defaultMessage: 'Just now', id: 'bxv59V' },
    secondsAgo: {
        defaultMessage: '{count, plural, one {# second ago} other {# seconds ago}}',
        id: 'sYoT7W',
    },
    unexpectedErrorOccurred: { defaultMessage: 'An unexpected error occurred', id: '3IKub9' },
    backToHome: { defaultMessage: 'Back to home', id: 'aIRWQB' },
    minutesAgo: {
        defaultMessage: '{count, plural, one {# minute ago} other {# minutes ago}}',
        id: 'aLBTVj',
    },
    hoursAgo: {
        defaultMessage: '{count, plural, one {# hour ago} other {# hours ago}}',
        id: 'LupnQU',
    },
    daysAgo: {
        defaultMessage: '{count, plural, one {# day ago} other {# days ago}}',
        id: '8OCpdQ',
    },
    none: { defaultMessage: 'None', id: '450Fty' },
    requestError: { defaultMessage: 'Request error', id: 'UQUIP7' },
    name: { defaultMessage: 'Name', id: 'HAlOn1' },
    region: { defaultMessage: 'Region', id: 'lnaWo/' },
    whitelistErrorMessage: {
        defaultMessage:
            'This subscription is not currently whitelisted to use SRE Agent. Please contact your administrator or support team to request access.',
        id: 'Kbdzt3',
    },
    iframeUnauthorizedMessage: {
        defaultMessage:
            'We were unable to load the URL {agentUxUrl}. This may be due to the existence of a firewall or network restrictions placed on the domain of your agent. Please speak to your network administrator to remove this restriction in order to proceed with interacting with your agent.',
        id: 'kbQZUj',
    },
    iframeZscalerUnauthorizedMessage: {
        defaultMessage:
            "We were unable to load the URL {agentUxUrl}. We've detected that your organization has selected Zscaler to protect you from unknown domains. Please speak to your network administrator to remove the restriction on this domain in order to proceed with interacting with your agent.",
        id: 'GDEEBE',
    },
    operationCancelled: { defaultMessage: 'Operation cancelled', id: 'g82HU6' },
    directory: { defaultMessage: 'Directory', id: 'RDwKyy' },
    search: { defaultMessage: 'Search', id: 'xmcVZ0' },
    allSubscriptions: { defaultMessage: 'All subscriptions', id: '8yyU6n' },
    allResourceGroups: { defaultMessage: 'All resource groups', id: 'jEU2gk' },
    allRegions: { defaultMessage: 'All regions', id: '456ixe' },
    managedResourceGroups: { defaultMessage: 'Managed resource groups', id: 'yilQrD' },
    fieldRequired: { defaultMessage: 'This field is required.', id: '6B5Jtu' },
    sreAgentNameMinMax: { defaultMessage: 'Name must be between 2 and 32 characters', id: '+YDzOd' },
    sreAgentNameAlreadyExists: { defaultMessage: 'An agent with this name already exists in the selected resource group.', id: 'ceCESY' },
    resourceGroupDenyAssignmentError: {
        defaultMessage: 'Some of the selected resource groups have deny assignments that prevent deployments.',
        id: 'GWson9',
    },
    sreAgentNameValidation: {
        defaultMessage:
            'The name must begin and end with a lowercase letter, and contain only lowercase letters, numbers, and hyphens. It cannot contain consecutive hyphens.',
        id: 'B6aNdQ',
    },
    expand: { defaultMessage: 'Expand', id: '0oLj/t' },
    collapse: { defaultMessage: 'Collapse', id: 'W/V6+Y' },
    sreAgentLocationsLoadFailure: { defaultMessage: 'Failed to load SRE Agent locations. Please try again later.', id: 'WE+M5j' },
    yes: { defaultMessage: 'Yes', id: 'a5msuh' },
    no: { defaultMessage: 'No', id: 'oUWADl' },
    selectASubscription: { defaultMessage: 'Select a subscription', id: 'LrnSHG' },
    selectAnExistingResourceGroup: { defaultMessage: 'Select an existing resource group', id: 'LkSPVW' },
    selectRegion: { defaultMessage: 'Select region', id: 'tshYzs' },
    registrationFailed: { defaultMessage: 'Registration failed', id: 'G7yB8N' },
    loading: { defaultMessage: 'Loading', id: 'iFsDVR' },
    noResultsFound: { defaultMessage: 'No results found', id: 'hX5PAb' },
    noResourceGroupCreatePermission: {
        defaultMessage: 'You do not have permission to create resource groups under the currently selected subscription.',
        id: 'uqyJPP',
    },
    copy: { defaultMessage: 'Copy', id: '4l6vz1' },
    copied: { defaultMessage: 'Copied', id: 'p556q3' },
    copyToClipboard: { defaultMessage: 'Copy to clipboard', id: 'aCdAsI' },
    sessionId: { defaultMessage: 'Session ID', id: 'b0v+Pu' },
    getSupport: { defaultMessage: 'Get support', id: 'Km7x3v' },
    newItemFormat: { defaultMessage: '(new) {item}', id: 'zJ+8HW' },
    resourceGroupAlreadyExistsInSubscription: {
        defaultMessage: 'A resource group with this name already exists in the selected subscription.',
        id: 'If+Q1B',
    },
    policyErrorFormattedMessage: {
        defaultMessage: "Deployment to this resource group will be blocked by policy: '{field} not allowed'. Policy Assignment ID: {id}",
        id: '75IWbW',
    },
    allowlistWarning: {
        defaultMessage:
            'The subscription you have selected has not been registered to use SRE Agent. Please email us with your subscription ID on sreagentteam@microsoft.com for getting registered.',
        id: 'r0gBch',
    },
    reader: { defaultMessage: 'Reader', id: '3nhWFW' },
    readerDescription: {
        defaultMessage:
            "The agent has read-only permissions on the resource groups it manages. It takes the user's permissions temporarily for approved actions.",
        id: 'C0ZRdE',
    },
    privileged: { defaultMessage: 'Privileged', id: 'TDoBlx' },
    privilegedDescription: {
        defaultMessage:
            'The agent has permissions to take approved actions on resources and resource types detected in its assigned resource groups.',
        id: '3tJfza',
    },
    permissionsLevel: { defaultMessage: 'Agent permissions level', id: '+bJIWo' },
    permissionsDescription: {
        defaultMessage:
            'Assign the agent a level of permissions for the resource groups it manages. The agent can still manage its assigned resources with Reader permissions.',
        id: 'hswM/b',
    },
    learnMoreAboutAgentPermissions: { defaultMessage: 'Learn more about Reader and Privileged permissions', id: 'vu2LMl' },
    registrationFailedMessage: {
        defaultMessage:
            'We were unable to register the Microsoft.App RP due to a lack of permissions which may cause your deployment to fail. Ensure that you have Contributor permissions to this subscription or have your subscription administrator register the RP for you.',
        id: 'GmzN3r',
    },
    doYouWantToContinue: { defaultMessage: 'Do you want to continue?', id: 'xHDoP8' },
    managedResourceGroupDescription: {
        defaultMessage:
            'To assign the agent managed resource groups across subscriptions, you need Owner or User Access Administrator permissions on those resource groups. The agent resource and managed resource groups can be in different regions and subscriptions.',
        id: 'sRU00i',
    },
    learnMoreAboutManagedRgPermissions: { defaultMessage: 'Learn more about permissions for managed resource groups', id: 'ru0BPw' },
    resourceGroupNameLinkAriaLabel: { defaultMessage: 'Open resource group', id: 'tffS9r' },
    readOnlyLock: { defaultMessage: 'Read only lock', id: 'fIp46f' },
    denyAssignments: { defaultMessage: 'Deny assignments', id: 'iM9JZL' },
    policyErrors: { defaultMessage: 'Denied by policy', id: 'ASEuj4' },
    resourceGroupLockError: {
        defaultMessage: 'Some of the selected resource groups have a read only lock on the resource group.',
        id: 'YYx7ap',
    },
    resourceGroupPermissionError: {
        defaultMessage: 'Choose at least 1 resource group that you have Owner or User Access Administrator permissions on.',
        id: 'kyVg+J',
    },
    resourceGroupPolicyError: {
        defaultMessage: 'Some of the selected resource groups have policies that will cause the deployment to fail.',
        id: '+Ov1f1',
    },
    resourceGroupMaxError: { defaultMessage: 'You can choose a maximum of 100 resource groups that the agent will manage.', id: 'axbDHG' },
    removeResourceGroup: { defaultMessage: 'Remove resource group', id: '4USxEK' },
    userPermissions: { defaultMessage: 'User permissions', id: '5M+hLZ' },
    managedResourceGroupsTableAriaLabel: { defaultMessage: 'Managed resource groups table', id: 'V/rQci' },
    agentDetails: { defaultMessage: 'Agent details', id: 'Wf6bDe' },
    // PillFilter strings
    all: { defaultMessage: 'All', id: 'zQvVDJ' },
    noResults: { defaultMessage: 'No results', id: 'jHJmjf' },
    apply: { defaultMessage: 'Apply', id: 'EWw/tK' },
    equals: { defaultMessage: 'equals', id: 'Y2QRpS' },
    selectedOutOfTotal: { defaultMessage: '{selectedCount} of {totalCount}', id: '01sZoP' },
    optionsListAriaLabel: { defaultMessage: '{fieldName} options', id: 'dDk23i' },
    pillFilterAriaLabel: {
        defaultMessage: 'Editor to filter the results by column value. {columnName}{delimiter} {filterValue}',
        id: '5j5HnL',
    },
    pillFilterRemoveAriaLabel: { defaultMessage: 'Remove {columnName} filter', id: '/ytgXm' },
    // Resource Group Picker strings
    selectResourceGroupsToMonitor: { defaultMessage: 'Select resource groups to monitor', id: 'CfGC/2' },
    resourceGroupName: { defaultMessage: 'Resource group name', id: 'xVPoso' },
    save: { defaultMessage: 'Save', id: 'jvo0vs' },
    selectAll: { defaultMessage: 'Select all', id: '94Fg25' },
    resourceGroupPickerTitle: { defaultMessage: 'Select resource groups', id: 'ftfFhS' },
    resourceGroupsMax: { defaultMessage: 'Select up to 100 resource groups to monitor', id: 'dKhdkO' },
    resourceGroupSelected: { defaultMessage: '{0} resource group selected', id: 'nlPgO8' },
    resourceGroupsSelected: { defaultMessage: '{0} resource groups selected', id: 'egr0Oj' },
    showRecommended: { defaultMessage: 'Show only recommended', id: 'UoL653' },
    toggleShowRecommendedAriaLabel: { defaultMessage: 'Toggle to show only recommended resource groups', id: 'Kg6ebk' },
    searchResourceGroups: { defaultMessage: 'Search resource groups', id: 'pMlVvA' },
    resourceGroupPickerTableAriaLabel: { defaultMessage: 'Resource groups list', id: 'Ngsqgf' },
    resourceGroupPickerDialogAriaLabel: { defaultMessage: 'Select resource groups dialog', id: '2xRon3' },
    recommendedResourceGroupTooltip: {
        defaultMessage: 'This resource group contains resources supported by SRE Agent',
        id: 'CrmeG3',
    },
});

export const ResourceTypeNameResources = defineMessages({
    website: { defaultMessage: 'App Services', id: 'UVD6yh' },
    functionApp: { defaultMessage: 'Function Apps', id: 'L31yBb' },
    storageAccounts: { defaultMessage: 'Storage Accounts', id: '5UUKxL' },
    storageBlobContainers: { defaultMessage: 'Storage Blob Containers', id: '43mD/Y' },
    cosmosDbAccounts: { defaultMessage: 'Cosmos DB Accounts', id: '+zgzmq' },
    sqlServers: { defaultMessage: 'SQL Servers', id: 'zhHihn' },
    sqlDatabases: { defaultMessage: 'SQL Databases', id: 'bXkiU5' },
    sqlManagedInstances: { defaultMessage: 'SQL Managed Instances', id: 'X0e0bZ' },
    aksClusters: { defaultMessage: 'AKS Clusters', id: 'FqRdvb' },
    containerApps: { defaultMessage: 'Container Apps', id: '+TlNdm' },
    redisCache: { defaultMessage: 'Redis Cache', id: 'cmUVb9' },
    virtualMachines: { defaultMessage: 'Virtual Machines', id: 'zEk9h3' },
    postgreSqlFlexibleServers: { defaultMessage: 'PostgreSQL Flexible Servers', id: '1myzs4' },
    postgreSqlServers: { defaultMessage: 'PostgreSQL Servers', id: '/wY7pG' },
    dataFactories: { defaultMessage: 'Data Factories', id: 'C8z3QQ' },
    machineLearningWorkspaces: { defaultMessage: 'Machine Learning Workspaces', id: 'AVMCsG' },
    cognitiveServices: { defaultMessage: 'Cognitive Services', id: 'fSFDgd' },
    searchServices: { defaultMessage: 'Search Services', id: 'ufonOZ' },
    digitalTwins: { defaultMessage: 'Digital Twins', id: '2do8JC' },
    iotHubs: { defaultMessage: 'IoT Hubs', id: 'uh732n' },
    apiManagement: { defaultMessage: 'API Management', id: 'iv5NrP' },
    appConfiguration: { defaultMessage: 'App Configuration', id: 'KJGQ1f' },
    serviceBus: { defaultMessage: 'Service Bus', id: 's0xRD+' },
    logicApps: { defaultMessage: 'Logic Apps', id: 'TzxmIN' },
    applicationInsights: { defaultMessage: 'Application Insights', id: 'WFo96A' },
    logAnalyticsWorkspaces: { defaultMessage: 'Log Analytics Workspaces', id: 'WlHVBb' },
    insights: { defaultMessage: 'App Insights', id: 'hGmeVK' },
    workbooks: { defaultMessage: 'Workbooks', id: 'HCDcpW' },
    sapVirtualInstances: { defaultMessage: 'SAP Virtual Instances', id: 'b43a5F' },
    costManagement: { defaultMessage: 'Cost Management', id: '69g7If' },
});

export const AgentCreateDeploymentNotificationResources = defineMessages({
    agentCreationTitle: { defaultMessage: 'Provisioning SRE Agent', id: '/6Fckw' },
    agentCreationInProgress: {
        defaultMessage: "We've started provisioning your SRE Agent {agentName} to manage your selected resource groups.",
        id: 'pVF2EE',
    },
    agentCreatedSuccessDescription: { defaultMessage: 'SRE Agent {agentName} creation succeeded', id: 'WODKUB' },
    agentCreationFailedDescription: {
        defaultMessage: 'Failed to create the SRE agent {agentName} with the error: {error}',
        id: 'YYWhEp',
    },
    agentCreationValidationTitle: { defaultMessage: 'Validating SRE Agent creation', id: 'OsTw6c' },
    agentCreationValidationInProgress: {
        defaultMessage: 'Validating SRE Agent {agentName} creation in progress',
        id: 'lcvC4k',
    },
    agentCreationValidationSuccessDescription: {
        defaultMessage: 'SRE Agent {agentName} creation validation succeeded',
        id: 'NCTGGm',
    },
    agentCreationValidationRPFailureDescription: {
        defaultMessage:
            'Failed to register Microsoft.App RP for SRE Agent {agentName} creation. Please ensure you have Contributor permissions on the subscription or contact your subscription administrator to register the RP for you.',
        id: 'QwVQbw',
    },
    agentCreationValidationFailedDescription: {
        defaultMessage: 'Failed to validate SRE Agent {agentName} creation with the error: {error}',
        id: 'lNehTG',
    },
    identityFailedDescription: { defaultMessage: 'Failed to setup Managed Identity with the error: {error}', id: 'UuzObe' },
    workspaceFailedDescription: {
        defaultMessage: 'Failed to setup Log Analytics Workspace with the error: {error}',
        id: 'oThNc4',
    },
    templateBuilderFailedDescription: { defaultMessage: 'Invalid template or unable to fetch the template.', id: 'VssvTa' },
    templateBuilderFailedTitle: { defaultMessage: 'Template error', id: 'eKpamp' },
    resourceGroupFailedDescription: { defaultMessage: 'Resource group creation failed.', id: 'jjUD0v' },
    resourceGroupFailedTitle: { defaultMessage: 'Resource group creation', id: 'pW5vuU' },
});

export const DeployResources = defineMessages({
    deploy: { defaultMessage: 'Deploy', id: '556JQK' },
    deploymentName: { defaultMessage: 'Deployment name', id: 'OjYIuI' },
    correlationId: { defaultMessage: 'Correlation ID', id: 'p849eW' },
    startTime: { defaultMessage: 'Start time', id: '/zFP1/' },
    deploymentInProgress: { defaultMessage: 'Deployment in progress...', id: 'gty4jJ' },
    deploymentSucceeded: { defaultMessage: 'Deployment succeeded', id: 'v90qT8' },
    deploymentFailed: { defaultMessage: 'Deployment failed', id: '9M3sYh' },
    resourceOperations: { defaultMessage: 'Resource operations', id: 'czVHN2' },
    creating: { defaultMessage: 'Creating', id: 'xhfdqv' },
    created: { defaultMessage: 'Created', id: 'ORGv1Q' },
    failed: { defaultMessage: 'Failed', id: 'vXCeIi' },
    updating: { defaultMessage: 'Updating', id: 'S8snIe' },
    running: { defaultMessage: 'Running', id: 'nDyaq/' },
    succeeded: { defaultMessage: 'Succeeded', id: 'LOghU6' },
    noOperations: { defaultMessage: 'No operations found', id: 'vxVGav' },
    loadingOperations: { defaultMessage: 'Loading operations...', id: '1Lx9q5' },
});

export const RolesAndPermissions = defineMessages({
    loadingResourceTypes: { defaultMessage: 'Loading resource types...', id: 'q7CVBv' },
    detectedResourceTypes: { defaultMessage: 'Detected resource types', id: 'zacv31' },
    role: { defaultMessage: 'Role', id: '1ZgrhW' },
    description: { defaultMessage: 'Description', id: 'Q8Qw5B' },
    permissionsTableAriaLabel: { defaultMessage: 'Agent permissions and roles table', id: 'Ab4TgE' },
    currentAgentCount: { defaultMessage: 'Current agent count', id: 'Xh85Ml' },
    maxAgentCount: { defaultMessage: 'Max agent count', id: 'AhdXRl' },
    policies: { defaultMessage: 'Policies', id: 'yV5oYe' },
    genevaActionsConfiguration: { defaultMessage: 'Geneva actions configuration', id: '1t2BaF' },
    authenticationMode: { defaultMessage: 'Authentication mode', id: 'Z2WgoK' },
    extensionName: { defaultMessage: 'Extension name', id: 'oIiHqo' },
    acisEndpoint: { defaultMessage: 'ACIS endpoint', id: 'pM3DKw' },
    clientId: { defaultMessage: 'Client ID', id: 'U5+MBC' },
    allowedActions: { defaultMessage: 'Allowed Actions', id: 'n/e5Mg' },
    approvalRequired: { defaultMessage: 'Approval Required', id: 'G1xeUt' },
    certificateSubjectAlternativeName: { defaultMessage: 'Certificate SAN', id: 's2jhon' },
    genevaActionsCertificateName: { defaultMessage: 'Geneva Actions Certificate Name', id: 'x2Qj1F' },
    readOnlyModeDescription: {
        defaultMessage:
            'Your agent is in read-only mode. The following permissions are required for the agent to build knowledge about your resources. The contributor roles for specific services will not be used to perform any write operations.',
        id: 'P9odAr',
    },
    reviewModeDescription: {
        defaultMessage:
            'Your agent is in review mode. The following permissions are required for the agent to build knowledge about your resources. The agent will use some of these permissions to perform write operations with your approval based on your requests.',
        id: 'p/xAmY',
    },
    autonomousModeDescription: {
        defaultMessage:
            'Your agent is in autonomous mode. The following permissions are required for the agent to build knowledge about your resources. The agent will use some of these permissions to perform write operations autonomously based on your requests.',
        id: '/dxZCE',
    },
    rolesAndPermissionsDescription: {
        defaultMessage: 'The resources you picked have permissions for these roles.',
        id: 'OTGHHm',
    },
    noRolesAndPermissions: {
        defaultMessage: 'To view the roles and permissions the agent will have, choose resource groups for the agent to manage.',
        id: 'Qly58H',
    },
    contributor: { defaultMessage: 'Contributor', id: '+k5t/y' },
    contributorDescription: {
        defaultMessage:
            'Grants full access to manage all resources, but does not allow you to assign roles in Azure RBAC, manage assignments in Azure Blueprints, or share image galleries.',
        id: 'KzMCPo',
    },
    monitoringContributorDescription: {
        defaultMessage: 'Can read all monitoring data and update monitoring settings.',
        id: 'PrFU82',
    },
    containerAppsContributor: { defaultMessage: 'Container Apps Contributor', id: 'i5OUQE' },
    containerAppsContributorDescription: {
        defaultMessage: 'Full management of Container Apps, including creation, deletion, and updates.',
        id: 'Mnvpbx',
    },
    logAnalyticsReader: { defaultMessage: 'Log Analytics Reader', id: 'sI+CCC' },
    logAnalyticsReaderDescription: {
        defaultMessage:
            'View and search all monitoring data as well as view monitoring settings, including viewing the configuration of Azure diagnostics on all Azure resources.',
        id: 'Oom2N7',
    },
    websitesContributor: { defaultMessage: 'Website Contributor', id: 'xtkizV' },
    websitesContributorDescription: {
        defaultMessage: 'Manage websites, but not web plans. Does not allow you to assign roles.',
        id: '3zLsNR',
    },
    webPlanContributor: { defaultMessage: 'Web Plan Contributor', id: '1YPTmM' },
    webPlanContributorDescription: {
        defaultMessage: 'Lets you manage the web plans for websites, but not access to them.',
        id: 'jJE3xY',
    },
    reader: { defaultMessage: 'Reader', id: '3nhWFW' },
    readerDescription: { defaultMessage: 'View all resources, but does not allow you to make any changes.', id: 'LSaaxU' },
    containerAppsOperator: { defaultMessage: 'Container Apps Operator', id: '/WrP/v' },
    containerAppsOperatorDescription: { defaultMessage: 'Read, logstream and exec into Container Apps.', id: 'gn/nvJ' },
    azureKubernetesServiceRbacReader: { defaultMessage: 'Azure Kubernetes Service RBAC Reader', id: 'RrsyUh' },
    azureKubernetesServiceRbacReaderDescription: {
        defaultMessage:
            'Allows read-only access to see most objects in a namespace. It does not allow viewing roles or role bindings. This role does not allow viewing Secrets, since reading the contents of Secrets enables access to ServiceAccount credentials in the namespace, which would allow API access as any ServiceAccount in the namespace (a form of privilege escalation). Applying this role at cluster scope will give access across all namespaces.',
        id: 'gC4xMY',
    },
    azureKubernetesServiceClusterUserRole: { defaultMessage: 'Azure Kubernetes Service Cluster User Role', id: '5V+Txp' },
    azureKubernetesServiceClusterUserRoleDescription: {
        defaultMessage: 'List cluster user credential action.',
        id: 'Bcx/Gz',
    },
    azureKubernetesServiceClusterAdmin: { defaultMessage: 'Azure Kubernetes Service Cluster Admin', id: 'RStTJp' },
    azureKubernetesServiceClusterAdminDescription: {
        defaultMessage: 'List cluster admin credential action.',
        id: '4kCXiz',
    },
    azureKubernetesServiceRbacClusterAdmin: { defaultMessage: 'Azure Kubernetes Service RBAC Cluster Admin', id: 'YZIFAO' },
    azureKubernetesServiceRbacClusterAdminDescription: {
        defaultMessage: 'Lets you manage all resources in the cluster.',
        id: 'nBPow3',
    },
    azureMonitorMonitoringContributor: { defaultMessage: 'Monitoring Contributor', id: 'TAm7bB' },
    azureMonitorMonitoringContributorDescription: {
        defaultMessage: 'Read and write Azure Monitor monitoring settings and data.',
        id: 'mkhNnB',
    },
    applicationInsightsComponentContributor: {
        defaultMessage: 'Application Insights Component Contributor',
        id: 'VlBNux',
    },
    applicationInsightsComponentContributorDescription: {
        defaultMessage: 'Manage Application Insights components.',
        id: 'pqgzm0',
    },
    logAnalyticsContributor: { defaultMessage: 'Log Analytics Contributor', id: 'e0a3XV' },
    logAnalyticsContributorDescription: {
        defaultMessage: 'Read all monitoring data and edit monitoring settings.',
        id: '6zUWZ/',
    },
    postgreSqlContributor: { defaultMessage: 'PostgreSQL Contributor', id: 'gzx/k1' },
    postgreSqlContributorDescription: { defaultMessage: 'TODO', id: 'RVf7gC' }, // TODO
    redisCacheContributor: { defaultMessage: 'Redis Cache Contributor', id: '8nBFW4' },
    redisCacheContributorDescription: { defaultMessage: 'Manage without access.', id: 'hO1Iog' },
    sqlDbContributor: { defaultMessage: 'SQL DB Contributor', id: 'hfIdUs' },
    sqlDbContributorDescription: {
        defaultMessage: "Manage without access. Can't manage security policies or parent SQL servers.",
        id: 'p5T+zv',
    },
    storageBlobDataContributor: { defaultMessage: 'Storage Blob Data Contributor', id: 'ND2EUR' },
    storageBlobDataContributorDescription: {
        defaultMessage: 'Read, write, and delete Azure Storage containers and blobs.',
        id: 'uRMqBi',
    },
    documentDbAccountContributor: { defaultMessage: 'DocumentDB Account Contributor', id: 'ABo5XY' },
    documentDbAccountContributorDescription: { defaultMessage: 'Can read Azure Cosmos DB account data.', id: 'vfndow' },
    storageBlobDataReader: { defaultMessage: 'Storage Blob Data Reader', id: 'Q3p3sz' },
    storageBlobDataReaderDescription: {
        defaultMessage: 'Allows for read access to Azure Storage blob containers and data.',
        id: '4ii5zj',
    },
    monitoringReader: { defaultMessage: 'Monitoring Reader', id: 'Sr4IbA' },
    monitoringReaderDescription: { defaultMessage: 'Can read all monitoring data.', id: 'xdMkcg' },
    storageAccountContributor: { defaultMessage: 'Storage Account Contributor', id: 'cTzjJg' },
    storageAccountContributorDescription: {
        defaultMessage:
            'Lets you manage storage accounts, including accessing storage account keys which provide full access to storage account data.',
        id: 'xXhn+h',
    },
    virtualMachineContributor: { defaultMessage: 'Virtual Machine Contributor', id: 'PXg8+x' },
    virtualMachineContributorDescription: {
        defaultMessage:
            'Lets you manage virtual machines, but not access to them, and not the virtual network or storage account they are connected to.',
        id: 'AeWmvh',
    },
    postgreSqlFlexibleServerLongTermRetentionBackupRole: {
        defaultMessage: 'PostgreSQL Flexible Server Long Term Retention Backup Role',
        id: 'WLw9E7',
    },
    postgreSqlFlexibleServerLongTermRetentionBackupRoleDescription: {
        defaultMessage: 'Manage long-term retention backups for PostgreSQL Flexible Server.',
        id: 'XtnlO8',
    },
    sqlManagedInstanceContributor: { defaultMessage: 'SQL Managed Instance Contributor', id: 'SuVToZ' },
    sqlManagedInstanceContributorDescription: { defaultMessage: 'Manage SQL Managed Instances.', id: '/8MshI' },
    sqlServerContributor: { defaultMessage: 'SQL Server Contributor', id: 'ss/NWY' },
    sqlServerContributorDescription: { defaultMessage: 'Manage SQL servers and their security policies.', id: '0Dhe75' },
    dataFactoryContributor: { defaultMessage: 'Data Factory Contributor', id: 'Wtf3vL' },
    dataFactoryContributorDescription: { defaultMessage: 'Manage Azure Data Factory instances.', id: '0te2Ra' },
    hdInsightOnAksClusterAdmin: { defaultMessage: 'HDInsight on AKS Cluster Admin', id: 'NcxGiD' },
    hdInsightOnAksClusterAdminDescription: { defaultMessage: 'Administer HDInsight clusters on AKS.', id: 'ixb1SP' },
    hdInsightOnAksClusterPoolAdmin: { defaultMessage: 'HDInsight on AKS Cluster Pool Admin', id: 'pAFuFx' },
    hdInsightOnAksClusterPoolAdminDescription: { defaultMessage: 'Administer HDInsight cluster pools.', id: 'WygVDv' },
    azureMlComputeOperator: { defaultMessage: 'AzureML Compute Operator', id: 'Wc5b/J' },
    azureMlComputeOperatorDescription: { defaultMessage: 'Operate Azure Machine Learning compute resources.', id: 'ciB+oy' },
    azureMlDataScientist: { defaultMessage: 'AzureML Data Scientist', id: 'l5sNim' },
    azureMlDataScientistDescription: { defaultMessage: 'Perform data science tasks in Azure Machine Learning.', id: 'i6cLLM' },
    cognitiveServicesContributor: { defaultMessage: 'Cognitive Services Contributor', id: 'Dff3ms' },
    cognitiveServicesContributorDescription: { defaultMessage: 'Manage Cognitive Services accounts.', id: 'wxlJSs' },
    cognitiveServicesOpenAiContributor: { defaultMessage: 'Cognitive Services OpenAI Contributor', id: 'HQhDfV' },
    cognitiveServicesOpenAiContributorDescription: { defaultMessage: 'Manage Azure OpenAI resources.', id: 'ZsLOg3' },
    cognitiveServicesCustomVisionContributor: {
        defaultMessage: 'Cognitive Services Custom Vision Contributor',
        id: '7+b0J0',
    },
    cognitiveServicesCustomVisionContributorDescription: {
        defaultMessage: 'Manage Custom Vision projects.',
        id: '/gCtdO',
    },
    cognitiveServicesLanguageWriter: { defaultMessage: 'Cognitive Services Language Writer', id: 'aqNZbD' },
    cognitiveServicesLanguageWriterDescription: {
        defaultMessage: 'Write access to Language service resources.',
        id: 'CMaDRa',
    },
    cognitiveServicesLuisWriter: { defaultMessage: 'Cognitive Services LUIS Writer', id: '64zSh3' },
    cognitiveServicesLuisWriterDescription: { defaultMessage: 'Write access to LUIS applications.', id: 'cRTR/A' },
    cognitiveServicesQnaMakerEditor: { defaultMessage: 'Cognitive Services QnA Maker Editor', id: 'rjgOC5' },
    cognitiveServicesQnaMakerEditorDescription: { defaultMessage: 'Edit QnA Maker knowledge bases.', id: 'mAyw3x' },
    cognitiveServicesSpeechContributor: { defaultMessage: 'Cognitive Services Speech Contributor', id: 'fFyuVF' },
    cognitiveServicesSpeechContributorDescription: {
        defaultMessage: 'Contribute to Speech service resources.',
        id: '6YXj/s',
    },
    healthcareAgentEditor: { defaultMessage: 'Healthcare Agent Editor', id: 't9I1dY' },
    healthcareAgentEditorDescription: { defaultMessage: 'Edit Healthcare APIs agent configurations.', id: 'Phji5P' },
    searchServiceContributor: { defaultMessage: 'Search Service Contributor', id: 'P3qxV2' },
    searchServiceContributorDescription: { defaultMessage: 'Manage Azure Search services.', id: 'ecG+OD' },
    azureDigitalTwinsDataOwner: { defaultMessage: 'Azure Digital Twins Data Owner', id: 'QIY3dQ' },
    azureDigitalTwinsDataOwnerDescription: { defaultMessage: 'Full access to Azure Digital Twins data.', id: '87v+WY' },
    deviceProvisioningServiceDataContributor: {
        defaultMessage: 'Device Provisioning Service Data Contributor',
        id: '5UfRjw',
    },
    deviceProvisioningServiceDataContributorDescription: {
        defaultMessage: 'Manage Device Provisioning Service data.',
        id: '7N87nD',
    },
    deviceUpdateAdministrator: { defaultMessage: 'Device Update Administrator', id: 'e3itcX' },
    deviceUpdateAdministratorDescription: { defaultMessage: 'Administer Device Update accounts.', id: 'hF5T80' },
    iotHubDataContributor: { defaultMessage: 'IoT Hub Data Contributor', id: 'xqwf/7' },
    iotHubDataContributorDescription: { defaultMessage: 'Full access to IoT Hub data.', id: 'R1RX2a' },
    iotHubRegistryContributor: { defaultMessage: 'IoT Hub Registry Contributor', id: 'lvNWLS' },
    iotHubRegistryContributorDescription: { defaultMessage: 'Manage IoT Hub device registry.', id: '2PnnDB' },
    iotHubTwinContributor: { defaultMessage: 'IoT Hub Twin Contributor', id: '5Sc5rT' },
    iotHubTwinContributorDescription: { defaultMessage: 'Manage IoT Hub device twins.', id: 'gZ5fZs' },
    apiManagementServiceContributor: { defaultMessage: 'API Management Service Contributor', id: 'rZaqtB' },
    apiManagementServiceContributorDescription: { defaultMessage: 'Manage API Management services.', id: 'dR8VUW' },
    apiManagementServiceOperatorRole: { defaultMessage: 'API Management Service Operator Role', id: 'yo67XU' },
    apiManagementServiceOperatorRoleDescription: { defaultMessage: 'Operate API Management services.', id: 'xmsrBu' },
    apiManagementWorkspaceContributor: { defaultMessage: 'API Management Workspace Contributor', id: 'EdEthU' },
    apiManagementWorkspaceContributorDescription: { defaultMessage: 'Manage API Management workspaces.', id: 'd2GmfJ' },
    appConfigurationContributor: { defaultMessage: 'App Configuration Contributor', id: 'IEFW3Y' },
    appConfigurationContributorDescription: { defaultMessage: 'Manage App Configuration stores.', id: '2LQx4N' },
    azureServiceBusDataOwner: { defaultMessage: 'Azure Service Bus Data Owner', id: 'H3ooTI' },
    azureServiceBusDataOwnerDescription: { defaultMessage: 'Full access to Azure Service Bus data.', id: 'nrAnZy' },
    logicAppContributor: { defaultMessage: 'Logic App Contributor', id: 'C3PGqj' },
    logicAppContributorDescription: { defaultMessage: 'Manage Logic Apps.', id: 'ZNMCbm' },
    workbookContributor: { defaultMessage: 'Workbook Contributor', id: '4MeTpL' },
    workbookContributorDescription: { defaultMessage: 'Manage Azure Monitor workbooks.', id: 'Z7Aj91' },
    azureCenterForSapSolutionsAdministrator: {
        defaultMessage: 'Azure Center for SAP solutions administrator',
        id: 'Yp7NCi',
    },
    azureCenterForSapSolutionsAdministratorDescription: {
        defaultMessage: 'Administer SAP workloads on Azure.',
        id: 'wbigtI',
    },
    costManagementContributor: { defaultMessage: 'Cost Management Contributor', id: 'oQ/TUW' },
    costManagementContributorDescription: { defaultMessage: 'Manage cost analysis and budgets.', id: 'sRb5P9' },
    // Reader roles
    hdInsightClusterOperator: { defaultMessage: 'HDInsight Cluster Operator', id: 'xGPsyJ' },
    hdInsightClusterOperatorDescription: {
        defaultMessage: 'Lets you read and modify HDInsight cluster configurations.',
        id: 'XJ+Lww',
    },
    cognitiveServicesCustomVisionReader: { defaultMessage: 'Cognitive Services Custom Vision Reader', id: 'u0xiAh' },
    cognitiveServicesCustomVisionReaderDescription: {
        defaultMessage: "Read-only actions in the project. Readers can't create or update the project.",
        id: 'eBvTo6',
    },
    cognitiveServicesDataReader: { defaultMessage: 'Cognitive Services Data Reader', id: 'SCjiXP' },
    cognitiveServicesDataReaderDescription: { defaultMessage: 'Lets you read Cognitive Services data.', id: 'IQaKwH' },
    cognitiveServicesLanguageReader: { defaultMessage: 'Cognitive Services Language Reader', id: '8NHZQV' },
    cognitiveServicesLanguageReaderDescription: {
        defaultMessage: 'Has access to Read and Test functions under Language portal.',
        id: 'vbdOl/',
    },
    cognitiveServicesLuisReader: { defaultMessage: 'Cognitive Services LUIS Reader', id: 'Pwen/L' },
    cognitiveServicesLuisReaderDescription: {
        defaultMessage: 'Has access to Read and Test functions under LUIS.',
        id: 'aGL+Qo',
    },
    cognitiveServicesQnaMakerReader: { defaultMessage: 'Cognitive Services QnA Maker Reader', id: 'Yk6Co7' },
    cognitiveServicesQnaMakerReaderDescription: {
        defaultMessage: "Let's you read and test a KB only.",
        id: 'Dx3Xj3',
    },
    cognitiveServicesUsagesReader: { defaultMessage: 'Cognitive Services Usages Reader', id: 'c1EiBR' },
    cognitiveServicesUsagesReaderDescription: {
        defaultMessage: 'Minimal permission to view Cognitive Services usages.',
        id: 'GoSIa4',
    },
    searchIndexDataReader: { defaultMessage: 'Search Index Data Reader', id: 'j5Yfyr' },
    searchIndexDataReaderDescription: {
        defaultMessage: 'Grants read access to Azure Cognitive Search index data.',
        id: 'pSfQh6',
    },
    azureDigitalTwinsDataReader: { defaultMessage: 'Azure Digital Twins Data Reader', id: 'hrdmcd' },
    azureDigitalTwinsDataReaderDescription: {
        defaultMessage: 'Read-only role for Digital Twins data-plane properties.',
        id: 'CFJ1OD',
    },
    deviceProvisioningServiceDataReader: { defaultMessage: 'Device Provisioning Service Data Reader', id: 'bN0x+w' },
    deviceProvisioningServiceDataReaderDescription: {
        defaultMessage: 'Allows for full read access to Device Provisioning Service data-plane properties.',
        id: 'dQ5/dh',
    },
    deviceUpdateReader: { defaultMessage: 'Device Update Reader', id: 't3D4PH' },
    deviceUpdateReaderDescription: {
        defaultMessage: 'Gives you read access to management and content operations, but does not allow making changes.',
        id: '+/nU/s',
    },
    iotHubDataReader: { defaultMessage: 'IoT Hub Data Reader', id: 'd8dECB' },
    iotHubDataReaderDescription: {
        defaultMessage: 'Allows for full read access to IoT Hub data-plane properties.',
        id: 'KAYpG9',
    },
    apiManagementServiceReader: { defaultMessage: 'API Management Service Reader Role', id: '4TnjxL' },
    apiManagementServiceReaderDescription: { defaultMessage: 'Read-only access to service and APIs.', id: '8aHHLj' },
    apiManagementWorkspaceReader: { defaultMessage: 'API Management Workspace Reader', id: 'XYSJsS' },
    apiManagementWorkspaceReaderDescription: {
        defaultMessage: 'Has read-only access to entities in the workspace. This role should be assigned on the workspace scope.',
        id: 'UZS12+',
    },
    appConfigurationReader: { defaultMessage: 'App Configuration Reader', id: 'pDUFq5' },
    appConfigurationReaderDescription: {
        defaultMessage: 'Grants permission for read operations for App Configuration resources.',
        id: 'ENnkRe',
    },
    logicAppOperator: { defaultMessage: 'Logic App Operator', id: 'T5+AEf' },
    logicAppOperatorDescription: { defaultMessage: 'Lets you read, enable and disable logic app.', id: '01lT1B' },
    workbookReader: { defaultMessage: 'Workbook Reader', id: 'hPj49L' },
    workbookReaderDescription: { defaultMessage: 'Can read workbooks.', id: '+l+XEu' },
    azureCenterForSapSolutionsReader: { defaultMessage: 'Azure Center for SAP solutions reader', id: 'BKSv0l' },
    azureCenterForSapSolutionsReaderDescription: {
        defaultMessage: 'This role provides read access to all capabilities of Azure Center for SAP solutions.',
        id: 'NAAdaF',
    },
    costManagementReader: { defaultMessage: 'Cost Management Reader', id: '5wGcN7' },
    costManagementReaderDescription: {
        defaultMessage: 'Can view cost data and configuration (e.g. budgets, exports).',
        id: '3t/IhV',
    },
});
