<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Azure.AI.OpenAI" />
	  <PackageReference Include="Azure.Monitor.Query" />
	  <PackageReference Include="Azure.ResourceManager.AppContainers" />
    <PackageReference Include="Azure.ResourceManager.Authorization" />
	  <PackageReference Include="Azure.ResourceManager.ContainerRegistry" />
    <PackageReference Include="Azure.ResourceManager.ContainerService" />
	  <PackageReference Include="Azure.ResourceManager.Network" />
	  <PackageReference Include="Microsoft.Azure.Management.Monitor.Fluent" />
	  <PackageReference Include="Microsoft.Graph" />
    <PackageReference Include="ScottPlot" />
    <PackageReference Include="Microsoft.SemanticKernel" />
    <PackageReference Include="Microsoft.SemanticKernel.Abstractions" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureOpenAI" />
    <PackageReference Include="Octokit" />
    <PackageReference Include="KubernetesClient" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agent.Core\Agent.Core.csproj" />
    <ProjectReference Include="..\Agent.Graph\Agent.Graph.csproj" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Agent.Analyzers\Agent.Analyzers.csproj" OutputItemType="Analyzer" />
	</ItemGroup>

</Project>
