<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Agent.Tests.Unit</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="antares.kubectl" GeneratePathProperty="true" />
    <PackageReference Include="Azure.AI.OpenAI" />
    <PackageReference Include="Azure.Monitor.Query" />
    <PackageReference Include="Azure.ResourceManager.ApiManagement" />
    <PackageReference Include="Azure.ResourceManager.AppContainers" />
    <PackageReference Include="Azure.ResourceManager.Authorization" />
    <PackageReference Include="Azure.ResourceManager.ContainerRegistry" />
    <PackageReference Include="Azure.ResourceManager.ContainerService" />
	  <PackageReference Include="Azure.ResourceManager.Network" />
	  <PackageReference Include="Azure.Search.Documents" />
    <PackageReference Include="Azure.ResourceManager.OperationalInsights" />
	  <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.VisualStudio.Services.Search.Client" />
    <PackageReference Include="SharpZipLib" />
    <PackageReference Include="Microsoft.Azure.Management.Monitor.Fluent" />
    <PackageReference Include="Microsoft.Diagnostics.Runtime" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" />
    <PackageReference Include="Microsoft.Graph" />
    <PackageReference Include="Microsoft.TeamFoundationServer.Client" />
    <PackageReference Include="ScottPlot" />
    <PackageReference Include="Microsoft.SemanticKernel" />
    <PackageReference Include="Microsoft.SemanticKernel.Abstractions" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureOpenAI" />
    <PackageReference Include="Octokit" />
    <PackageReference Include="KubernetesClient" />
    <PackageReference Include="ReverseMarkdown" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agent.Core\Agent.Core.csproj" />
    <ProjectReference Include="..\Agent.Graph\Agent.Graph.csproj" />
    <ProjectReference Include="..\Agent.Prometheus\Agent.Prometheus.csproj" />
    <ProjectReference Include="..\Agent.Framework\Agent.Framework.csproj" />
    <ProjectReference Include="..\Agent.Data\Agent.Data.csproj" />
    <ProjectReference Include="..\Agent.ScheduledTasks\Agent.ScheduledTasks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agent.Analyzers\Agent.Analyzers.csproj" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Plugins\Definitions\Queries\*.kql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Playbooks\**\*.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Playbooks\**\*.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="$(PkgAntares_Kubectl)\kubectl.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="Plugins\Definitions\Queries\**\*.kql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Plugins\Definitions\Queries\AzureFunctions\FlexConsumption\" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Plugins\Definitions\Queries\ColdStart\" />
  </ItemGroup>

</Project>
