let _startTime = datetime("##startTime##");
let _endTime = datetime("##endTime##");
let _siteName = "##siteName##";
let _eventPrimaryStampName = "##eventPrimaryStampName##";
let _functionName = "##functionName##";
FunctionsLogs
| where PreciseTimeStamp between (_startTime .. _endTime)
| where AppName =~ _siteName
| where EventStampName == _eventPrimaryStampName
| where FunctionName == _functionName
| where Summary startswith "Trigger Details"
| project PreciseTimeStamp, EventName, Summary, Level
| parse Summary with "Trigger Details: MessageId: " MessageId ", SequenceNumber: " SequenceNumber ", DeliveryCount: " DeliveryCount ", EnqueuedTimeUtc: " EnqueuedTimeUtc ", LockedUntilUtc: " LockedUntilUtc ", SessionId: " SessionId
| take 3
