let _startTime = datetime("##startTime##");
let _endTime = datetime("##endTime##");
let _siteName = "##siteName##";
let _eventPrimaryStampName = "##eventPrimaryStampName##";
let _functionName = "##functionName##";
FunctionsLogs
| where PreciseTimeStamp between (_startTime .. _endTime)
| where AppName =~ _siteName
| where EventStampName == _eventPrimaryStampName
| where FunctionName == _functionName
| where EventName == "BlobDoesNotMatchPattern"
| project PreciseTimeStamp, EventName, Summary, EventIpAddress, EventPrimaryStampName, FunctionName
| take 100
